### ISSUE TITLE
using  HTTP_PROXY and HTTPS_PROXY is somehow breaking the solution start with code 403

### ISSUE THREAD

**Issue by izvictor** [dotnet/aspire#1012]
Hello,

I'm trying to use the .NET Aspire Starter Application on my corporate workstation and when launching the AppHost I have the following error :
![image](https://github.com/dotnet/aspire/assets/98562/cb8af5c8-4808-4ce9-823e-25b06d157396)
![image](https://github.com/dotnet/aspire/assets/98562/ef587d6b-f420-45c0-b288-01f870114cd4)

I have defined the NO_PROXY environment variable 
![image](https://github.com/dotnet/aspire/assets/98562/b3ec0b38-22fc-4a5c-a439-1479667ae49c)

but this does not change the error.
How can I disable proxy for local connections ?
Thanks for help

**Comment by mitchdenny** [comment]
Try the following:

```env
NO_PROXY=localhost,127.0.01,::1
```

For that API call its actually resolving an IPv6 address which doesn't match to your no proxy list.

**Comment by izvictor** [comment]
Thanks @mitchdenny for the proposition but adding IPv6 localhost adresse does not solve the issue:

![image](https://github.com/dotnet/aspire/assets/98562/135fe474-9d55-4a90-b8a8-5f8a1db98830)

If I check the stack trace the issue is happening in the k86 C# client at the **SendRequestRaw**
```
 at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.DeleteClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, String name, V1DeleteOptions body, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, String dryRun, IReadOnlyDictionary`2 customHeaders, CancellationT
```
Correct me if I'm wrong but would it be possible that the **kubernetes-client** used by aspire does not support [NO_PROXY](https://github.com/kubernetes-client/csharp/issues/568) variable ?

**Comment by mitchdenny** [comment]
That's strange I was able to reproduce your issue and then solve it by appending the IPv6 loop back.

Can you try removing the http and https proxy variables and just have the no proxy variable?

**Comment by izvictor** [comment]
Hello @mitchdenny ,
Thanks for answer, indeed removing the **HTTP_PROXY** and **HTTPS_PROXY** variables the solution starts correctly. Well this means the presence of **HTTP_PROXY** and **HTTPS_PROXY** is somehow breaking the solution start. 
Regards.

**Comment by chrisdcmoore** [comment]
I just did a bit of debugging of this, and I had to add `[::1]` (*with* the square brackets) to my `NO_PROXY` list, as the `Uri.Host` property in the request was `[::1]` and the bypass evaluation is done [via string matching](https://github.com/dotnet/runtime/blob/3e551673a1215a3fdad2a38b4c406895ef29703c/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.cs#L284)
