### ISSUE TITLE
ExcludeFromManifest Fails

### ISSUE THREAD

**Issue by rudiv** [dotnet/aspire#1595]
As per the title calling `ExcludeFromManifest` fails in some use cases with the following error:

```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at Aspire.Hosting.ResourceBuilderExtensions.ExcludeFromManifest[T](IResourceBuilder`1 builder) in /_/src/Aspire.Hosting/Extensions/ResourceBuilderExtensions.cs:line 365
   at Program.<Main>$(String[] args)
```

The offending LOC is [here](https://github.com/dotnet/aspire/blob/60b2529dedede70430db881f76c4a50eeafaf9ce/src/Aspire.Hosting/Extensions/ResourceBuilderExtensions.cs#L363C15-L363C15) where it's explicitly removing the annotations that it's iterating over.

**Comment by davidfowl** [comment]
Thanks @rudiv ! Would you like to send a PR to fix?

**Comment by mitchdenny** [comment]
Not feature work, pushing to P5.

**Comment by davidfowl** [comment]
This was fixed in https://github.com/dotnet/aspire/pull/2052
