### ISSUE TITLE
Improve ServerVersion.AutoDetect in AddMySqlDbContext

### ISSUE THREAD

**Issue by bgrainger** [dotnet/aspire#1866]
Background: Pomelo.EntityFrameworkCore.MySql (the EF Core library for MySQL) requires a `ServerVersion` object (as well as a connection string) in the `UseMySql` extension method used to configure EF Core. This allows it to configure various things (such as DDL syntax and available column types) based on the MySQL-compatible server version the user is connecting to.

* https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql?tab=readme-ov-file#2-services-configuration
* https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options#mandatory-parameters

This value needs to be determined before the `UseMySql` call can be made. One way to do that is via `ServerVersion.AutoDetect(connectionString)` which establishes a DB connection and queries the remote server version. As noted in https://github.com/dotnet/aspire/pull/1161#pullrequestreview-1844557984 this can cause a critical failure at startup, e.g., if the Docker container isn't ready yet.

One mitigation might just be to retry `MaxRetryCount` times, waiting for the Docker container to become ready.

Or perhaps in the local, Docker-based development scenario, the `ContainerImageAnnotation` could be read to determine the container image being used, which could let the code synthesize the appropriate corresponding ServerVersion string? (Note that it's currently hardcoded to `mysql:latest` so there's not actually a chance the user is using this code with, say, `mariadb:11.0`, but perhaps that might be configurable in the future?)

Or perhaps this issue should be kicked back to the PomeloFoundation project, to make "AutoDetect" possible to be deferred until the first database connection is successfully made. (I don't know how much work that would be in the Pomelo EF Core driver.) Related issue: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1603.

**Comment by eerhardt** [comment]
After thinking about this some more, I think @sebastienros's work in #1706 which will fix #1403 will make this code all go away in the Aspire Component. And users will need to just use the Pomelo.EntityFrameworkCore.MySql APIs to add the DbContext to DI.

**Comment by bgrainger** [comment]
From https://github.com/dotnet/aspire/issues/1403:

> we should have the dev user call directly into the EF DependencyInjection APIs

Redesigning the Pomelo component to adopt this pattern will side-step the `ServerVersion` issues.

**Comment by eerhardt** [comment]
@bgrainger - with https://github.com/dotnet/aspire/pull/2125 and #1403, we decided to keep the current `AddXXXContext` methods, but also add new `EnrichXXXContext` methods. So the original issue is going to have to be addressed - when we try to auto-detect the server version, we aren't doing retries.

Is this something you can address? Or should we remove this functionality and just force users to have to set the version until the underlying Pomelo library addresses this?

**Comment by bgrainger** [comment]
I think I can take a look at this. 

Also, Pomelo 8.0.0 just shipped with support for `MySqlDataSource` so there may be some improvements to be made just from updating that dependency.

**Comment by bgrainger** [comment]
@eerhardt I think I know how I want to solve this, but I'm actually having trouble reproducing the original problem that was noted, either in Test Explorer or via `.\build.cmd -test`; will keep working on it.

**Comment by eerhardt** [comment]
> I'm actually having trouble reproducing the original problem

Take this change: https://github.com/dotnet/aspire/commit/b793b6a836b81ea348b1192c579386c82ec8c196

Then `dotnet run --project .\playground\mysql\MySqlDb.AppHost\MySqlDb.AppHost.csproj`

Look in the dashboard (probably http://localhost:15224/), you'll see `apiservice` crashed.

Look at its console logs:

```
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Couldn't connect to server
 ---> MySqlConnector.MySqlEndOfStreamException: An incomplete response was received from the server
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.ReadPayloadAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 424
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 924
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 462
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 604
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, Action`4 logMessage, Int64 startingTimestamp, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 428
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, Action`4 logMessage, Int64 startingTimestamp, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 433
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int64 startingTimestamp, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 113
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int64 startingTimestamp, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 146
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 919
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 419
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 381
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Microsoft.Extensions.Hosting.AspireEFMySqlExtensions.<>c__DisplayClass2_0`1.<AddMySqlDbContext>g__ConfigureDbContext|1(IServiceProvider serviceProvider, DbContextOptionsBuilder dbContextOptionsBuilder) in C:\git\aspire2\src\Components\Aspire.Pomelo.EntityFrameworkCore.MySql\AspireEFMySqlExtensions.cs:line 82
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass6_0`1.<AddPoolingOptions>b__0(IServiceProvider sp, DbContextOptionsBuilder ob)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
```

Notice what is trying to do the connect:

```
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 381
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Microsoft.Extensions.Hosting.AspireEFMySqlExtensions.<>c__DisplayClass2_0`1.<AddMySqlDbContext>g__ConfigureDbContext|1(IServiceProvider serviceProvider, DbContextOptionsBuilder dbContextOptionsBuilder) in C:\git\aspire2\src\Components\Aspire.Pomelo.EntityFrameworkCore.MySql\AspireEFMySqlExtensions.cs:line 82
```

**Comment by bgrainger** [comment]
https://github.com/dotnet/aspire/pull/2386
