### ISSUE TITLE
StaticWebAssets fail when BlazorWebApp referenced and then deleted.

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1897]
Repro is:

- Add a reference to a blazor web app
- Run the app (you'll see static web assets copied into the bin folder of the apphost)
- Delete the blazor project
- Run the app
- BOOM

This feels like a bug somewhere else though.

Original:

We should be using the slim builder and never loading static web assets in the app host.

![image](https://github.com/dotnet/aspire/assets/95136/63799be3-b8e8-4d4c-8d76-db980b633744)

**Comment by davidfowl** [comment]
Ok saw it a 2nd time. I think we need to fix this for P2. Make sure we're not using static web assets at all.

**Comment by mitchdenny** [comment]
Assuming you mean P3 :)

**Comment by davidfowl** [comment]
```
Unhandled exception. System.AggregateException: One or more errors occurred. (C:\Users\davifowl\source\repos\AppHost3\BlazorApp2\BlazorApp2\obj\Debug\net8.0\scopedcss\projectbundle\)
 ---> System.IO.DirectoryNotFoundException: C:\Users\davifowl\source\repos\AppHost3\BlazorApp2\BlazorApp2\obj\Debug\net8.0\scopedcss\projectbundle\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.InitializeHosting(BootstrapHostBuilder bootstrapHostBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder()
   at Aspire.Hosting.Dashboard.DashboardServiceHost..ctor(DistributedApplicationOptions options, DistributedApplicationModel applicationModel, KubernetesService kubernetesService, IEnvironmentVariables environmentVariables, IOptions`1 publishingOptions, ILoggerFactory loggerFactory, IConfigureOptions`1 loggerOptions) in /_/src/Aspire.Hosting/Dashboard/DashboardServiceHost.cs:line 69
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Aspire.Hosting.DistributedApplicationBuilder.<>c.<.ctor>b__14_1(IServiceProvider sp) in /_/src/Aspire.Hosting/DistributedApplicationBuilder.cs:line 63
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 147
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 155
   at Program.<Main>$(String[] args) in C:\Users\davifowl\source\repos\AppHost3\AppHost3\Program.cs:line 3
```

**Comment by davidfowl** [comment]
@eerhardt Might this be related to your changes? I think it has to do with caching happening somewhere. I had a project called  BlazorApp2 at some point, then I deleted it. My apphost is empty now and has no project references, but it explodes like this.

First, I don't know how scoped CSS gets injected into the AppHost project in the first place. Secondly, it seems to be stuck there. I think if I do a clean rebuild it'll work.

cc @SteveSandersonMS @javiercn How does scoped css get injected and how do we disable it?

**Comment by davidfowl** [comment]
OK this is not random, we need to fix it for p3. I think I know why it happens.

We import static web assets explicitly. 

https://github.com/dotnet/aspire/blob/f954f614d45ea4085e94abb435ad6bcbb8280911/src/Aspire.Hosting/build/Aspire.Hosting.targets#L3

**Comment by davidfowl** [comment]
Repro is:

- Add a reference to a blazor web app
- Run the app (you'll see static web assets copied into the bin folder of the apphost)
- Delete the blazor project
- Run the app
- BOOM

This feels like a bug somewhere else though.
