### ISSUE TITLE
Regression: AppHost no longer runnable if ASP.NET Core URLS isn't specified

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1928]
This used to work in preview2 but now we blow up instead of falling back to a default port.

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://127.0.0.1:57155
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\davifowl\source\repos\AppHost3\AppHost3
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: ASPNETCORE_URLS environment variable not set.
         at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 202
         at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 91
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.AggregateException: One or more errors occurred. (Command C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0-preview.3.24077.4\tools\dcp.exe start-apiserver --monitor 20940 --detach --kubeconfig "C:\Users\davifowl\AppData\Local\Temp\aspire.tq4j1ctq.p2m\kubeconfig" returned non-zero exit code -1)
 ---> System.InvalidOperationException: Command C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0-preview.3.24077.4\tools\dcp.exe start-apiserver --monitor 20940 --detach --kubeconfig "C:\Users\davifowl\AppData\Local\Temp\aspire.tq4j1ctq.p2m\kubeconfig" returned non-zero exit code -1
   at Aspire.Hosting.Dcp.Process.ProcessUtil.ProcessDisposable.DisposeAsync() in /_/src/Aspire.Hosting/Dcp/Process/ProcessUtil.cs:line 147
   at Aspire.Hosting.Dcp.DcpHostService.DisposeAsync() in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 86
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<DisposeAsync>g__Await|26_0(Int32 i, ValueTask vt, List`1 toDispose)
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>g__DisposeAsync|21_0(Object o)
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 147
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 155
   at Program.<Main>$(String[] args) in C:\Users\davifowl\source\repos\AppHost3\AppHost3\Program.cs:line 6
```

**Comment by v-gaolisa** [comment]
@davidfowl, Today we encountered another issue when running aspire app with vs code and C# Dev Kit:'Time out while waiting for the dashboard to be responsive'.
![image](https://github.com/dotnet/aspire/assets/89128759/1799d2ed-c6e5-4149-a4f3-81477661e22d)

**Comment by davidfowl** [comment]
What version?

**Comment by davidfowl** [comment]
Looks like the dashboard failed to launch?

**Comment by v-gaolisa** [comment]
Yeah, That's it.

**Comment by mitchdenny** [comment]
Is this related to this issue or is it a new one. Maybe we should track in a new issue to avoid confusion.

**Comment by mitchdenny** [comment]
Can you share what you have in your launchsettings.json?

**Comment by davidfowl** [comment]
Seems like a new issue.

**Comment by v-gaolisa** [comment]
@mitchdenny this is launchsetting.json file.
![image](https://github.com/dotnet/aspire/assets/89128759/10a7df3e-2c28-4814-89ed-1ad8b21bdd2a)

**Comment by davidfowl** [comment]
Can you reproduce this consistently @v-gaolisa ?

**Comment by v-gaolisa** [comment]
Yeah, I can reproduce it stably.

**Comment by davidfowl** [comment]
Excellent. Lets try to get a repro then. Can you file a new issue with the steps? Lets see if we can isolate it.

**Comment by v-gaolisa** [comment]
OK, I opened a new issue to tracking it [#2007](https://github.com/dotnet/aspire/issues/2007).
