### ISSUE TITLE
Resource server returned an error while navigating around the dashboard

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1930]
```
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'WatchResources'.
      System.ArgumentNullException: Value cannot be null. (Parameter 'value')
         at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
         at Aspire.V1.Resource.set_State(String value) in /_/artifacts/obj/Aspire.Hosting/Release/net8.0/Dashboard/proto/ResourceService.cs:line 2574
         at Aspire.V1.Resource.FromSnapshot(ResourceSnapshot snapshot) in /_/src/Aspire.Hosting/Dashboard/proto/Partials.cs:line 13
         at Aspire.Hosting.Dashboard.DashboardService.<>c__DisplayClass6_0.<<WatchResources>g__WatchResourcesInternal|0>d.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DashboardService.cs:line 88
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dashboard.DashboardService.<>c__DisplayClass6_0.<<WatchResources>g__WatchResourcesInternal|0>d.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DashboardService.cs:line 78
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dashboard.DashboardService.WatchResources(WatchResourcesRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context) in /_/src/Aspire.Hosting/Dashboard/DashboardService.cs:line 58
         at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
         at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```

**Comment by kvenkatrajan** [comment]
@drewnoakes  can you have a look please?

**Comment by drewnoakes** [comment]
This stems from the Protobuf codegen we use not producing null-annotated code.

In this instance, the `ResourceSnapshot.State` value is `null`, which is not allowed in the `.proto` we have.

Options to fix this:

1. Make the field optional (a breaking change, so not a great option)
2. Pass a default value when `null`
  - Empty string
  - "Unknown" (would this need to be localised?)

I'll submit a PR with the empty string for now.

**Comment by jakoss** [comment]
Is this fix released? I have this issue on preview 4 (on .NET 8) still:
```
Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'WatchResources'.
      System.ArgumentNullException: Value cannot be null. (Parameter 'value')
         at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
         at Google.Protobuf.WellKnownTypes.Value.ForString(String value)
         at Aspire.Hosting.Dashboard.ResourceSnapshot.get_Properties()+MoveNext() in /_/src/Aspire.Hosting/Dashboard/ResourceSnapshot.cs:line 36
         at Aspire.V1.Resource.FromSnapshot(ResourceSnapshot snapshot) in /_/src/Aspire.Hosting/Dashboard/proto/Partials.cs:line 59
         at Aspire.Hosting.Dashboard.DashboardService.<>c__DisplayClass6_0.<<WatchResources>g__WatchResourcesInternal|0>d.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DashboardService.cs:line 88
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dashboard.DashboardService.<>c__DisplayClass6_0.<<WatchResources>g__WatchResourcesInternal|0>d.MoveNext() in /_/src/Aspire.Hosting/Dashboard/DashboardService.cs:line 78
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dashboard.DashboardService.WatchResources(WatchResourcesRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context) in /_/src/Aspire.Hosting/Dashboard/DashboardService.cs:line 58
         at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
         at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)

```
