### ISSUE TITLE
[WebToolsE2E][Aspire][Unstable]Do not start Docker Desktop first, Ctrl + F5 running Aspire Starter App with Redis checked project shows 'No connection could be made because the target machine actively refused it.' in the console window.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#1938]
**REGRESSION INFO**: Not repro on Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.0 Preview 1.0 [34528.15.main]
3. Install SDK 8.0.200
4. Install Aspire Preview 3 latest build 8.0.0-preview.3.24078.5
5. Apply NuGet Feeds
6. Install Docker Desktop

**REPRO STEPS**
1. Do not start Docker Desktop first.
2. Open VS, create a new project > Aspire Starter Application > .NET 8.0 > check 'Use Redis for caching (requires Docker)' > Create
3. Ctrl + F5
4. In the popped 'Start Docker Desktop' dialog, click 'Yes'

**Notes**:

1. If start Docker Desktop first, then open VS and create project, running it will not meet this issue.
2. If quit Docker Desktop, then running the project again, it will not meet this issue. 
3. This issue reproduces unstably.

**ACTUAL**
It shows errors in the console window: No connection could be made because the target machine actively refused it.
![image](https://github.com/dotnet/aspire/assets/82028229/b0d873a3-d64b-49ad-94db-1efd918c20ca)
```
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
Hosting failed to start
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. ([::1]:52594)
---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken) at k8s.AbstractKubernetes.ICustomObjectsOperations_CreateClusterCustomObjectWithHttpMessagesAsync[T](Object body, String group, String version, String plural, String dryRun, String fieldManager, Nullable1 pretty, IReadOnlyDictionary2 customHeaders, CancellationToken cancellationToken) at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.CreateClusterCustomObjectWithHttpMessagesAsync(Object body, String group, String version, String plural, String dryRun, String fieldManager, Nullable1 pretty, IReadOnlyDictionary2 customHeaders, CancellationToken cancellationToken) at Aspire.Hosting.Dcp.KubernetesService.<>c__DisplayClass10_01.<b__0>d.MoveNext() in //src/Aspire.Hosting/Dcp/KubernetesService.cs:line 40
--- End of stack trace from previous location ---
at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 187 at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func2 operation, CancellationToken cancellationToken) in //src/Aspire.Hosting/Dcp/KubernetesService.cs:line 194
at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in //src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 234
at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in //src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 91
at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in //src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65
at Microsoft.Extensions.Hosting.Internal.Host.b__15_1(IHostedService service, CancellationToken token)
at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List1 exceptions, Func3 operation) Unhandled exception. System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. ([::1]:52594)) ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. ([::1]:52594) ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it. at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
at k8s.AbstractKubernetes.ICustomObjectsOperations_CreateClusterCustomObjectWithHttpMessagesAsync[T](Object body, String group, String version, String plural, String dryRun, String fieldManager, Nullable1 pretty, IReadOnlyDictionary2 customHeaders, CancellationToken cancellationToken)
at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.CreateClusterCustomObjectWithHttpMessagesAsync(Object body, String group, String version, String plural, String dryRun, String fieldManager, Nullable1 pretty, IReadOnlyDictionary2 customHeaders, CancellationToken cancellationToken)
at Aspire.Hosting.Dcp.KubernetesService.<>c__DisplayClass10_01.<<CreateAsync>b__0>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 40 --- End of stack trace from previous location --- at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func2 operation, CancellationToken cancellationToken) in //src/Aspire.Hosting/Dcp/KubernetesService.cs:line 187
at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 194 at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 234 at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 91 at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65 at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token) at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List1 exceptions, Func3 operation)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in //src/Aspire.Hosting/DistributedApplication.cs:line 147
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at Aspire.Hosting.DistributedApplication.Run() in //src/Aspire.Hosting/DistributedApplication.cs:line 155
at Program.

$(String[] args) in C:\Users\v-\source\repos\AspireApp1\AspireApp1.AppHost\Program.cs:line 11
C:\Users\v-\source\repos\AspireApp1\AspireApp1.AppHost\bin\Debug\net8.0\AspireApp1.AppHost.exe (process 10992) exited with code -532462766.
Press any key to close this window . . .
```
**EXPECTED**
No error shows and shows dashboard successfully.

**Comment by davidfowl** [comment]
Can you remove "Aspire.Hosting.Dcp" from your appsettings.json?:

```diff
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
-      "Aspire.Hosting.Dcp": "Warning"
    }
  }
}

```

That should give more information on what happened to DCP

**Comment by v-cazhang** [comment]
Hi @davidfowl.
This is an unstable issue, I set up a new machine and did following steps:

1. Do not start Docker Desktop first.
2. Open VS, create a new project > Aspire Starter Application > .NET 8.0 > check 'Use Redis for caching (requires Docker)' > Create
3. Open appsettings.json of AppHost file, commented out the  `"Aspire.Hosting.Dcp": "Warning" `
4. Ctrl + F5
5. In the popped 'Start Docker Desktop' dialog, click 'Yes'

No error shows in debug console:
![image](https://github.com/dotnet/aspire/assets/82028229/528df7a2-ac0f-4f81-9861-b362827ab2fb)

But meets following errors, which is similar with the errors mentioned in https://github.com/dotnet/aspire/issues/1695
![image](https://github.com/dotnet/aspire/assets/82028229/5294e79a-2706-4f35-8ee9-f7cf15d3ba74)

**Comment by davidfowl** [comment]
Doesn't need to be an error in the console. I wanted to see if you could reproduce the problem with these logs so we can get more information.

**Comment by danmoseley** [comment]
We need a stable repro

**Comment by adityamandaleeka** [comment]
I'm unable to repro this either. Confirmed low-pri for preview 3.

**Comment by adityamandaleeka** [comment]
Moving to preview4 for now, let's see if we can get a repro of this. If not, we can close it.

**Comment by v-cazhang** [comment]
I cannot reproduce this issue with a new machine today. This issue doesn't always reproduce.

**Comment by davidfowl** [comment]
Lets close it then and wait to see if any customer runs into it. One thing we might want to do is make the error message better in preview 4.

**Comment by gsm1be** [comment]
I get the same issue when I run the sample on a windows machine. The same sample runs just fine on OSX machine. I'll change the log level also to debug further.
