### ISSUE TITLE
NullRefereneceExcepoin in Structured Logs dashboard

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/aspire#1946]
[Aspire.Hosting 8.0.0-preview.2.23619.3]

I've been getting this exception:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.AspNetCore.SignalR.Core
  StackTrace:
   at Microsoft.AspNetCore.SignalR.ClientProxyExtensions.SendAsync(IClientProxy clientProxy, String method, Object arg1, Object arg2, Object arg3, CancellationToken cancellationToken) in /_/src/SignalR/server/Core/src/ClientProxyExtensions.cs:line 72
```

Complete stack trace:

```
Microsoft.AspNetCore.SignalR.Core.dll!Microsoft.AspNetCore.SignalR.ClientProxyExtensions.SendAsync(Microsoft.AspNetCore.SignalR.IClientProxy clientProxy, string method, object arg1, object arg2, object arg3, System.Threading.CancellationToken cancellationToken) Line 72
Microsoft.AspNetCore.Components.Server.dll!Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.EndInvokeDotNet(Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo invocationInfo, Microsoft.JSInterop.Infrastructure.DotNetInvocationResult invocationResult) Line 98
Microsoft.JSInterop.dll!Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo invocationInfo, string argsJson) Line 137
Microsoft.AspNetCore.Components.Server.dll!Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.BeginInvokeDotNetFromJS.AnonymousMethod__1() Line 379
Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.InvokeAsync.__Execute|8_0((System.Runtime.CompilerServices.AsyncTaskMethodBuilder Completion, System.Action Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext Context) state) Line 67
Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)>(System.Threading.Tasks.Task antecedent, System.Action<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)> callback, (System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext) state) Line 197
[Resuming Async Method]	
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 179
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<PostAsync>d__14<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)>>.MoveNext(System.Threading.Thread threadPoolThread) Line 376
System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask) Line 275
System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.Execute() Line 664
System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 918
System.Private.CoreLib.dll!System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() Line 102
[Async Call Stack]	
[Async] Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)>(System.Threading.Tasks.Task antecedent, System.Action<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)> callback, (System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext) state) Line 193
[Async] Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)>(System.Threading.Tasks.Task antecedent, System.Action<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)> callback, (System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext) state) Line 193
[Async] Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)>(System.Threading.Tasks.Task antecedent, System.Action<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)> callback, (System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext) state) Line 193
[Async] Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)>(System.Threading.Tasks.Task antecedent, System.Action<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)> callback, (System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext) state) Line 193
[Async] Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)>(System.Threading.Tasks.Task antecedent, System.Action<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)> callback, (System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext) state) Line 193
[Async] Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)>(System.Threading.Tasks.Task antecedent, System.Action<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)> callback, (System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext) state) Line 193
[Async] Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync<(System.Threading.SendOrPostCallback, object)>(System.Threading.Tasks.Task antecedent, System.Action<(System.Threading.SendOrPostCallback, object)> callback, (System.Threading.SendOrPostCallback, object) state) Line 193
[Async] Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)>(System.Threading.Tasks.Task antecedent, System.Action<(System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext)> callback, (System.Runtime.CompilerServices.AsyncTaskMethodBuilder, System.Action, Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext) state) Line 193
```

**Comment by paulomorgado** [comment]
I get these logs:

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning
      System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at Aspire.Dashboard.Components.Controls.SummaryDetailsView.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/SummaryDetailsView.razor.cs:line 73
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '8C2yUdvEvRy1Ri84PZo3yU-r1KZ_6Cc5c594lRPcb4U'.
      System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at Aspire.Dashboard.Components.Controls.SummaryDetailsView.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/SummaryDetailsView.razor.cs:line 73
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

right before [this](https://github.com/dotnet/aspnetcore/blob/v8.0.1/src/Components/Server/src/Circuits/RemoteJSRuntime.cs#L93).

As far as I could debug, [this](https://github.com/dotnet/aspnetcore/blob/v8.0.1/src/Components/Server/src/Circuits/RemoteJSRuntime.cs#L185) is never invoked.

**Comment by tlmii** [comment]
This should be fixed by #1729 in the next release

**Comment by tlmii** [comment]
@leslierichardson95 Just to clarify my previous comment, the above fix should ship in Preview 3.

**Comment by drewnoakes** [comment]
@JamesNK can you confirm that your PR fixes this, and close if so?

**Comment by JamesNK** [comment]
This is fixed.

**Comment by davidfowl** [comment]
in preview3?

**Comment by JamesNK** [comment]
Yes

**Comment by JamesNK** [comment]
@paulomorgado You can work around this problem by deleting all Aspire values from local storage:

In Chrome:
1. F12 to open developer console
2. Click Application tab
3. Choose local storage in tree
4. Delete all values
5. Refresh the app
