### ISSUE TITLE
[WebToolsE2E][Aspire] Update existing aspire 8.0 P1 project to 8.0 P3, F5 will encounter an error: "Inner Exception 1: DirectoryNotFoundException".

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#2012]
**REGRESSION INFO:** Repro on Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.0 Preview 1.0 [34530.244.main]
3. Install 8.0.200 RTM SDK
4. Install Aspire Preview 3 latest build 8.0.0-preview.3.24080.1
5. Apply NuGet Feeds

**REPRO STEPS**

1. On Aspire template version 8.0.0-preview.1.23557.2, Open VS, create a new project > ASP.NET Core Web App (Razor Pages) > .NET 8.0 > check 'Enlist in .NET Aspire orchestration' > Create. Or you can open existing aspire 8.0 P1 project.
2. Update Aspire template version to latest 8.0.0-preview.3.24078.5
3. Open the project you just created, build solution and will encounter this bug https://github.com/dotnet/aspire/issues/1944
4. Update 'Aspire.Hosting' version to 8.0.0-preview.3.24080.1
5. Build solution and F5

**ACTUAL**
F5 will encounter an error.
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (C:\Users\v-reinawang\.nuget\packages\microsoft.fluentui.aspnetcore.components\4.0.0-preview.2\staticwebassets\)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run()
   at Program.<Main>$(String[] args) in D:\Users\v-reinawang\Desktop\WebApplication1\WebApplication1.AppHost\Program.cs:line 5

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
DirectoryNotFoundException: C:\Users\v-reinawang\.nuget\packages\microsoft.fluentui.aspnetcore.components\4.0.0-preview.2\staticwebassets\

![image](https://github.com/dotnet/aspire/assets/109339894/28ccd326-5eb1-4482-8244-a8a4ab34a5ff)

**EXPECTED**
The project can run successfully.

**Comment by davidfowl** [comment]
@v-reinawang can you put the entire stack trace in the issue?

**Comment by v-reinawang** [comment]
@davidfowl This is the entire stack trace.

info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
Unhandled exception. System.AggregateException: One or more errors occurred. (C:\Users\v-reinawang\.nuget\packages\microsoft.fluentui.aspnetcore.components\4.0.0-preview.2\staticwebassets\)
 ---> System.IO.DirectoryNotFoundException: C:\Users\v-reinawang\.nuget\packages\microsoft.fluentui.aspnetcore.components\4.0.0-preview.2\staticwebassets\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.InitializeHosting(BootstrapHostBuilder bootstrapHostBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder()
   at Aspire.Hosting.Dashboard.DashboardServiceHost..ctor(DistributedApplicationOptions options, DistributedApplicationModel applicationModel, KubernetesService kubernetesService, IEnvironmentVariables environmentVariables, IOptions`1 publishingOptions, ILoggerFactory loggerFactory, IConfigureOptions`1 loggerOptions) in /_/src/Aspire.Hosting/Dashboard/DashboardServiceHost.cs:line 69
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Aspire.Hosting.DistributedApplicationBuilder.<>c.<.ctor>b__14_1(IServiceProvider sp) in /_/src/Aspire.Hosting/DistributedApplicationBuilder.cs:line 67
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 132
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 153
   at Program.<Main>$(String[] args) in D:\Users\v-reinawang\Desktop\WebApplication1\WebApplication1.AppHost\Program.cs:line 5

**Comment by davidfowl** [comment]
Thanks, this is the same as https://github.com/dotnet/aspire/pull/1923, but reproduced via an upgrade.

**Comment by davidfowl** [comment]
Does the error go away when you do a clean rebuild?

**Comment by v-reinawang** [comment]
Rebuild solution and F5, this issue also repro.

**Comment by davidfowl** [comment]
delete, obj and bin, and rebuild, it should run.

**Comment by v-reinawang** [comment]
Should I delete these two folders directly? I tried removing them but still repro.
![image](https://github.com/dotnet/aspire/assets/109339894/f16b47b1-69f6-441f-a6f9-ae3333474172)

**Comment by davidfowl** [comment]
The ones inside of the WebApplication1.AppHost

**Comment by v-reinawang** [comment]
There is no obj and bin file in WebApplication1.AppHost.

**Comment by davidfowl** [comment]
When you build the solution or run that project, it produces a binary in the bin folder, you should have both a bin and obj for each project.

**Comment by v-reinawang** [comment]
After I deleted the obj and bin folders under WebApplication1.AppHost, rebuild and F5 can be successful.

**Comment by v-reinawang** [comment]
Verify that this issue has been fixed in 8.0.0-preview.3.24081.5
