### ISSUE TITLE
Traces dashboard view freeze/crash when viewing large trace

### ISSUE THREAD

**Issue by ThomasCronholm** [dotnet/aspire#2103]
When pressing View on the span I would like to look at:
![image](https://github.com/dotnet/aspire/assets/25451613/251b1aab-3242-4715-955b-0a26f37228ee)

The dashboard freezes and then after less than a minute I get the following stack-trace in the aspire console window.

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: An item with the same key has already been added. Key: f44344300
      System.ArgumentException: An item with the same key has already been added. Key: f44344300
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at Microsoft.FluentUI.AspNetCore.Components.DataGrid.Infrastructure.InternalGridContext`1.Register(FluentDataGridRow`1 row)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'FYrVbbEoe_KzOf0rV5XKofGa7KRmaeLgNyH1iQ9uODQ'.
      System.ArgumentException: An item with the same key has already been added. Key: f44344300
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at Microsoft.FluentUI.AspNetCore.Components.DataGrid.Infrastructure.InternalGridContext`1.Register(FluentDataGridRow`1 row)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: A task was canceled.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at Microsoft.FluentUI.AspNetCore.Components.FluentDataGrid`1.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'FYrVbbEoe_KzOf0rV5XKofGa7KRmaeLgNyH1iQ9uODQ'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at Microsoft.FluentUI.AspNetCore.Components.FluentDataGrid`1.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
```
Aspire.Hosting version 8.0.0-preview.1.23557.2

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by JamesNK** [comment]
That's a lot of spans.

The span graph is displayed in a fluent data grid. Perhaps its virtualization could be used here.

**Comment by JamesNK** [comment]
Hmm, FluentUI randomly generates row IDs. It's a lottery every time it renders whether there is a conflict and error. The more rows the more tickets to the lottery 😬 

https://github.com/microsoft/fluentui-blazor/blob/0536a0b78fd4e87dd58320a96ef0dfc6a00c997f/src/Core/Identifier.cs#L35

I'll log a bug with them.

**Comment by vnbaaij** [comment]
I've implemented a fix for the grid where it will now use sequential numbers as row and cell ids. It is part of the preview packages we publish.

**Comment by leslierichardson95** [comment]
We need to update to the latest Fluent UI version to resolve this issue.

**Comment by kvenkatrajan** [comment]
@adamint  please confirm if the package is upgraded and the fix works.

**Comment by adamint** [comment]
This appears not to reproduce anymore with the updated packages. @ThomasCronholm please tag me if you run into this again
