### ISSUE TITLE
Errors in stopping services when EndToEnd tests complete

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#2153]
This is on macOS:

1. start docker afresh
2. run the tests
3. make sure no dotnet run or any running containers left around
4. run the tests again, and it fails at the end with the following error
<details>
<summary>Error details</summary>

```
[apphost] dbug: Microsoft.Extensions.Hosting.Internal.Host[3]
[apphost]       Hosting stopping
[apphost] dbug: Microsoft.Extensions.Hosting.Internal.Host[3]
[apphost]       Hosting stopping
[apphost] info: Aspire.Hosting.Dcp.ApplicationExecutor[0]
[apphost]       Could not stop project 'servicea'.
[apphost]       k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'Conflict', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on executablereplicasets.usvc-dev.developer.microsoft.com \"servicea\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"servicea","group":"usvc-dev.developer.microsoft.com","kind":"executablereplicasets"},"code":409}
[apphost]       
[apphost]          at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
[apphost]          at k8s.AbstractKubernetes.ICustomObjectsOperations_DeleteClusterCustomObjectWithHttpMessagesAsync[T](String group, String version, String plural, String name, V1DeleteOptions body, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, String dryRun, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
[apphost]          at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.DeleteClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, String name, V1DeleteOptions body, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, String dryRun, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
[apphost]          at Aspire.Hosting.Dcp.KubernetesService.<>c__DisplayClass12_0`1.<<DeleteAsync>b__0>d.MoveNext() in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 112
[apphost]       --- End of stack trace from previous location ---
[apphost]          at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 201
[apphost]          at Aspire.Hosting.Dcp.ApplicationExecutor.DeleteResourcesAsync[RT](String resourceType, CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 899
[apphost] dbug: Microsoft.Extensions.Hosting.Internal.Host[4]
[apphost]       Hosting stopped
[apphost] info: Aspire.Hosting.Dcp.ApplicationExecutor[0]
[apphost]       Could not stop project 'serviceb'.
[apphost]       k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'NotFound', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"executablereplicasets.usvc-dev.developer.microsoft.com \"serviceb\" not found","reason":"NotFound","details":{"name":"serviceb","group":"usvc-dev.developer.microsoft.com","kind":"executablereplicasets"},"code":404}
[apphost]       
[apphost]          at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
[apphost]          at k8s.AbstractKubernetes.ICustomObjectsOperations_DeleteClusterCustomObjectWithHttpMessagesAsync[T](String group, String version, String plural, String name, V1DeleteOptions body, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, String dryRun, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
[apphost]          at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.DeleteClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, String name, V1DeleteOptions body, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, String dryRun, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
[apphost]          at Aspire.Hosting.Dcp.KubernetesService.<>c__DisplayClass12_0`1.<<DeleteAsync>b__0>d.MoveNext() in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 112
[apphost]       --- End of stack trace from previous location ---
[apphost]          at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 201
[apphost]          at Aspire.Hosting.Dcp.ApplicationExecutor.DeleteResourcesAsync[RT](String resourceType, CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 899
[apphost] dbug: Microsoft.Extensions.Hosting.Internal.Host[5]
[apphost]       Hosting shutdown exception
[apphost]       System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
[apphost]          at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
[apphost]          at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
[apphost]          at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
[apphost]          at Aspire.Hosting.Dcp.ApplicationExecutor.DeleteResourcesAsync[RT](String resourceType, CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 895
[apphost]          at Aspire.Hosting.Dcp.ApplicationExecutor.StopApplicationAsync(CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 263
[apphost]          at Aspire.Hosting.Dcp.DcpHostService.StopAsync(CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 77
[apphost]          at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[apphost] Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
[apphost]    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
[apphost]    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
[apphost]    at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
[apphost]    at Aspire.Hosting.Dcp.ApplicationExecutor.DeleteResourcesAsync[RT](String resourceType, CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 895
[apphost]    at Aspire.Hosting.Dcp.ApplicationExecutor.StopApplicationAsync(CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 263
[apphost]    at Aspire.Hosting.Dcp.DcpHostService.StopAsync(CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 77
[apphost]    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[apphost]    at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
[apphost]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
[apphost]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[apphost]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[apphost]    at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/DistributedApplication.cs:line 128
[apphost]    at TestProgram.RunAsync(CancellationToken cancellationToken) in /Users/ankj/dev/a2/tests/testproject/TestProject.AppHost/TestProgram.cs:line 99
[apphost]    at Program.<Main>$(String[] args) in /Users/ankj/dev/a2/tests/testproject/TestProject.AppHost/Program.cs:line 20
[apphost]    at Program.<Main>(String[] args)
Results File: /Users/ankj/dev/a2/tests/Aspire.EndToEnd.Tests/TestResults/_infinity_2024-02-08_17_23_29.trx
```
</details>

I see two things here:
```
[apphost]       Could not stop project 'servicea'.
[apphost]       k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'Conflict', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on executablereplicasets.usvc-dev.developer.microsoft.com \"servicea\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"servicea","group":"usvc-dev.developer.microsoft.com","kind":"executablereplicasets"},"code":409}
```

This seems to be the core issue, and happens for `serviceb` also.

But then we get:

```
[apphost]       Hosting shutdown exception
[apphost]       System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
[apphost]          at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
[apphost]          at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
[apphost]          at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
[apphost]          at Aspire.Hosting.Dcp.ApplicationExecutor.DeleteResourcesAsync[RT](String resourceType, CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 895
[apphost]          at Aspire.Hosting.Dcp.ApplicationExecutor.StopApplicationAsync(CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 263
[apphost]          at Aspire.Hosting.Dcp.DcpHostService.StopAsync(CancellationToken cancellationToken) in /Users/ankj/dev/a2/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 77
[apphost]          at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

.. which looks like a different issue, but hit due to the first one.

cc @karolz-ms @joperezr @eerhardt

**Comment by eerhardt** [comment]
I get errors during shutdown on this project on my Windows as well. Something must be wrong with it.

```
eerhardt@EERHARDT5  C:\git\aspire\tests\testproject\TestProject.AppHost   8.0.200-preview.24060.48   UpdateRabbitMQ ~1               [12:51:02]
❯ dotnet run
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: C:\git\aspire\tests\testproject\TestProject.AppHost
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: http://localhost:18888
$ENDPOINTS: {"servicea":{"Endpoints":[{"Name":"http","Uri":"http://localhost:5156"}]},"serviceb":{"Endpoints":[{"Name":"http","Uri":"http://localhost:5254"}]},"servicec":{"Endpoints":[{"Name":"http","Uri":"http://localhost:5271"}]},"workera":{"Endpoints":[]},"integrationservicea":{"Endpoints":[{"Name":"http","Uri":"http://localhost:5281"}]}}
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press CTRL-C to stop.
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReplicaSetReconciler[0]
      failed to delete inactive child Executable object {"ExecutableReplicaSet": {"name":"servicea"}, "Reconciliation": 39, "DesiredReplicas": 1, "exe": {"kind":"Executable","apiVersion":"usvc-dev.developer.microsoft.com/v1","metadata":{"name":"servicea-6ov1o8o","uid":"087e83b2-ea76-4ea2-a7f1-2c8944dedd3b","resourceVersion":"163","creationTimestamp":"2024-02-09T18:51:27Z","deletionTimestamp":"2024-02-09T18:51:52Z","deletionGracePeriodSeconds":0,"annotations":{"csharp-project-path":"C:\\git\\aspire\\tests\\testproject\\TestProject.ServiceA\\TestProject.ServiceA.csproj","executable-replica-set.usvc-dev.developer.microsoft.com/display-name":"servicea-1","executable-replica-set.usvc-dev.developer.microsoft.com/replica-state":"active","otel-service-name":"servicea","resource-name":"servicea","service-producer":"[{\"serviceName\":\"servicea\",\"address\":null,\"port\":null}]"},"ownerReferences":[{"apiVersion":"usvc-dev.developer.microsoft.com/v1","kind":"ExecutableReplicaSet","name":"servicea","uid":"460f3802-9dc8-4c15-b91c-def961f161ba","controller":true,"blockOwnerDeletion":true}],"finalizers":["usvc-dev.developer.microsoft.com/executable-reconciler"],"managedFields":[{"manager":"dcpctrl.exe","operation":"Update","apiVersion":"usvc-dev.developer.microsoft.com/v1","time":"2024-02-09T18:51:27Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:csharp-project-path":{},"f:executable-replica-set.usvc-dev.developer.microsoft.com/display-name":{},"f:executable-replica-set.usvc-dev.developer.microsoft.com/replica-state":{},"f:otel-service-name":{},"f:resource-name":{},"f:service-producer":{}},"f:finalizers":{".":{},"v:\"usvc-dev.developer.microsoft.com/executable-reconciler\"":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"460f3802-9dc8-4c15-b91c-def961f161ba\"}":{}}},"f:spec":{"f:args":{},"f:env":{},"f:executablePath":{},"f:executionType":{},"f:workingDirectory":{}}}}]},"spec":{"executablePath":"dotnet","workingDirectory":"C:\\git\\aspire\\tests\\testproject\\TestProject.ServiceA","args":["run","--no-build","--project","C:\\git\\aspire\\tests\\testproject\\TestProject.ServiceA\\TestProject.ServiceA.csproj","--no-launch-profile"],"env":[{"name":"DOTNET_LAUNCH_PROFILE","value":"http"},{"name":"ASPNETCORE_URLS","value":"http://localhost:{{- portForServing \"servicea\" -}}"},{"name":"ASPNETCORE_ENVIRONMENT","value":"Development"},{"name":"OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES","value":"true"},{"name":"OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES","value":"true"},{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","value":"http://localhost:18889"},{"name":"OTEL_RESOURCE_ATTRIBUTES","value":"service.instance.id={{- .UID -}}"},{"name":"OTEL_SERVICE_NAME","value":"{{- index .Annotations \"otel-service-name\" -}}"},{"name":"DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION","value":"true"},{"name":"LOGGING__CONSOLE__FORMATTERNAME","value":"simple"},{"name":"LOGGING__CONSOLE__FORMATTEROPTIONS__TIMESTAMPFORMAT","value":"yyyy-MM-ddTHH:mm:ss.fffffff "}],"executionType":"Process"},"status":{"executionID":"99904","pid":99904,"state":"Running","startupTimestamp":"2024-02-09T18:51:27Z","finishTimestamp":null,"stdOutFile":"C:\\Users\\eerhardt\\AppData\\Local\\Temp\\aspire.jer23p1s.05a\\servicea-6ov1o8o_out_087e83b2-ea76-4ea2-a7f1-2c8944dedd3b","stdErrFile":"C:\\Users\\eerhardt\\AppData\\Local\\Temp\\aspire.jer23p1s.05a\\servicea-6ov1o8o_err_087e83b2-ea76-4ea2-a7f1-2c8944dedd3b","effectiveEnv":[{"name":"VSDebugger_ValidateDotnetDebugLibSignatures","value":"0"},{"name":"PROCESSOR_LEVEL","value":"6"},{"name":"USERPROFILE","value":"C:\\Users\\eerhardt"},{"name":"Path","value":"C:\\Program Files\\PowerShell\\7;C:\\Program Files\\Microsoft\\jdk-11.0.21.9-hotspot\\bin;C:\\Program Files\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;c:\\Program Files (x86)\\HP\\HP Performance Advisor;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\nodejs\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\Go\\bin;C:\\Program Files\\CMake\\bin;C:\\Program Files\\GitHub CLI\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PowerShell\\7\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\Users\\eerhardt\\AppData\\Local\\Programs\\Python\\Launcher\\;C:\\Users\\eerhardt\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\eerhardt\\AppData\\Local\\Programs\\Python\\Python39\\;C:\\Users\\eerhardt\\.cargo\\bin;C:\\Users\\eerhardt\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\eerhardt\\.dotnet\\tools;C:\\git\\sdk\\artifacts\\tmp\\Release\\.dotnet\\tools;C:\\git\\sdk\\artifacts\\tmp\\Debug\\.dotnet\\tools;C:\\Program Files\\Ninja;C:\\Users\\eerhardt\\AppData\\Local\\Programs\\Python\\Python39;C:\\Users\\eerhardt\\AppData\\Local\\Microsoft\\WindowsApps;C:\\git\\sdk\\artifacts\\tmp\\Debug\\GivenWorkload---126200D6\\.dotnet\\tools;C:\\git\\sdk\\artifacts\\tmp\\Debug\\GivenASpecifi---19E2CF8C\\.dotnet\\tools;C:\\git\\sdk\\artifacts\\tmp\\Debug\\GivenWorkload---8C208320\\.dotnet\\tools;C:\\Users\\eerhardt\\AppData\\Local\\Programs\\Fiddler;C:\\Users\\eerhardt\\AppData\\Roaming\\npm;C:\\Users\\eerhardt\\go\\bin;C:\\Users\\eerhardt\\AppData\\Local\\Microsoft\\WinGet\\Links;C:\\Users\\eerhardt\\AppData\\Local\\Programs\\oh-my-posh\\bin;C:\\git\\sdk2\\artifacts\\tmp\\Debug\\.dotnet\\tools;C:\\Users\\eerhardt\\AppData\\Local\\Programs\\Azure Dev CLI\\;C:\\Program Files\\Markdown Monster"},{"name":"OneDrive","value":"C:\\Users\\eerhardt\\OneDrive - Microsoft"},{"name":"COMPUTERNAME","value":"EERHARDT5"},{"name":"HOMEDRIVE","value":"C:"},{"name":"WSLENV","value":"WT_SESSION:WT_PROFILE_ID:"},{"name":"MSBuildLoadMicrosoftTargetsReadOnly","value":"true"},{"name":"NUMBER_OF_PROCESSORS","value":"12"},{"name":"HOMEPATH","value":"\\Users\\eerhardt"},{"name":"DCP_LOG_SOCKET","value":"C:\\Users\\eerhardt\\AppData\\Local\\Temp\\aspire.jer23p1s.05a\\output.sock"},{"name":"RegionCode","value":"NA"},{"name":"WT_SESSION","value":"3b151557-aa5a-404d-baa4-4cb1501f8859"},{"name":"PSModulePath","value":"C:\\Users\\eerhardt\\Documents\\PowerShell\\Modules;C:\\Program Files\\PowerShell\\Modules;c:\\program files\\powershell\\7\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft Azure Information Protection\\Powershell"},{"name":"WT_PROFILE_ID","value":"{574e775e-4f2a-5b96-ac1e-a2962a402336}"},{"name":"ProgramData","value":"C:\\ProgramData"},{"name":"OTEL_SERVICE_NAME","value":"servicea"},{"name":"DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION","value":"true"},{"name":"USERDNSDOMAIN","value":"northamerica.corp.microsoft.com"},{"name":"CommonProgramFiles(x86)","value":"C:\\Program Files (x86)\\Common Files"},{"name":"OneDriveCommercial","value":"C:\\Users\\eerhardt\\OneDrive - Microsoft"},{"name":"TEMP","value":"C:\\Users\\eerhardt\\AppData\\Local\\Temp"},{"name":"SESSIONNAME","value":"Console"},{"name":"ASPNETCORE_URLS","value":"http://localhost:52299"},{"name":"windir","value":"C:\\WINDOWS"},{"name":"PATHEXT","value":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL"},{"name":"ComSpec","value":"C:\\WINDOWS\\system32\\cmd.exe"},{"name":"POSH_THEMES_PATH","value":"C:\\Users\\eerhardt\\AppData\\Local\\Programs\\oh-my-posh\\themes"},{"name":"DOTNET_ROOT_X64","value":"C:\\Program Files\\dotnet"},{"name":"DOTNET_MULTILEVEL_LOOKUP","value":"0"},{"name":"PUBLIC","value":"C:\\Users\\Public"},{"name":"platformcode","value":"5X"},{"name":"GOPATH","value":"C:\\Users\\eerhardt\\go"},{"name":"PROCESSOR_REVISION","value":"9e0a"},{"name":"CommonProgramW6432","value":"C:\\Program Files\\Common Files"},{"name":"POSH_CURSOR_COLUMN","value":"1"},{"name":"POSH_SHELL_VERSION","value":"7.3.11"},{"name":"POSH_AZURE_ENABLED","value":"False"},{"name":"OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES","value":"true"},{"name":"OTEL_RESOURCE_ATTRIBUTES","value":"service.instance.id=087e83b2-ea76-4ea2-a7f1-2c8944dedd3b"},{"name":"LOGGING__CONSOLE__FORMATTERNAME","value":"simple"},{"name":"POSH_PID","value":"40188"},{"name":"POSH_GIT_ENABLED","value":"False"},{"name":"DOTNET_LAUNCH_PROFILE","value":"http"},{"name":"USERNAME","value":"eerhardt"},{"name":"USERDOMAIN_ROAMINGPROFILE","value":"NORTHAMERICA"},{"name":"LOCALAPPDATA","value":"C:\\Users\\eerhardt\\AppData\\Local"},{"name":"SystemRoot","value":"C:\\WINDOWS"},{"name":"ProgramW6432","value":"C:\\Program Files"},{"name":"SystemDrive","value":"C:"},{"name":"DCP_SESSION_FOLDER","value":"C:\\Users\\eerhardt\\AppData\\Local\\Temp\\aspire.jer23p1s.05a"},{"name":"POSH_CURSOR_LINE","value":"35"},{"name":"POWERSHELL_DISTRIBUTION_CHANNEL","value":"MSI:Windows 10 Pro"},{"name":"ProgramFiles(x86)","value":"C:\\Program Files (x86)"},{"name":"TMP","value":"C:\\Users\\eerhardt\\AppData\\Local\\Temp"},{"name":"UATDATA","value":"C:\\windows\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77"},{"name":"USERDOMAIN","value":"NORTHAMERICA"},{"name":"ALLUSERSPROFILE","value":"C:\\ProgramData"},{"name":"ProgramFiles","value":"C:\\Program Files"},{"name":"PROCESSOR_IDENTIFIER","value":"Intel64 Family 6 Model 158 Stepping 10, GenuineIntel"},{"name":"CommonProgramFiles","value":"C:\\Program Files\\Common Files"},{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","value":"http://localhost:18889"},{"name":"JAVA_HOME","value":"C:\\Program Files\\Microsoft\\jdk-11.0.21.9-hotspot\\"},{"name":"NugetMachineInstallRoot","value":"C:\\CxCache"},{"name":"OnlineServices","value":"Online Services"},{"name":"POSH_INSTALLER","value":"winget"},{"name":"POSH_THEME","value":"C:\\Users\\eerhardt\\.oh-my-posh\\ohmyposhv3-2.json"},{"name":"DriverData","value":"C:\\Windows\\System32\\Drivers\\DriverData"},{"name":"PROCESSOR_ARCHITECTURE","value":"AMD64"},{"name":"LOGONSERVER","value":"\\\\EERHARDT5"},{"name":"LOGGING__CONSOLE__FORMATTEROPTIONS__TIMESTAMPFORMAT","value":"yyyy-MM-ddTHH:mm:ss.fffffff "},{"name":"OS","value":"Windows_NT"},{"name":"DCP_BIN_PATH","value":"C:\\Users\\eerhardt\\.nuget\\packages\\microsoft.developercontrolplane.windows-amd64\\0.1.50\\tools\\ext\\bin\\"},{"name":"CONDA_PROMPT_MODIFIER","value":"False"},{"name":"POWERLINE_COMMAND","value":"oh-my-posh"},{"name":"APPDATA","value":"C:\\Users\\eerhardt\\AppData\\Roaming"},{"name":"ASPNETCORE_ENVIRONMENT","value":"Development"},{"name":"OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES","value":"true"}],"effectiveArgs":["run","--no-build","--project","C:\\git\\aspire\\tests\\testproject\\TestProject.ServiceA\\TestProject.ServiceA.csproj","--no-launch-profile"]}}, "error": "executables.usvc-dev.developer.microsoft.com \"servicea-6ov1o8o\" not found"}
```

Just `dotnet run` it, wait for a while. Then `CTRL+C` and see the error.

**Comment by mitchdenny** [comment]
Is this still occurring @radical ? There have been plenty of changes getting to preview 5.

**Comment by radical** [comment]
No, I haven't seen this occur recently. Closing.
