### ISSUE TITLE
.NET Aspire 8.0.0-preview.3.24105.21 Dashboard fails to be found

### ISSUE THREAD

**Issue by cisionmarkwalls** [dotnet/aspire#2218]
Upgrading from 8.0.0-preview.2.23619.3 to 8.0.0-preview.3.24105.21 leads to a loss of the dashboard.
* It seems to be looking for a reference for it so I attempted to add the Aspire.Dashboard nuget (8.0.0-preview.3.24073.5 from .net8 channel), but that didn't affect it.
* I attempted moving Aspire.Hosting to 8.0.0-preview.4.24113.5, but that didn't work either.
This is using Visual Studio Version 17.9.0 Preview 5.0.

```
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: C:\Users\Mark.Walls\source\repos\AspireApp2\AspireApp2.AppHost
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: Dashboard path empty or file does not exist.
         at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 168
         at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 92
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

The code I'm running to get the above error is:

```
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache");
var kafka = builder.AddKafka("Kafka");

var apiservice = builder.AddProject<Projects.AspireApp2_ApiService>("apiservice");

builder.AddProject<Projects.AspireApp2_Web>("webfrontend")
    .WithReference(cache)
    .WithReference(kafka)
    .WithReference(apiservice);

builder.Build().Run();
```
And my csproj is:
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAspireHost>true</IsAspireHost>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AspireApp2.ApiService\AspireApp2.ApiService.csproj" IsAspireProjectResource="true" />
		<ProjectReference Include="..\AspireApp2.Web\AspireApp2.Web.csproj" IsAspireProjectResource="true" />
	</ItemGroup>

	<ItemGroup>
		    <PackageReference Include="Aspire.Dashboard" Version="8.0.0-preview.3.24073.5" />
    	<PackageReference Include="Aspire.Hosting" Version="8.0.0-preview.4.24113.5" />
  </ItemGroup>

</Project>
```

**Comment by DamianEdwards** [comment]
Did you update the aspire workload? The dashboard is delivered with the workload now in preview.3

```
dotnet workload update
dotnet workload install aspire
```

**Comment by cisionmarkwalls** [comment]
Something I noticed during the install was this unsigned manifest. Not really related to this, but someone should probably peek at it.
![image](https://github.com/dotnet/aspire/assets/106612666/c9f3389d-8748-4c62-8f35-71a38f4b8ffd)

The above steps however didn't change the error. After doing the above commands I:
* Created a new Aspire Starter solution
* Ran it to make sure it worked with the out of the box 8.0.0-preview.1.23557.2 Aspire.Hosting
```
info: Aspire.Dashboard.DashboardWebApplication[0]
      Now listening on: http://localhost:15171
info: Aspire.Dashboard.DashboardWebApplication[0]
      OTLP server running at: http://localhost:16049
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Mark.Walls\source\repos\AspireApp3\AspireApp3.AppHost
```
* Updated the Aspire.Hosting nuget from 8.0.0-preview.1.23557.2 to 8.0.0-preview.3.24105.21, and added the IsAspireProjectResource="true" to the project resources to handle the build errors and got
```
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: C:\Users\Mark.Walls\source\repos\AspireApp3\AspireApp3.AppHost
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: Dashboard path empty or file does not exist.
         at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 168
         at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 92
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

**Comment by cisionmarkwalls** [comment]
I found the issue. When I upgraded to Version 17.10.0 Preview 1.0 of Visual studio it started working. The  17.9.0 Preview 5.0 version of Visual studio doesn't work with the new dashboard.
