### ISSUE TITLE
Running the Dashboard Docker Image

### ISSUE THREAD

**Issue by christophwille** [dotnet/aspire#2248]
```
docker pull mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.3 
docker run --rm -it -p 18888:18888 -p 4317:18889  mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.3
```

When going to http://localhost:18888/, I get the following (fail) output from the console:

```
info: Aspire.Dashboard[0]
      Now listening on: http://0.0.0.0:18888
info: Aspire.Dashboard[0]
      OTLP server running at: http://0.0.0.0:18889
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/home/app/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {26c8391a-bd95-4284-8b92-420a58964eee} may be persisted to storage in unencrypted form.
info: Aspire.Dashboard.Model.DashboardClient[0]
      DOTNET_RESOURCE_SERVICE_ENDPOINT_URL is not specified. Dashboard client services are unavailable.
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: DashboardClient is disabled. Check the IsEnabled property before calling this.
      System.InvalidOperationException: DashboardClient is disabled. Check the IsEnabled property before calling this.
         at Aspire.Dashboard.Model.DashboardClient.EnsureInitialized() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 135
         at Aspire.Dashboard.Model.DashboardClient.Aspire.Dashboard.Model.IDashboardClient.get_WhenConnected() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 301
         at Aspire.Dashboard.Components.ApplicationName.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/ApplicationName.razor.cs:line 29
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'p7hax2t1XD7heIt-rX0VpvaxEmoNfU1vV8SGg8kDIC4'.
      System.InvalidOperationException: DashboardClient is disabled. Check the IsEnabled property before calling this.
         at Aspire.Dashboard.Model.DashboardClient.EnsureInitialized() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 135
         at Aspire.Dashboard.Model.DashboardClient.Aspire.Dashboard.Model.IDashboardClient.get_WhenConnected() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 301
         at Aspire.Dashboard.Components.ApplicationName.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/ApplicationName.razor.cs:line 29
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot access a disposed object.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'p7hax2t1XD7heIt-rX0VpvaxEmoNfU1vV8SGg8kDIC4'.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

What am I missing? Should I be using a newer tag https://[mcr.microsoft.com/v2/dotnet/nightly/aspire-dashboard/tags/list](https://mcr.microsoft.com/v2/dotnet/nightly/aspire-dashboard/tags/list)? Current tags as of writing this issue:

```
{
    "name": "dotnet/nightly/aspire-dashboard",
    "tags": [
        "8.0-preview",
        "8.0-preview-amd64",
        "8.0-preview-arm64v8",
        "8.0-preview-cbl-mariner-distroless",
        "8.0-preview-cbl-mariner-distroless-amd64",
        "8.0-preview-cbl-mariner-distroless-arm64v8",
        "8.0.0-preview.3",
        "8.0.0-preview.3-amd64",
        "8.0.0-preview.3-arm64v8",
        "8.0.0-preview.3-cbl-mariner-distroless",
        "8.0.0-preview.3-cbl-mariner-distroless-amd64",
        "8.0.0-preview.3-cbl-mariner-distroless-arm64v8",
        "8.0.0-preview.4",
        "8.0.0-preview.4-amd64",
        "8.0.0-preview.4-arm64v8",
        "latest"
    ]
}
```

**Comment by madhub** [comment]
same here

**Comment by davidfowl** [comment]
There are bugs in the current dashboard image when run without a resource server. The image hasn't been updated since the original push. When we get another update it should be runnable as a standalone otlp server.

cc @joperezr

**Comment by joperezr** [comment]
I have a PR out to update it to a build from today: https://github.com/dotnet/dotnet-docker/pull/5203

**Comment by radical** [comment]
> I have a PR out to update it to a build from today: [dotnet/dotnet-docker#5203](https://github.com/dotnet/dotnet-docker/pull/5203)

Are these updates going to be automated?

**Comment by lbussell** [comment]
> Are these updates going to be automated?

https://github.com/dotnet/dotnet-docker/issues/5154

**Comment by christophwille** [comment]
I can confirm that

```
docker pull mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.4
docker run --rm -it -p 18888:18888 -p 4317:18889  mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.4
```

Now works for logs & traces from a standard OTLP-exporting ASP.NET 8.0 application

![image](https://github.com/dotnet/aspire/assets/344208/03ff8e86-ae24-4f40-8c1a-976af55ffd65)

**Comment by davidfowl** [comment]
Excellent @christophwille !

**Comment by drewnoakes** [comment]
If you don't want to wait and just need a binary, you could build it yourself from this repo to test it out.

**Comment by davidfowl** [comment]
@KalleOlaviNiemitalo use the preview 4 version
