### ISSUE TITLE
[tests][CI] `Aspire.Hosting` tests failing with `The configured user limit (128) on the number of inotify instances ...`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#2369]
This was hit on [vNext](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576133&view=results), and [main](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575318&view=results) on PRs. I see this error only on PRs, and not on rolling builds though.

```
System.IO.IOException : The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.,

at System.IO.FileSystemWatcher.StartRaisingEvents()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ApplyDefaultAppConfiguration(HostBuilderContext hostingContext, IConfigurationBuilder appConfigBuilder, String[] args)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder..ctor(HostApplicationBuilderSettings settings)
   at Aspire.Hosting.DistributedApplicationBuilder..ctor(DistributedApplicationOptions options) in /_/src/Aspire.Hosting/DistributedApplicationBuilder.cs:line 49
   at Aspire.Hosting.DistributedApplication.CreateBuilder(DistributedApplicationOptions options) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 90
   at TestProgram..ctor(String[] args, Assembly assembly, Boolean includeIntegrationServices, Boolean includeNodeApp, Boolean disableDashboard) in /_/tests/testproject/TestProject.AppHost/TestProgram.cs:line 18
   at TestProgram.Create[T](String[] args, Boolean includeIntegrationServices, Boolean includeNodeApp, Boolean disableDashboard) in /_/tests/testproject/TestProject.AppHost/TestProgram.cs:line 82
   at Aspire.Hosting.Tests.ManifestGenerationTests.CreateTestProgramJsonDocumentManifestPublisher(Boolean includeNodeApp) in /_/tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs:line 542
   at Aspire.Hosting.Tests.ManifestGenerationTests.PublishingRedisResourceAsContainerResultsInConnectionStringProperty() in /_/tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs:line 283
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr),
```

The earliest failure was on a [PR](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574870&view=results) with [commits](https://github.com/dotnet/aspire/commits/ec9c5070baa0c5fcbb675a8322585e7dbd8e7f4c/). The last one from main is https://github.com/dotnet/aspire/pull/2342 -`microsoft/usvc-apiserver` update.

cc @joperezr

**Comment by eerhardt** [comment]
I believe this was fixed with https://github.com/dotnet/aspire/pull/2364. If this error happens again, please reopen.

**Comment by radical** [comment]
This is being hit on `main` also - https://dev.azure.com/dnceng-public/public/_build/results?buildId=610768&view=results

**Comment by joperezr** [comment]
Seems like this hasn't been an issue in a while from a search through build logs, so closing this as resolved. Please re-open if we see it again.
