### ISSUE TITLE
Azure Provisioner / Bicep returning invalid service bus namespace causing Bicep sample to explode.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#2412]
Probably impacts AZD deployment also. Needs to be fixed for P4 I think.

```
System.ArgumentException: The value 'sb-lsjxqndzuq6pa.servicebus.windows.net:443/' is not a well-formed Service Bus fully qualified namespace. (Parameter 'fullyQualifiedNamespace')
   at Azure.Core.Argument.AssertWellFormedServiceBusNamespace(String argumentValue, String argumentName)
   at Azure.Messaging.ServiceBus.ServiceBusConnection..ctor(String fullyQualifiedNamespace, TokenCredential credential, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusConnection.CreateWithCredential[TCredential](String fullyQualifiedNamespace, TCredential credential, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String fullyQualifiedNamespace, Object credential, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String fullyQualifiedNamespace, TokenCredential credential, ServiceBusClientOptions options)
   at Microsoft.Extensions.Hosting.AspireServiceBusExtensions.MessageBusComponent.<>c__DisplayClass0_0`1.<AddClient>b__0(ServiceBusClientOptions options, TokenCredential cred) in C:\Code\aspire\src\Components\Aspire.Azure.Messaging.ServiceBus\AspireServiceBusExtensions.cs:line 77
   at Microsoft.Extensions.Azure.AzureClientFactoryBuilder.<>c__DisplayClass8_0`2.<Azure.Core.Extensions.IAzureClientFactoryBuilderWithCredential.RegisterClientFactory>b__0(TOptions options, TokenCredential credential, IServiceProvider _)
   at Microsoft.Extensions.Azure.AzureClientFactoryBuilder.<>c__DisplayClass15_0`2.<RegisterClientFactory>b__0(IServiceProvider provider, Object options, TokenCredential credential)
   at Microsoft.Extensions.Azure.ClientRegistration`1.GetClient(IServiceProvider serviceProvider, Object options, TokenCredential tokenCredential)
   at Microsoft.Extensions.Azure.AzureClientFactory`2.CreateClient(String name)
   at Microsoft.Extensions.Azure.AzureClientFactoryBuilder.<>c__15`2.<RegisterClientFactory>b__15_1(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at lambda_method16(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by mitchdenny** [comment]
Closing as fixed in: https://github.com/dotnet/aspire/pull/2385
