### ISSUE TITLE
Dashboard shortcuts cause a large number of error logs

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2459]
```
2024-02-27T11:27:43.0946576 fail: Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager[4]
      Navigation failed when changing the location to /ConsoleLogs
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext()
```

**Comment by JamesNK** [comment]
This happens when you open Aspire dashboard links in new browser windows, then close them, then navigate page.

**Comment by tlmii** [comment]
Testing this a little bit I suspect the root cause is the same as #2467. The static has references to all the pages (and is perhaps keeping them alive too long?) and so it tries to navigate on the closed pages.
