### ISSUE TITLE
Flaky test: Aspire.Dashboard.Tests.Integration.OtlpServiceTests.CallService_BrowserEndPoint_Failure

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2536]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=583920&view=ms.vss-test-web.build-test-results-tab&runId=14047054&resultId=100063&paneView=debug

Assert.Equal() Failure
Expected: PermissionDenied
Actual:   Unavailable

```
Stack trace
   at Aspire.Dashboard.Tests.Integration.OtlpServiceTests.CallService_BrowserEndPoint_Failure() in /_/tests/Aspire.Dashboard.Tests/Integration/OtlpServiceTests.cs:line 66
   at Aspire.Dashboard.Tests.Integration.OtlpServiceTests.CallService_BrowserEndPoint_Failure() in /_/tests/Aspire.Dashboard.Tests/Integration/OtlpServiceTests.cs:line 68
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

cc @JamesNK

**Comment by JamesNK** [comment]
This is the error:

```
| [2024-03-03T06:15:18] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN1R956B60LU" accepted.
| [2024-03-03T06:15:18] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN1R956B60LU" started.
| [2024-03-03T06:15:19] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Failed to authenticate HTTPS connection.
| System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
|  ---> System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized
|    at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
|    at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
|    at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslAuthenticationOptions authOptions)
|    at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions, Boolean newCredentialsRequested)
|    --- End of inner exception stack trace ---
|    at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions, Boolean newCredentialsRequested)
|    at System.Net.Security.SslStream.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions, Boolean newCredentialsRequested)
|    at System.Net.Security.SslStream.AcquireServerCredentials(Byte[]& thumbPrint)
|    at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
|    at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer, ProtocolToken& token)
|    at System.Net.Security.SslStream.ProcessTlsFrame(Int32 frameSize, ProtocolToken& message)
|    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
|    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
| [2024-03-03T06:15:19] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN1R956B60LU" stopped.
| [2024-03-03T06:15:19] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HN1R956B60LU" sending FIN because: "The Socket transport's send loop completed gracefully."
```

Sometimes the configured certificate is failing.
