### ISSUE TITLE
Weird behaviour on starting up Aspire app

### ISSUE THREAD

**Issue by adamtrip** [dotnet/aspire#2539]
Sometimes on starting an Aspire app via VS 2022, it immediately launches the browser saying "No resources found" and throws an error.

![image](https://github.com/dotnet/aspire/assets/59871955/52508bd5-2052-49fc-b1b2-7237803f5410)

```
Error: Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.")
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
   --- End of inner exception stack trace ---
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.<SendAsync>g__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at Grpc.Net.Client.Internal.Retry.RetryCallBase`2.GetResponseCoreAsync()
   at Aspire.Dashboard.Model.DashboardClient.<>c__DisplayClass23_0.<<EnsureInitialized>g__ConnectAsync|2>d.MoveNext() in /_/src/Aspire.Dashboard/Model/DashboardClient.cs:line 158
--- End of stack trace from previous location ---
   at Aspire.Dashboard.Components.ApplicationName.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/ApplicationName.razor.cs:line 32
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Sometimes it fixes itself, with a VS restart, and other times I have to reboot my PC to make it work again.
This did happen on preview versions 3, 4 and 5 so no specific version bound to this (I think)

**Comment by davidfowl** [comment]
The dashboard can't connect to the resource server (the app host) for some reason. Is it consistent? I'm going to close this and link the issue [here](https://github.com/dotnet/aspire/issues/2422)

**Comment by adamtrip** [comment]
> Is it consistent?

Yes, happens every hour or two.


> 1. When it happens were you launching in VS or outside?

In VS


> 2. Did you use F5 or CTRL+F5 if in VS?

Just F5


> 3\. The next time it happens, can you look at the environment variables on both the dashboard process and the app host?

How can I do that?

**Comment by davidfowl** [comment]
> Yes, happens every hour or two.

This is good news, we might be able to pin it down.

> How can I do that?

https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer

I'm guessing that something gets into a bad state wrt the ports chosen causing some errors. 

Can you also turn the logging verbosity up on the AppHost project once it starts happening? (in appsettings.json)

**Comment by adamtrip** [comment]
As soon as I encounter that issue again, I'll debug it with that tool.



> I'm guessing that something gets into a bad state wrt the ports chosen causing some errors.

I believe that that might be the case because changing the localhost port on launchsettings doesn't work, the dashboard does not launch, at least on preview 3, on preview 5 haven't tested

**Comment by adamtrip** [comment]
> I believe that that might be the case because changing the localhost port on launchsettings doesn't work, the dashboard does not launch, at least on preview 3, on preview 5 haven't tested

Adding `ASPNETCORE_URLS` env var fixes the dashboard port change not loading. I was only changing the `applicationUrl` env var.



> As soon as I encounter that issue again, I'll debug it with that tool.

Today didn't happen yet, still waiting for it to debug it and provide extra info.

**Comment by joaojvf** [comment]
@adamtrip can you give more explanation about how to fix it? Don't update any port of my application, but I've the same error.

https://github.com/joaojvf/AspirePoc/blob/add-aspire/src/AspirePoc.UI.Api/appsettings.json

**Comment by adamtrip** [comment]
@joaojvf I've updated to `8.0.0-preview.5.24155.1` and I have not encountered this issue since

**Comment by joaojvf** [comment]
@adamtrip do you update the .NET Aspire for this version? Because the last one that I found is the 8.0.0-preview.3.24105.21.

**Comment by adamtrip** [comment]
@joaojvf you can use the daily builds: https://github.com/dotnet/aspire/blob/main/docs/using-latest-daily.md

**Comment by davidfowl** [comment]
The rule about using daily builds is that you are following the commits to understand the changes. We're in rapid fire mode to beware of breakage 😄

**Comment by joaojvf** [comment]
Thank you guys! I tried re-implement the Aspire in my project, and worked! I use this project to create a medium post for my company initiative. If you like to see the code and post are here:
post: https://medium.com/@jferreira.ti/implementing-net-aspire-preview-3-24-988235098554
code: https://github.com/joaojvf/AspirePoc

**Comment by davidfowl** [comment]
The dashboard is connecting to 55072 and it’s failing. Unfortunately I think we need to add logs to narrow this down. It’s possible the app hosts’ resource server failed to start or there’s some caching bug that we have reporting the wrong url

**Comment by adamtrip** [comment]
out of curiosity I did a net stat and with the app stopped I saw this

```
[Aspire.Dashboard.exe]
  TCP    127.0.0.1:16051        adam-pc:0              LISTENING
 [Aspire.Dashboard.exe]
  TCP    127.0.0.1:45654        adam-pc:0              LISTENING
```

**Comment by davidfowl** [comment]
Take a look at the TCP/IP section on the apphost process.

**Comment by adamtrip** [comment]
![image](https://github.com/dotnet/aspire/assets/59871955/578187d4-bfa8-4b46-9443-38b1221e6bc7)

**Comment by davidfowl** [comment]
The apphost should be listening as well.

**Comment by davidfowl** [comment]
Different port. that's the orchestrator not aspire.hosting (even though logs come through that console)
