### ISSUE TITLE
OpenAI client fails to parse a connection string in client

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#2652]
I have a connection string as ConnectionStrings__foobar=http://localhost:11434

When in my client (using aspire-starter) and adding `builder.AddAzureOpenAI("foobar");` it fails with

```
System.ArgumentException
  HResult=0x80070057
  Message=Format of the initialization string does not conform to specification starting at index 0.
  Source=System.Data.Common
  StackTrace:
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Aspire.Azure.AI.OpenAI.AzureOpenAISettings.Aspire.Azure.Common.IConnectionStringSettings.ParseConnectionString(String connectionString)
   at Aspire.Azure.Common.AzureComponent`3.AddClient(IHostApplicationBuilder builder, String configurationSectionName, Action`1 configureSettings, Action`1 configureClientBuilder, String connectionName, String serviceKey)
   at Microsoft.Extensions.Hosting.AspireAzureOpenAIExtensions.AddAzureOpenAI(IHostApplicationBuilder builder, String connectionName, Action`1 configureSettings, Action`1 configureClientBuilder)
   at Program.<Main>$(String[] args) in D:\source\repos\AspireApp66\AspireApp66.Web\Program.cs:line 8
```

**Comment by DamianEdwards** [comment]
@timheuer you mean `ConnectionStrings__` rather than `ConnectionString__` I assume?
