### ISSUE TITLE
Output Bicep is invalid when using resources with '-' (dash) character in their name

### ISSUE THREAD

**Issue by pedershk** [dotnet/aspire#2729]
When resources are defined with the dash character in their name, output bicep is invalid:

![image](https://github.com/dotnet/aspire/assets/667361/c236c848-1b6d-4440-a9e5-07e265195e02)

This results in azd provision failing because modules can not be loaded.

Unsure if the right approach here is to rewrite on manifest creation or enforce naming standards in resource naming (on build/run).

**Comment by pedershk** [comment]
Actually, the Application Model explicitly allows hyphens (I now tried renaming to using underscores). So this is definitely a bug in the manifest generation (which should rewrite those hyphens or remove them, I guess).

```
 stderr: Unhandled exception. System.ArgumentException: Resource name 'sql_docgen' is invalid. Name must contain only ASCII letters, digits, and hyphens. (Parameter 'name')
   at Aspire.Hosting.ApplicationModel.ModelName.ValidateName(String target, String name) in /_/src/Aspire.Hosting/ApplicationModel/ModelName.cs:line 39
   at Aspire.Hosting.ApplicationModel.Resource..ctor(String name) in /_/src/Aspire.Hosting/ApplicationModel/Resource.cs:line 30
   at Aspire.Hosting.ApplicationModel.ContainerResource..ctor(String name, String entrypoint) in /_/src/Aspire.Hosting/ApplicationModel/ContainerResource.cs:line 11
   at Aspire.Hosting.ApplicationModel.SqlServerServerResource..ctor(String name, String password) in /_/src/Aspire.Hosting/SqlServer/SqlServerServerResource.cs:line 13
   at Aspire.Hosting.SqlServerBuilderExtensions.AddSqlServer(IDistributedApplicationBuilder builder, String name, String password, Nullable`1 port) in /_/src/Aspire.Hosting/SqlServer/SqlServerBuilderExtensions.cs:line 28
```

**Comment by DamianEdwards** [comment]
This is a bug in azd as Aspire resource names support hyphens (including in the manifest). If bicep doesn't then azd will have to encode/sanitize the names.

**Comment by timheuer** [comment]
Hit this today as well...the module name rules are `a-z` `A-Z` `0-9` and `_` and can't start with numeric digit

Move to azd?

**Comment by DamianEdwards** [comment]
> Move to azd?

Yep I think so.

**Comment by timheuer** [comment]
@rajeshkamal5050  FYI

**Comment by rajeshkamal5050** [comment]
@vhvb1989 do we still generate bicep's for it? with the new `AzureBicepResource` isn't `Aspire.Hosting.Azure`'s resources are generating bicep in the Aspire layer itself?

cc @mitchdenny @davidfowl

**Comment by vhvb1989** [comment]
azd creates `main.bicep` from all the bicep resources generated by Aspire.  This is a bug in azd prev4 :)

**Comment by vhvb1989** [comment]
Fix merged for next azd release supporting Aspire preview4: https://github.com/Azure/azure-dev/pull/3516

**Comment by vhvb1989** [comment]
@DamianEdwards , in case you want to close this issue.  You can try the fix using daily build
