### ISSUE TITLE
Name must contain only ASCII letters, digits, and hyphens. (Parameter 'name')

### ISSUE THREAD

**Issue by Depechie** [dotnet/aspire#2821]
Preview 4 of Aspire gives following exception when trying to start the AppHost:

```
Unhandled exception. System.ArgumentException: Resource name 'basket.api' is invalid. Name must contain only ASCII letters, digits, and hyphens. (Parameter 'name')
   at Aspire.Hosting.ApplicationModel.ModelName.ValidateName(String target, String name) in /_/src/Aspire.Hosting/ApplicationModel/ModelName.cs:line 39
   at Aspire.Hosting.ApplicationModel.Resource..ctor(String name) in /_/src/Aspire.Hosting/ApplicationModel/Resource.cs:line 30
   at Aspire.Hosting.ApplicationModel.ProjectResource..ctor(String name) in /_/src/Aspire.Hosting/ApplicationModel/ProjectResource.cs:line 10
   at Aspire.Hosting.ProjectResourceBuilderExtensions.AddProject[TProject](IDistributedApplicationBuilder builder, String name) in /_/src/Aspire.Hosting/Extensions/ProjectResourceBuilderExtensions.cs:line 27
```

The culprit is in defining a project like:

```
var basketAPI = builder.AddProject<Projects.otel_Basket_API>("basket.api")
```

This works fine with preview 3.

**Comment by davidfowl** [comment]
Yep, we changed the naming constraints. Change the . to a dash or underscore
