### ISSUE TITLE
`EndToEnd` tests failing to start up `testproject` with `dotnet run`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#2850]
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=600755&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=d268830e-a3ea-51fa-cf04-927cd28b9001) and [failing log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspire-refs-heads-main-41184ebf5ee84503b6/Aspire.EndToEnd.Tests/1/console.da51e905.log?helixlogtype=result)

```
...
[apphost] info: Aspire.Hosting.Dcp.api-server[0]
[apphost]       API server started	{"Address": "127.0.0.1", "Port": 46087}
[apphost] info: Aspire.Hosting.Dcp.dcpctrl.IdeExecutableRunner[0]
[apphost]       Executables cannot be started via IDE: missing required environment variable 'DEBUG_SESSION_PORT'
[apphost] info: Aspire.Hosting.Dcp.dcpctrl[0]
[apphost]       starting controller manager
...
[apphost] fail: Microsoft.Extensions.Hosting.Internal.Host[11]
[apphost]       Hosting failed to start
[apphost]       System.Threading.Tasks.TaskCanceledException: A task was canceled.
[apphost]          at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
[apphost]          at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
[apphost]          at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 170
[apphost]          at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 170
[apphost]          at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
[apphost]          at Aspire.Hosting.Dcp.ApplicationExecutor.CreateServicesAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 759
[apphost]          at Aspire.Hosting.Dcp.ApplicationExecutor.CreateServicesAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 759
[apphost]          at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 112
[apphost]          at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 69
[apphost]          at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
[apphost]          at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[apphost] Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
[apphost]    at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
[apphost]    at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
[apphost]    at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 170
[apphost]    at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 170
[apphost]    at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
[apphost]    at Aspire.Hosting.Dcp.ApplicationExecutor.CreateServicesAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 759
[apphost]    at Aspire.Hosting.Dcp.ApplicationExecutor.CreateServicesAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 759
[apphost]    at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 112
[apphost]    at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 69
[apphost]    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
[apphost]    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[apphost]    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[apphost]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[apphost]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[apphost]    at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 133
[apphost]    at TestProgram.RunAsync(CancellationToken cancellationToken) in /datadisks/disk1/work/A26F08C8/w/BB9C09DA/e/testassets/testproject/TestProject.AppHost/TestProgram.cs:line 144
[apphost]    at Program.<Main>$(String[] args) in /datadisks/disk1/work/A26F08C8/w/BB9C09DA/e/testassets/testproject/TestProject.AppHost/Program.cs:line 20
[apphost]    at Program.<Main>(String[] args)
...
```

The testproject never reaches `Distributed application started`. And after 5minutes of waiting for that the tests send `STOP` to the app which results in the exception at the end.

This is being hit on `main`, and on PRs now.

cc @eerhardt

**Comment by mitchdenny** [comment]
Is this still occurring @radical?

**Comment by radical** [comment]
No, this can be closed now. Thanks!
