### ISSUE TITLE
Redis component instrumentation (tracing) causes app to crash on start if Redis is unavailable

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2907]
The Redis component defaults to adding OpenTelemetry tracing for Redis. However if the configured Redis instance is unavailable at application start, the [`TelemetryHostedService` ](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Extensions.Hosting/Implementation/TelemetryHostedService.cs) will attempt to initialize all instrumentation and the Redis instrumentation initialization attempts to resolve the `IConnectionMultiplexer` from DI which attempts to connect to the instance (see [here](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/27a973b3cf862bf1b742146f1a6937251657980e/src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs#L122)). It seems an exception on this path will crash the startup of the app.

<details>
<summary>Stack trace</summary>

```
2024-03-14T15:57:24.5746136 fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
         at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log, Nullable`1 serverType, EndPointCollection endpoints) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 708
         at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 673
         at Microsoft.Extensions.Hosting.AspireRedisExtensions.<>c__DisplayClass3_0.<AddRedis>b__2(IServiceProvider sp) in D:\src\GitHub\dotnet\astra\src\Components\Aspire.StackExchange.Redis\AspireRedisExtensions.cs:line 82
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
         at OpenTelemetry.Trace.TracerProviderBuilderExtensions.<>c__DisplayClass4_0.<AddRedisInstrumentation>b__1(IServiceProvider sp)
         at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracerProviderBuilderExtensions.<>c__DisplayClass2_1`1.<AddInstrumentation>b__1()
         at OpenTelemetry.Trace.TracerProviderBuilderSdk.AddInstrumentation[TInstrumentation](Func`1 instrumentationFactory)
         at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracerProviderBuilderExtensions.<>c__DisplayClass2_0`1.<AddInstrumentation>b__0(IServiceProvider sp, TracerProviderBuilder builder)
         at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracingServiceCollectionExtensions.ConfigureTracerProviderBuilderCallbackWrapper.ConfigureBuilder(IServiceProvider serviceProvider, TracerProviderBuilder tracerProviderBuilder)
         at OpenTelemetry.Trace.TracerProviderSdk..ctor(IServiceProvider serviceProvider, Boolean ownsServiceProvider)
         at OpenTelemetry.Trace.TracerProviderBuilderBase.<>c.<.ctor>b__3_0(IServiceProvider sp)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
         at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.Initialize(IServiceProvider serviceProvider)
         at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

</details>

For the health checks we seem to guard against this by deferring the actual resolution of the connection until the health check runs https://github.com/dotnet/aspire/blob/11b012853a0c3c00f3510b1a96c0156a06129d29/src/Components/Aspire.StackExchange.Redis/AspireRedisExtensions.cs#L173-L177

We might need a similar guard for OpenTelemetry initialization. Not sure if any other components are impacted.

**Comment by eerhardt** [comment]
@DamianEdwards - can you provide a repro project for this?

> RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.

We default `AbortOnConnectFail=false` by default. So I think something about your setup is overriding this.

https://github.com/dotnet/aspire/blob/9df25bb1588eb88afcc551de348cc0f98bfe2d28/src/Components/Aspire.StackExchange.Redis/AspireRedisExtensions.cs#L244-L251

**Comment by DamianEdwards** [comment]
Repro steps:

1. Create a new solution using the Aspire Starter App template and ensure the "Use Redis for caching" option is selected
2. Edit the `Program.cs` in the AppHost project so that the Redis container pauses on start:
    ```csharp
    var cache = builder.AddRedis("cache")
        .WithEntrypoint("sleep").WithArgs("1d");
    ```
3. Run the AppHost project

**Comment by eerhardt** [comment]
From https://github.com/StackExchange/StackExchange.Redis/blob/main/docs/Configuration.md?plain=1

| connectRetry={int}     | `ConnectRetry`         | `3`                          | The number of times to repeat connect attempts during initial `Connect`                                   |
| connectTimeout={int}   | `ConnectTimeout`       | `5000`                       | Timeout (ms) for connect operations                                                                       |

You can up the connectTimeout if you expect it to be longer.

The issue is that the OTel instrumentation package needs to start "listening" to the IConnectionMultiplexer on app startup. If the Tracing was moved to be part of StackExchange.Redis itself, the Redis OTel instrumentation package could completely go away.

cc @mgravell @NickCraver

**Comment by DamianEdwards** [comment]
I don't think what we have right now is usable given that an application can't start if a configured Redis instance is unavailable. That's the opposite of resilient 😄

**Comment by DamianEdwards** [comment]
Could the OTel instrumentation defer listening until socket connect via `ConfigurationOptions.BeforeSocketConnect` or similar?

**Comment by DamianEdwards** [comment]
This seems to work https://github.com/dotnet/aspire/compare/main...damianedwards/defer-redis-tracing

**Comment by eerhardt** [comment]
That seems like a good approach. I wasn't aware we could register the ConnectionMultiplexer after the fact.
