### ISSUE TITLE
Occasional races and file access issues in Provisioner (azure cli)

### ISSUE THREAD

**Issue by oising** [dotnet/aspire#2983]
example stacktrace in a project that wants to deploy a storage account and eventhubs namespace:

```
Provisioning eventhubns...
WARNING: The configuration value of bicep.use_binary_from_path has been set to 'false'.
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [WinError 32] The process cannot access the file because it is being used by another process
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 4476, in build_bicep_file
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 107, in run_bicep_command
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 305, in _run_command
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
Error provisioning eventhubns.
System.InvalidOperationException: Command C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd bicep build --file "C:\Users\OisinGrehan\AppData\Local\Temp\aspirew3d0p52w.toj\eventhubns.module.bicep" --stdout returned non-zero exit code 1
   at Aspire.Hosting.Azure.Provisioning.BicepProvisioner.ExecuteCommand(ProcessSpec processSpec) in C:\p\github\aspire\src\Aspire.Hosting.Azure\Provisioning\Provisioners\BicepProvisioner.cs:line 360
   at Aspire.Hosting.Azure.Provisioning.BicepProvisioner.ExecuteCommand(ProcessSpec processSpec) in C:\p\github\aspire\src\Aspire.Hosting.Azure\Provisioning\Provisioners\BicepProvisioner.cs:line 368
   at Aspire.Hosting.Azure.Provisioning.BicepProvisioner.GetOrCreateResourceAsync(AzureBicepResource resource, ProvisioningContext context, CancellationToken cancellationToken) in C:\p\github\aspire\src\Aspire.Hosting.Azure\Provisioning\Provisioners\BicepProvisioner.cs:line 193
   at Aspire.Hosting.Azure.AzureProvisioner.ProcessResourceAsync(IConfiguration configuration, Lazy`1 provisioningContextLazy, IAzureResource resource, CancellationToken cancellationToken) in C:\p\github\aspire\src\Aspire.Hosting.Azure\Provisioning\Provisioners\AzureProvisioner.cs:line 246
```

**Comment by mitchdenny** [comment]
@oising were you hitting this with the eventhubs playground sample? I've not seen this before and I've done a lot of deployments. So I'm trying to figure out if this issue is still occuring.

**Comment by oising** [comment]
Haven't seen it since, @mitchdenny - it was that day.

**Comment by mitchdenny** [comment]
OK I'm going to close this. If it pops up again feel free to re-open.
