### ISSUE TITLE
Potential flakey test issue

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2987]
Just got this stack on Helix which after some sperlunking with @davidfowl might be an indication of a race-condition somewhere deep in OTel or our instrumentation:

```
at System.Threading.Tasks.TaskCompletionSource.SetResult()
   at Aspire.Components.Common.Tests.ActivityNotifier.OnEnd(Activity data) in /_/tests/Aspire.Components.Common.Tests/ActivityNotifier.cs:line 23
   at OpenTelemetry.Trace.TracerProviderSdk.<.ctor>b__10_1(Activity activity)
   at System.Diagnostics.SynchronizedList`1.EnumWithAction(Action`2 action, Object arg)
   at System.Diagnostics.Activity.Stop()
   at OpenTelemetry.Instrumentation.StackExchangeRedis.Implementation.RedisProfilerEntryToActivityConverter.ProfilerCommandToActivity(Activity parentActivity, IProfiledCommand command, StackExchangeRedisInstrumentationOptions options)
   at OpenTelemetry.Instrumentation.StackExchangeRedis.Implementation.RedisProfilerEntryToActivityConverter.DrainSession(Activity parentActivity, IEnumerable`1 sessionCommands, StackExchangeRedisInstrumentationOptions options)
   at OpenTelemetry.Instrumentation.StackExchangeRedis.StackExchangeRedisConnectionInstrumentation.Flush()
   at OpenTelemetry.Instrumentation.StackExchangeRedis.StackExchangeRedisConnectionInstrumentation.Dispose()
   at OpenTelemetry.Instrumentation.StackExchangeRedis.StackExchangeRedisInstrumentation.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<DisposeAsync>g__Await|26_0(Int32 i, ValueTask vt, List`1 toDispose)
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>g__DisposeAsync|21_0(Object o)
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.Internal.Host.Dispose()
   at Aspire.Components.ConformanceTests.ConformanceTests`2.LoggerFactoryIsUsedByRegisteredClient(Boolean registerAfterLoggerFactory, Boolean useKey) in /_/tests/Aspire.Components.Common.Tests/ConformanceTests.cs:line 296
   at InvokeStub_ConformanceTests`2.LoggerFactoryIsUsedByRegisteredClient(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Tests that were failing with this stack:
- `Aspire.StackExchange.Redis.Tests.ConformanceTests.Aspire.StackExchange.Redis.Tests.ConformanceTests.LoggerFactoryIsUsedByRegisteredClient`
- `Aspire.StackExchange.Redis.Tests.ConformanceTests.Aspire.StackExchange.Redis.Tests.ConformanceTests.HealthCheckReportsExpectedStatus`

**Comment by davidfowl** [comment]
https://github.com/dotnet/aspire/pull/2982#discussion_r1529466164
