### ISSUE TITLE
Unable to launch Aspire playground project due to Dcp timeout. 

### ISSUE THREAD

**Issue by oising** [dotnet/aspire#3003]
This has been sporadic for a few days but today it's constant. This is in my PR for event hubs (oising:support-eventhubs) with the EventHubs playground project:

```
Application orchestrator dependency check had an unexpected error System.TimeoutException: The operation has timed out.
   at Aspire.Hosting.Dcp.DcpDependencyCheck.EnsureDcpDependenciesAsync(CancellationToken cancellationToken) in C:\p\github\aspire\src\Aspire.Hosting\Dcp\DcpDependencyCheck.cs:line 67
```

I cannot get past this. Tried changing the timeout to be longer/infinite, but no joy. Aspire craps out and terminates. Any ideas?

**Comment by oising** [comment]
I figured it out. This is definitely something we need to highlight in release notes...

Docker Desktop apparently has a relatively new feature called "resource saver mode." This is a mode where it suspends internal processes and acts like it's completely crashed, ergo causing the timeout. I'd imagine the actual behaviour is that it should wake after being probed, but this doesn't appear to be the case for whatever the Dcp health check is doing; actually, it appears it will only wake when a container is started.

Restarting docker desktop "fixes" the issue. Thankfully it's possible to completely disable this feature.

![image](https://github.com/dotnet/aspire/assets/1844001/4f9d666f-998e-4799-b790-4604b53b8f6e)

**Comment by razvangoga** [comment]
started also hitting this problem. it worked fine until about an hour ago.

disabled the docker resource saver, restarted everything (win included), no updates pending...

any other ideas?

```
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.0-preview.4.24156.9+692dc41a65da572a7df25d53a9f2880afe59fdd8
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: D:\_work\mott\mis-v2\src\mis2\Aspire.AppHost
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: Timed out after 00:01:00 while waiting for the dashboard to be responsive.
         at Aspire.Hosting.Dcp.HttpPingDashboardAvailability.WaitForDashboardAvailabilityAsync(Uri url, TimeSpan timeout, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/HttpPingDashboardAvailability.cs:line 50
         at Aspire.Hosting.Dcp.ApplicationExecutor.CheckDashboardAvailabilityAsync(String delimitedUrlList, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 241
         at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 217
         at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 86
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 68
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.AggregateException: One or more errors occurred. (Timed out after 00:01:00 while waiting for the dashboard to be responsive.)
 ---> Aspire.Hosting.DistributedApplicationException: Timed out after 00:01:00 while waiting for the dashboard to be responsive.
   at Aspire.Hosting.Dcp.HttpPingDashboardAvailability.WaitForDashboardAvailabilityAsync(Uri url, TimeSpan timeout, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/HttpPingDashboardAvailability.cs:line 50
   at Aspire.Hosting.Dcp.ApplicationExecutor.CheckDashboardAvailabilityAsync(String delimitedUrlList, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 241
   at Aspire.Hosting.Dcp.ApplicationExecutor.StartDashboardAsDcpExecutableAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 217
   at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 86
   at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 68
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 133
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 141
```

**Comment by oising** [comment]
@razvangoga That looks to be a different issue about the Aspire dashboard. I'd open a new issue.

**Comment by DamianEdwards** [comment]
@karolz-ms @danegsta another case of Docker Desktop not waking up automatically from resource save mode.

**Comment by smbecker** [comment]
I am running into this as well since I upgraded to preview 4, although I am running from the command line on Linux and do not have Docker Desktop installed.

**Comment by mitchdenny** [comment]
@karolz-ms this should be handled in DCP correct?

**Comment by karolz-ms** [comment]
We have an ongoing discussion about this with Docker. That said, there is not much we can do, other than perhaps having a better, more actionable error message. If the Aspire app has containers in the mix, we need a functional container orchestrator.

**Comment by karolz-ms** [comment]
Will do

**Comment by dbreshears** [comment]
We have improved the error message when Docker is stuck in resource saver mode in 0.4.0 of DCP, of course can't address the underlying Docker issue but have raised the issue with them already.
