### ISSUE TITLE
[WebToolsE2E] Running the built-in test that comes with the Aspire Starter App template fails with TimeoutRejectedException

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#3107]
**REGRESSION INFO**: Worked-in: Aspire 8.0 P4

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 3 build main-34721.267 (includes .NET SDK 8.0.200 and .NET workload Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire 8.0.0-preview.5.24172.3, apply feeds

**REPRO STEPS**
1. New Aspire Starter Application > check 'use redis for caching' and 'Create a tests project' > AspireStarterApp3
2. Build solution and Ctrl + F5 > works fine
3. Open Test Explorer in VS
4. Run Tests

**ACTUAL**
- There's only 1 test in AspireStarterApp3.Tests but it seems to take a long time for the test to get discovered
- Running the test fails
![image](https://github.com/dotnet/aspire/assets/8246794/36cf68af-0ecb-47df-8cc2-55ecdf98aa55)

Output window Tests pane shows the following exception
```
Test data store opened in 0.003 sec.
========== Starting test discovery ==========
========== Test discovery skipped: All test containers are up to date ==========
Building Test Projects
========== Starting test run ==========
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.5.3.1+6b60a9e56a (64-bit .NET 8.0.2)
[xUnit.net 00:00:00.08]   Starting:    AspireStarterApp3.Tests
[xUnit.net 00:00:34.05]     AspireStarterApp3.Tests.WebTests.GetWebResourceRootReturnsOkStatusCode [FAIL]
[xUnit.net 00:00:34.05]       Polly.Timeout.TimeoutRejectedException : The operation didn't complete within the allowed timeout of '00:00:30'.
[xUnit.net 00:00:34.05]       ---- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
[xUnit.net 00:00:34.05]       -------- System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
[xUnit.net 00:00:34.05]       ------------ System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request.
[xUnit.net 00:00:34.05]       Stack Trace:
[xUnit.net 00:00:34.05]            at Polly.Utils.ExceptionUtilities.TrySetStackTrace[T](T exception)
[xUnit.net 00:00:34.05]            at Polly.Timeout.TimeoutResilienceStrategy.ExecuteCore[TResult,TState](Func`3 callback, ResilienceContext context, TState state)
[xUnit.net 00:00:34.05]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.05]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.05]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.05]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.05]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.05]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.05]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.05]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.05]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.05]            at Polly.Utils.StrategyHelper.<ExecuteCallbackSafeAsync>g__AwaitTask|0_0[TResult,TState,T](ValueTask`1 task, Boolean continueOnCapturedContext)
[xUnit.net 00:00:34.05]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.05]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.05]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.06]            at Polly.Utils.Pipeline.BridgeComponent`1.<ConvertValueTask>g__ConvertValueTaskAsync|5_0[TTo](ValueTask`1 valueTask, ResilienceContext resilienceContext)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.06]            at Polly.Retry.RetryResilienceStrategy`1.ExecuteCore[TState](Func`3 callback, ResilienceContext context, TState state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.06]            at Polly.Utils.StrategyHelper.<ExecuteCallbackSafeAsync>g__AwaitTask|0_0[TResult,TState,T](ValueTask`1 task, Boolean continueOnCapturedContext)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.06]            at Polly.Utils.Pipeline.BridgeComponent`1.<ConvertValueTask>g__ConvertValueTaskAsync|5_0[TTo](ValueTask`1 valueTask, ResilienceContext resilienceContext)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.06]            at Polly.CircuitBreaker.CircuitBreakerResilienceStrategy`1.ExecuteCore[TState](Func`3 callback, ResilienceContext context, TState state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.06]            at Polly.Utils.StrategyHelper.<ExecuteCallbackSafeAsync>g__AwaitTask|0_0[TResult,TState,T](ValueTask`1 task, Boolean continueOnCapturedContext)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.06]            at Polly.Timeout.TimeoutResilienceStrategy.ExecuteCore[TResult,TState](Func`3 callback, ResilienceContext context, TState state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.06]            at Polly.Utils.StrategyHelper.<ExecuteCallbackSafeAsync>g__AwaitTask|0_0[TResult,TState,T](ValueTask`1 task, Boolean continueOnCapturedContext)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[xUnit.net 00:00:34.06]            at Microsoft.Extensions.Http.Resilience.ResilienceHandler.<>c.<<SendAsync>b__3_0>d.MoveNext()
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
[xUnit.net 00:00:34.06]            at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.06]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.06]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.06]            at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
[xUnit.net 00:00:34.07]            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.07]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
[xUnit.net 00:00:34.07]            at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.07]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
[xUnit.net 00:00:34.07]            at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.07]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
[xUnit.net 00:00:34.07]            at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
[xUnit.net 00:00:34.07]            at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[xUnit.net 00:00:34.07]            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[xUnit.net 00:00:34.07]            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[xUnit.net 00:00:34.07]            at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__173_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
[xUnit.net 00:00:34.07]            at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
[xUnit.net 00:00:34.07]            at System.Threading.ThreadPoolWorkQueue.Dispatch()
[xUnit.net 00:00:34.07]            at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[xUnit.net 00:00:34.07]         --- End of stack trace from previous location ---
[xUnit.net 00:00:34.07]            at Polly.Outcome`1.ThrowIfException()
[xUnit.net 00:00:34.07]            at Microsoft.Extensions.Http.Resilience.ResilienceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[xUnit.net 00:00:34.07]         C:\Users\balach\source\repos\AspireStarterApp3\AspireStarterApp3.Tests\WebTests.cs(17,0): at AspireStarterApp3.Tests.WebTests.GetWebResourceRootReturnsOkStatusCode()
[xUnit.net 00:00:34.07]         C:\Users\balach\source\repos\AspireStarterApp3\AspireStarterApp3.Tests\WebTests.cs(20,0): at AspireStarterApp3.Tests.WebTests.GetWebResourceRootReturnsOkStatusCode()
[xUnit.net 00:00:34.07]         --- End of stack trace from previous location ---
[xUnit.net 00:00:34.07]         ----- Inner Stack Trace -----
[xUnit.net 00:00:34.07]            at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at Microsoft.Extensions.Http.Resilience.ResilienceHandler.<>c.<<SendAsync>b__3_0>d.MoveNext()
[xUnit.net 00:00:34.07]         ----- Inner Stack Trace -----
[xUnit.net 00:00:34.07]            at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]            at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
[xUnit.net 00:00:34.07]            at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
[xUnit.net 00:00:34.07]            at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:34.07]         ----- Inner Stack Trace -----
[xUnit.net 00:00:34.07]         
[xUnit.net 00:00:34.08]   Finished:    AspireStarterApp3.Tests
========== Test run finished: 1 Tests (0 Passed, 1 Failed, 0 Skipped) run in 34.1 sec ==========

```

**EXPECTED**
Test to be discovered easily and run successfully

**Comment by balachir** [comment]
Tracking this on the tooling side with AzDO 2005271

**Comment by hex2bit** [comment]
I get a similar error when debugging an Aspire project within Visual Studio.  Tracing through the code, the API code complete fine (returning a success response), but Aspire ultimately throws an 500 error due to the above noted connection reset issue.  If seems like Aspire has some really short internal threshold on a server endpoint being able to respond to something (keep-alive?).

**Comment by hex2bit** [comment]
I cannot comment on the original poster's question regarding slow tests, however I can comment on the root source of the logged error and what I was seeing.  The following config sets up Polly with a default timeout configuration, which affects Aspire managed connections.
http.AddStandardResilienceHandler();

This discussion outlines how it can be configured with different timeout values, in case you have long running APIs or need some time for debugging.
https://github.com/dotnet/aspire/discussions/1112

**Comment by DamianEdwards** [comment]
This was fixed in VS.
