### ISSUE TITLE
[tests] `TracingEnablesTheRightActivitySource` test failing for `EntityFramework.SqlServer` and `SqlClient`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#3221]
[build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=621042&view=results), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspire-refs-heads-main-f2408aa1ce7c4eb486/Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests/2/console.25f8142b.log?helixlogtype=result):

```
  Failed Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests.ConformanceTests.TracingEnablesTheRightActivitySource [1 m]
  Error Message:
   Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Timed out at 3/27/2024 5:34:55 PM after 60000ms waiting for remote process.
	Process ID: 35446
	Handle: 4880
	Name: dotnet
	MainModule: /datadisks/disk1/work/B5B5097E/p/dotnet-cli/dotnet
	StartTime: 3/27/2024 5:33:55 PM
	TotalProcessorTime: 00:00:02.2799999

  Stack Trace:
     at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 55
   at Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests.ConformanceTests.TracingEnablesTheRightActivitySource() in /_/tests/Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests/ConformanceTests.cs:line 116
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
```
  Failed Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests.EnrichSqlServerTests.TracingEnablesTheRightActivitySource [1 m]
  Error Message:
   Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Timed out at 3/27/2024 5:34:57 PM after 60000ms waiting for remote process.
	Process ID: 35497
	Handle: 4904
	Name: dotnet
	MainModule: /datadisks/disk1/work/B5B5097E/p/dotnet-cli/dotnet
	StartTime: 3/27/2024 5:33:57 PM
	TotalProcessorTime: 00:00:02.1700000

  Stack Trace:
     at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 55
   at Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests.ConformanceTests.TracingEnablesTheRightActivitySource() in /_/tests/Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests/ConformanceTests.cs:line 116
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
```
  Failed Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests.ConformanceTests_TypeSpecificConfig.TracingEnablesTheRightActivitySource [1 m]
  Error Message:
   Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Timed out at 3/27/2024 5:35:56 PM after 60000ms waiting for remote process.
	Process ID: 36471
	Handle: 5036
	Name: dotnet
	MainModule: /datadisks/disk1/work/B5B5097E/p/dotnet-cli/dotnet
	StartTime: 3/27/2024 5:34:56 PM
	TotalProcessorTime: 00:00:02.1500000

  Stack Trace:
     at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 55
   at Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests.ConformanceTests.TracingEnablesTheRightActivitySource() in /_/tests/Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests/ConformanceTests.cs:line 116
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by radical** [comment]
cc @sebastienros could this be due to:
```
commit efcab05d6256fb2df72d94034d890cbab2808b3a
Author: Sébastien Ros <sebastienros@gmail.com>
Date:   Tue Mar 26 21:42:10 2024 -0700

    Detect conflicting settings when using EnrichEF (#3159)
```

**Comment by radical** [comment]
`SqlClient` also failing, log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspire-refs-heads-main-227f579e3d3848a4ac/Aspire.Microsoft.Data.SqlClient.Tests/1/console.72cc0fcd.log?helixlogtype=result

**Comment by radical** [comment]
This is still being hit.

**Comment by radical** [comment]
Should retries be enabled for this, unless somebody can investigate? cc @eerhardt @joperezr
