### ISSUE TITLE
[WebToolsE2E][Aspire] An error occurs when running the aspire project using http: The 'applicationUrl' setting must be an https address unless the 'ASPIRE_ALLOW_UNSECURED_TRANSPORT' environment variable is set to true.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3250]
**REGRESSION INFO**: Not repro on Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Aspire 8.0 Preview 5 [8.0.0-preview.5.24177.21]
3. Apply NuGet Feeds

**REPRO STEPS**

1. Open Command Prompt, run the following commands to create and run the project using http

```
dotnet new aspire-starter -o AspireStarterApp1
cd AspireStarterApp1/AspireStarterApp1.AppHost
dotnet run -lp http
```

**NOTE**: This issue is also reproduced in aspire application and web app with aspire selected.

**ACTUAL**
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Microsoft.Extensions.Options.OptionsValidationException: The 'applicationUrl' setting must be an https address unless the 'ASPIRE_ALLOW_UNSECURED_TRANSPORT' environment variable is set to true. This configuration is commonly set in the launch profile. See https://aka.ms/dotnet/aspire/allowunsecuredtransport for more details.
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
         at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
         at Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.<>c__DisplayClass0_1`1.<ValidateOnStart>b__1()
         at Microsoft.Extensions.Options.StartupValidator.Validate()
      --- End of stack trace from previous location ---
         at Microsoft.Extensions.Options.StartupValidator.Validate()
         at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Unhandled exception. System.AggregateException: One or more errors occurred. (The 'applicationUrl' setting must be an https address unless the 'ASPIRE_ALLOW_UNSECURED_TRANSPORT' environment variable is set to true. This configuration is commonly set in the launch profile. See https://aka.ms/dotnet/aspire/allowunsecuredtransport for more details.)
 ---> Microsoft.Extensions.Options.OptionsValidationException: The 'applicationUrl' setting must be an https address unless the 'ASPIRE_ALLOW_UNSECURED_TRANSPORT' environment variable is set to true. This configuration is commonly set in the launch profile. See https://aka.ms/dotnet/aspire/allowunsecuredtransport for more details.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.<>c__DisplayClass0_1`1.<ValidateOnStart>b__1()
   at Microsoft.Extensions.Options.StartupValidator.Validate()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Options.StartupValidator.Validate()
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 102
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 110
   at Program.<Main>$(String[] args) in C:\Users\v-reinawang\AspireStarterApp1\AspireStarterApp1.AppHost\Program.cs:line 8

![image](https://github.com/dotnet/aspire/assets/109339894/5a35d10e-a121-46c7-9b7a-ae7b408d4b28)

**EXPECTED**
Can be successfully run using http.

**Comment by balachir** [comment]
This is By Design now when running http launch profile. The default launch profile for aspire apps is now https and this exception will not show up for https profile.

If you want to specifically run with the http launch profile (using `dotnet run -lp http` or selecting the http profile in the VS Debug dropdown), one way is to set the `"ASPIRE_ALLOW_UNSECURED_TRANSPORT": "true"` in the launchSettings.json of the AppHost project (eg: add line 26 in screenshot below).

![image](https://github.com/dotnet/aspire/assets/8246794/70004a82-7992-428e-9bb0-3412b9fe0bf1)

cc: @davidfowl

**Comment by davidfowl** [comment]
cc @IEvangelist Big changes coming for docs

**Comment by KieranFoot** [comment]
I'm having the same issue, even when specifying `launchProfileName: "https"` for each project.

**Comment by davidfowl** [comment]
@KieranFoot what issue is that?

**Comment by KieranFoot** [comment]
@davidfowl Apologies, it's the same error as the OP was having, however my fault. I was using the appsettings which did not have a https endpoint configured for the AppHost project itself.

Perhaps the exception message itself could be expanded to show which project is misconfigured.
