### ISSUE TITLE
AzureProvisioner user secrets parsing doesn't support comments

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#3284]
When modifying the secrets.json file from "Manage user secrets" in the AppHost, if you add a comment to the .json file and F5, the Azure Provisioning throws:

```
fail: Aspire.Hosting.Azure.AzureProvisioner[0]
      Failed to provision Azure resources because user secrets file is not well-formed JSON.
      System.Text.Json.JsonReaderException: '/' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 2 | BytePositionInLine: 4.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
         at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
         at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
         at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
         at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOptions, JsonDocumentOptions documentOptions)
         at Aspire.Hosting.Azure.AzureProvisioner.GetUserSecretsAsync(String userSecretsPath, CancellationToken cancellationToken) in /_/src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs:line 150
```

We should allow comments in this parsing.

**Comment by Cethric** [comment]
Taking this on as a quick intro to committing to the aspire project, I have been lurking in the background for a while now.

Looks like I can just use the same format from [JsonConfigurationFileParser.cs](https://github.com/dotnet/runtime/blob/ca9893f6bda7866370c58bd03ed60854019fe5de/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationFileParser.cs#L24) in runtime
