### ISSUE TITLE
Azure Provisioning fails on secondary tenant

### ISSUE THREAD

**Issue by pedershk** [dotnet/aspire#3544]
When trying to start a project with an Azure SignalR resource defined, provisioning fails. I'm able to use the Connected Services-> Azure Resource Provisioning settings to set Subscription Name, Location and Resource group, and all three are correctly defined in my user secrets after. 

When starting projects, resource provisioning fails with:

```
Error provisioning signalr.
Azure.RequestFailedException: The client 'REDACTED@microsoft.com' with object id 'REDACTED' does not have authorization to perform action 'Microsoft.Resources/subscriptions/read' over scope '/subscriptions/REDACTED' or the scope is invalid. If access was recently granted, please refresh your credentials.
Status: 403 (Forbidden)
ErrorCode: AuthorizationFailed

Content:
{"error":{"code":"AuthorizationFailed","message":"The client 'REDACTED@microsoft.com' with object id 'REDACTED' does not have authorization to perform action 'Microsoft.Resources/subscriptions/read' over scope '/subscriptions/REDACTED' or the scope is invalid. If access was recently granted, please refresh your credentials."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-request-id: 78621442-aabe-4b16-9184-abe111313da2
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Tue, 09 Apr 2024 23:07:50 GMT
Connection: close
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 384

   at Azure.ResourceManager.Resources.SubscriptionsRestOperations.GetAsync(String subscriptionId, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.SubscriptionResource.GetAsync(CancellationToken cancellationToken)
   at Azure.ResourceManager.ArmClient.GetDefaultSubscriptionAsync(CancellationToken cancellationToken)
   at Aspire.Hosting.Azure.AzureProvisioner.GetProvisioningContextAsync(Lazy`1 userSecretsLazy, CancellationToken cancellationToken) in /_/src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs:line 337
   at Aspire.Hosting.Azure.AzureProvisioner.ProcessResourceAsync(IConfiguration configuration, Lazy`1 provisioningContextLazy, IAzureResource resource, CancellationToken cancellationToken) in /_/src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs:line 265
```

This subscription is in a tenant where my Entra ID is a Member guest account.

az cli, azd, portal, all other ways to access it works, and I do in fact have the neccessary permissions. The Azure Resource provisioning setup mentioned above is also able to create a new resource group on the subscription.

I've tried setting an Azure:Tenant secret to both tenant id and tenant fqdn as well, to no avail.

When deploying to my primary tenant, everything works.

**Comment by timheuer** [comment]
@pedershk Can you share the VS version you have? And in VS do you have multiple identities logged in?

**Comment by pedershk** [comment]
> @pedershk Can you share the VS version you have? And in VS do you have multiple identities logged in?

17.10.0 Preview 3.

Only one Entra Identity - Microsoft.com AAD account, as well as my GitHub account:
![image](https://github.com/dotnet/aspire/assets/667361/cb5cf0de-8328-4525-8e9f-507228879142)

The account is a member of four tenants in total, the default tenant and three additional tenants.

**Comment by timheuer** [comment]
Thank you for this @pedershk -- @anvillan could we be using the wrong auth token?

@pedershk when you use `azd account show` is it showing the right tenant as the default, etc.?

**Comment by pedershk** [comment]
> Thank you for this @pedershk -- @anvillan could we be using the wrong auth token?
> 
> @pedershk when you use `azd account show` is it showing the right tenant as the default, etc.?

I assume you mean `azd config show` since there is no `azd account show`(at least in azd 1.8.0). The output doesn't show a tenant at all:

```
{
  "alpha": {
    "infraSynth": "on",
    "resourceGroupDeployments": "on"
  },
  "defaults": {
    "location": "norwayeast",
    "subscription": "REDACTED"
  }
}
```

**Comment by timheuer** [comment]
Sorry yeah I meant `az account show`

And also in VS, is this matching your 'default tenant':
![image](https://github.com/dotnet/aspire/assets/4821/b35f400a-7d05-4b60-9ba9-9744a4cdb14b)

**Comment by pedershk** [comment]
`az account show` shows the guest tenant that I'm trying to deploy to as my homeTenantId, and my default tenant under "managedByTenants". The subscription I'm trying to deploy to is the selected subscription.

Yes, the Default Tenant is correct (the MS home tenant).

**Comment by timheuer** [comment]
@pedershk Wondering if you can try something for us.  In the AppHost appsettings.json (or in user secrets), change the credential source:

```json
"Azure": {
  "CredentialSource": "VisualStudio"
}
```

Note: Other options: AzureCli, AzurePowerShell, VisualStudioCode, AzureDeveloperCli, InteractiveBrowser

**Comment by pedershk** [comment]
> @pedershk Wondering if you can try something for us. In the AppHost appsettings.json (or in user secrets), change the credential source:
> 
> ```json
> "Azure": {
>   "CredentialSource": "VisualStudio"
> }
> ```
> 
> Note: Other options: AzureCli, AzurePowerShell, VisualStudioCode, AzureDeveloperCli, InteractiveBrowser

Thank you! Setting it to `AzureCli` worked for me. The az cli has the tenant/subscription I'm using here currently set as its defaults. But its still strange - as the Visual Studio UI seems to be able to interact with the tenant/subscription combo in question just fine. Setting the credential source to `VisualStudio`, however, does not work.

**Comment by davidfowl** [comment]
When you run with the az cli credentials, it's likely that your runtime code also needs to change to do the same thing (the aspire component needs to set the right TokenCredential).

cc @tg-msft
