### ISSUE TITLE
No such host after upgrade from P4 to P5

### ISSUE THREAD

**Issue by JohnVottero** [dotnet/aspire#3565]
I upgraded from preview 4 to preview 5 and I'm running into problems resolving executable services. I have two executable services that are defined like this:

```
var tenantServicesServiceCommand = Path.GetFullPath("../../../tenant/src/TenantServices.Service/bin/Debug/net8.0/Dacier.TenantServices.Service.exe");
var tenantServicesServiceWorkingDirectory = Path.GetFullPath("../../../tenant/src/TenantServices.Service/bin/Debug/net8.0/");
var tenantService = builder.AddExecutable("tenantServicesService", tenantServicesServiceCommand, tenantServicesServiceWorkingDirectory)
    .WithCommonEnvironment()
    .WithEndpoint(port:8020, scheme:"https", name:tenantServicesEndpointName, env:"ASPNETCORE_HTTPS_PORTS");
```

Then, other services reference them like this:

```
var serviceGrpc = builder.AddProject<Projects.Scheduler_Entities_Service_Grpc>("schedulerEntitiesServiceGrpc")
    .WithCommonEnvironment()
    .WithReference(tenantService.GetEndpoint(tenantServicesEndpointName));
```

This was working in Preview 4 but in Preview 5 it is failing with:

```
2024-04-10T12:14:43.4384689 info: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Unavailable', Message: 'Error starting gRPC call. HttpRequestException: No such host is known. (tenantservicesservice:443) SocketException: No such host is known.'.
      System.Net.Http.HttpRequestException: No such host is known. (tenantservicesservice:443)
       ---> System.Net.Sockets.SocketException (11001): No such host is known.
...
``` 

Looking at the environment variables of a service that can't resolve the host I see:

services__tenantServicesService__tsep__0 = https://localhost:8020

"tsep" is the value of tenantServicesEndpointName so, I think that is correct, right?

Why can't this be resolved?

Here is the complete call stack from the failure:

```
2024-04-10T12:35:05.2469371 info: Grpc.AspNetCore.Server.ServerCallHandler[7]
      Error status code 'Unavailable' with detail 'Error starting gRPC call. HttpRequestException: No such host is known. (tenantservicesservice:443) SocketException: No such host is known.' raised.
      System.Net.Http.HttpRequestException: No such host is known. (tenantservicesservice:443)
       ---> System.Net.Sockets.SocketException (11001): No such host is known.
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.Metrics.MetricsHandler.SendAsyncWithMetrics(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
         at Microsoft.Extensions.ServiceDiscovery.Http.ResolvingHttpDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Microsoft.Extensions.ServiceDiscovery/Http/ResolvingHttpDelegatingHandler.cs:line 53
         at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
         at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
```

**Comment by christiannagel** [comment]
I'm having the same issue. This could be related with #2896 
This workaround https://github.com/dotnet/aspire/issues/2896#issuecomment-2010329355 does not build anymore because `UriEndpoint` is now `internal`

**Comment by JohnVottero** [comment]
I can make gRPC calls but only between services that were added with AddProject. I can't call services added with AddExecutable. Both gRPC and REST are broken.

With AddProject I don't explicitly add endpoints, I let Aspire figure that out. I have to add endpoints with AddExecutable.

**Comment by davidfowl** [comment]
When you see "no such host" errors it means the service discovery system isn't reading the configuration section, or the format is wrong. I'm guessing that you didn't update the service discovery package to preview5?

**Comment by JohnVottero** [comment]
Updating Microsoft.Extensions.ServiceDiscovery to Preview 5 resolved this issue for me.

Thanks David!
