### ISSUE TITLE
[Preview 5] Container with multiple endpoints leads to InvalidOperationException

### ISSUE THREAD

**Issue by ngruson** [dotnet/aspire#3569]
I'm using Papercut in my solution to act as a local SMTP server for development purposes.
It exposes 2 endpoints, one for port 25 to receive email and another port for its web interface.
This was working in preview 4.

```csharp
builder.AddContainer("papercut", "jijiechen/papercut")
    .WithEndpoint(port: 25, targetPort: 25)
    .WithEndpoint(port: 37408, targetPort: 37408);
```

Yesterday I updated to VS2022 17.10 and Aspire preview 5.
The code above throws an `InvalidOperationException`.

The call stack:
```
Aspire.Hosting.Dcp.ApplicationExecutor[0]
      Watch task over kubernetes Service resources terminated unexpectedly. Check to ensure dcpd process is running.
      System.InvalidOperationException: Sequence contains more than one matching element
         at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
         at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
         at Aspire.Hosting.ApplicationModel.EndpointReference.GetEndpointAnnotation() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 100
         at Aspire.Hosting.ApplicationModel.EndpointReference.get_EndpointAnnotation() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 18
         at Aspire.Hosting.Dcp.ApplicationExecutor.GetUrls(CustomResource resource) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 581
         at Aspire.Hosting.Dcp.ApplicationExecutor.ToSnapshot(Container container, CustomResourceSnapshot previous) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 467
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass37_0.<TryRefreshResource>b__0(CustomResourceSnapshot s) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 451
         at Aspire.Hosting.ApplicationModel.ResourceNotificationService.PublishUpdateAsync(IResource resource, String resourceId, Func`2 stateFactory) in /_/src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs:line 42
         at Aspire.Hosting.Dcp.ApplicationExecutor.TryRefreshResource(String resourceKind, String resourceName) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 447
         at Aspire.Hosting.Dcp.ApplicationExecutor.ProcessServiceChange(WatchEventType watchEventType, Service service) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 427
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass32_1`1.<<WatchResourceChanges>b__8>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 233
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass32_1`1.<<WatchResourceChanges>b__8>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 227
      --- End of stack trace from previous location ---
         at Polly.ResiliencePipeline.<>c.<<ExecuteAsync>b__3_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Polly.Outcome`1.GetResultOrRethrow()
         at Polly.ResiliencePipeline.ExecuteAsync(Func`2 callback, CancellationToken cancellationToken)
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass32_0.<<WatchResourceChanges>g__WatchKubernetesResource|1>d`1.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 223
```

When I comment one of the `WithEndpoint` calls, the solution does start without errors.
How do I expose multiple endpoints on a container in preview 5?

**Comment by timheuer** [comment]
Conflicting port names (absent a name, it would get 'tcp' and then two same-named ports.  Try adding name/scheme:

```csharp
builder.AddContainer("papercut", "jijiechen/papercut")
    .WithEndpoint(port: 25, targetPort: 25, name:"smtp")
    .WithEndpoint(port: 37408, targetPort: 37408, name:"web", scheme:"http");
```

**Comment by ngruson** [comment]
Yes, that did the trick.
Thanks @timheuer!
