### ISSUE TITLE
[Aspire.Hosting.Dapr] The endpoint `http` is not allocated for the resource `frontend`.

### ISSUE THREAD

**Issue by ngruson** [dotnet/aspire#3596]
I'm running a Dapr sidecar for a Blazor app like this:

```csharp
builder.AddProject<Projects.UI_Blazor>("frontend")
    .WithDaprSidecar(new DaprSidecarOptions
    {
        AppId = "frontendDapr",
        AppPort = 5001,
        ResourcesPaths = ImmutableHashSet.Create("./components"),
        LogLevel = "debug"
    })
```

It broke after updating to preview 5.

```
Failed to create resource frontend-dapr-cli
System.InvalidOperationException: The endpoint `http` is not allocated for the resource `frontend`.
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_AllocatedEndpoint() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 96
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_Host() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 78
   at Aspire.Hosting.Dapr.DaprDistributedApplicationLifecycleHook.<>c__DisplayClass6_1.<BeforeStartAsync>b__9(IList`1 updatedArgs) in /_/src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs:line 194
   at Aspire.Hosting.ApplicationModel.CommandLineArgsCallbackAnnotation.<>c__DisplayClass1_0.<.ctor>b__0(CommandLineArgsCallbackContext c) in /_/src/Aspire.Hosting/ApplicationModel/CommandLineArgsCallbackAnnotation.cs:line 32
   at Aspire.Hosting.Dcp.ApplicationExecutor.CreateExecutableAsync(AppResource er, ILogger resourceLogger, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 1194
   at Aspire.Hosting.Dcp.ApplicationExecutor.<CreateExecutablesAsync>g__CreateExecutableAsyncCore|53_0(AppResource cr, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 1134
```

The `Aspire.Hosting.Dapr` code seems to be looking for a resource endpoint called `http`.
https://github.com/dotnet/aspire/blob/f6fab970f6e2f4f94947d829b3e534b0b894fd96/src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs#L174-L183

This doesn't exist, the endpoint is called `https` since the Blazor app is running https.
When I change the Blazor app to run with http instead of https, then it does work. The endpoint is called `http` in that case.
Renaming the launch profile is not enough, I have to change the application url.
But I rather run with https.
Is there a way I can influence the endpoint name of the Blazor app?
So that I can name it http even though the scheme is https.

**Comment by davidfowl** [comment]
Did you upgrade all of the packages to preview5?

> The Aspire.Hosting.Dapr code seems to be looking for a resource endpoint called http.

It's looking for an endpoint called "http" in your application. What does your launch profile look like?

> But I rather run with https.

https doesn't work with dapr in preview 5. This PR will resolve it https://github.com/dotnet/aspire/pull/3184

**Comment by ngruson** [comment]
Yes, I updated the Aspire packages.

```xml
<PackageVersion Include="Aspire.Hosting.AppHost" Version="8.0.0-preview.5.24201.12" />
<PackageVersion Include="Aspire.Hosting.Dapr" Version="8.0.0-preview.5.24201.12" />
```

The launch profile:

```json
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
    "profiles": {
      "https": {
        "commandName": "Project",
        "dotnetRunMessages": true,
        "launchBrowser": true,
        "applicationUrl": "https://localhost:5001",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      }
    }
  }

```

But ok, I will use http for the time being and follow the PR.
Shall I close this issue?

**Comment by davidfowl** [comment]
Yes, we just merged the PR, it'll be opt in https for now.
