### ISSUE TITLE
After adding Prometheus AspNetCore Exporter package, API app startup fails when launching with AppHost project and /metrics endpoint cannot work

### ISSUE THREAD

**Issue by kyandaks** [dotnet/aspire#3600]
I created a sample web API and added Aspire using .NET Aspire Orchestrator support. 
This worked as expected. 

My goal is to expose prometheus metrics using the /metrics endpoint, add the following annotations ```prometheus.io/scrape: "true"``` and ```prometheus.io/path: /metrics``` to my Kubernetes deployment manifest such that prometheus can scrape this pod/app and I visualize the metrics using the Grafana dashboards the dotnet team provided. 

Challenge is that upon adding the OpenTelemetry.Exporter.Prometheus.AspNetCore Nuget package and uncommenting the line below:
`
// Uncomment the following lines to enable the Prometheus exporter (requires the OpenTelemetry.Exporter.Prometheus.AspNetCore package)
builder.Services.AddOpenTelemetry()
   .WithMetrics(metrics => metrics.AddPrometheusExporter());
`
I get this error when I run using the AspireApp.AppHost project:
`
System.MethodAccessException
  HResult=0x80131510
  Message=Attempt by method 'Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(Microsoft.Extensions.DependencyInjection.IServiceCollection)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.
  Source=OpenTelemetry.Extensions.Hosting
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(IServiceCollection services)
   at Microsoft.Extensions.Hosting.Extensions.ConfigureOpenTelemetry(IHostApplicationBuilder builder) in C:\Projects\AspireApp\AspireApp.ServiceDefaults\Extensions.cs:line 42
   at Microsoft.Extensions.Hosting.Extensions.AddServiceDefaults(IHostApplicationBuilder builder) in C:\Projects\AspireApp\AspireApp.ServiceDefaults\Extensions.cs:line 16
   at Program.<Main>$(String[] args) in C:\Projects\AspireApp\AspireApp\Program.cs:line 3
`
I have uploaded the code in a public repo here - https://github.com/kyandaks/AspireApp/blob/main/AspireApp.ServiceDefaults/Extensions.cs

Line 42 contains the code block for 
`builder.Services.AddOpenTelemetry()`

NET ASPIRE Version: Aspire version: 8.0.0-preview.4.24156.9+692dc41a65da572a7df25d53a9f2880afe59fdd8

Any help will be appreciated.

**Comment by kyandaks** [comment]
I figured out the issue upon following this video - https://www.youtube.com/watch?v=nFU-hcHyl2s
I have not uncommented this section:
`
// Uncomment the following line to enable the Prometheus endpoint (requires the OpenTelemetry.Exporter.Prometheus.AspNetCore package)
        app.MapPrometheusScrapingEndpoint();
`

Upon doing this, everything checks out
