### ISSUE TITLE
Issue when trying to run aspire in github codespace.

### ISSUE THREAD

**Issue by SalomonHenke** [dotnet/aspire#3652]
Not sure of the root cause. Tried to remove and reinstall the aspire workloads. 

```
: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: Application orchestrator dependency check had an unexpected error System.InvalidOperationException: Command /usr/share/dotnet/packs/Aspire.Hosting.Orchestration.linux-x64/8.0.0-preview.5.24201.12/tools/dcp info returned non-zero exit code 1
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 78.
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 105
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.AggregateException: One or more errors occurred. (Application orchestrator dependency check had an unexpected error System.InvalidOperationException: Command /usr/share/dotnet/packs/Aspire.Hosting.Orchestration.linux-x64/8.0.0-preview.5.24201.12/tools/dcp info returned non-zero exit code 1
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 78.)
 ---> Aspire.Hosting.DistributedApplicationException: Application orchestrator dependency check had an unexpected error System.InvalidOperationException: Command /usr/share/dotnet/packs/Aspire.Hosting.Orchestration.linux-x64/8.0.0-preview.5.24201.12/tools/dcp info returned non-zero exit code 1
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 78.
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 105
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
   at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 102
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 110
   at Program.<Main>$(String[] args) in /workspaces/Educade.io/Educade/Educade.AppHost/Program.cs:line 23
```

**Comment by mitchdenny** [comment]
There are some compat issues we are still working on with GitHub Codespaces. Just to confirm could you invoke the following:

```shell
/usr/share/dotnet/packs/Aspire.Hosting.Orchestration.linux-x64/8.0.0-preview.5.24201.12/tools/dcp info
```

What is the output?

**Comment by SalomonHenke** [comment]
> There are some compat issues we are still working on with GitHub Codespaces. Just to confirm could you invoke the following:
> 
> ```shell
> /usr/share/dotnet/packs/Aspire.Hosting.Orchestration.linux-x64/8.0.0-preview.5.24201.12/tools/dcp info
> ```
> 
> What is the output?

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/share/dotnet/packs/Aspire.Hosting.Orchestration.linux-x64/8.0.0-preview.5.24201.12/tools/dcp)
/usr/share/dotnet/packs/Aspire.Hosting.Orchestration.linux-x64/8.0.0-preview.5.24201.12/tools/dcp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/share/dotnet/packs/Aspire.Hosting.Orchestration.linux-x64/8.0.0-preview.5.24201.12/tools/dcp)

**Comment by davidfowl** [comment]
@danegsta you were looking a this right?

**Comment by danegsta** [comment]
We have a fix for this in the upcoming Preview 6 release. We accidentally prepared a build of the orchestrator on a machine with a newer glibc version, which meant that it couldn’t run on older LTS Linux distros (which unfortunately includes the distro code spaces uses). For preview 6 we updated our build pipeline to ensure we’re building with a glibc version compatible with older LTS distros such as Debian Bullseye or Ubuntu 20.04.

**Comment by DamianEdwards** [comment]
Can we close this given it's done?

**Comment by SalomonHenke** [comment]
sure @DamianEdwards ill reattempt codespace once preview 6 is available.
