### ISSUE TITLE
How can I add project without endpoints with Dapr sidecar?

### ISSUE THREAD

**Issue by dusan-tkac-bhp** [dotnet/aspire#3687]
Hello!

This used to work in preview 4 but stopped in preview 5.

I have a project which does not have any endpoints. 
It uses SDK to monitor storage queue (no Dapr bindings), it doesn't use any Dapr components, it just uses Dapr ActorProxy to invoke methods on actor instances.
Actors are hosted by a different project.

I can run this project with Dapr sidecar from command line from within project's directory like this (no app port):
`dapr run --app-id cloud-runs-controller -- dotnet run`

In preview 5, when I add the project to Aspire host, its Dapr sidecar fails to start with error

```
Failed to create resource package-event-processor-dapr-cli
System.InvalidOperationException: The endpoint `http` is not allocated for the resource `package-event-processor`.
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_AllocatedEndpoint() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 96
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_Host() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 78
   at Aspire.Hosting.Dapr.DaprDistributedApplicationLifecycleHook.<>c__DisplayClass6_1.<BeforeStartAsync>b__9(IList`1 updatedArgs) in /_/src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs:line 194
   at Aspire.Hosting.ApplicationModel.CommandLineArgsCallbackAnnotation.<>c__DisplayClass1_0.<.ctor>b__0(CommandLineArgsCallbackContext c) in /_/src/Aspire.Hosting/ApplicationModel/CommandLineArgsCallbackAnnotation.cs:line 32
   at Aspire.Hosting.Dcp.ApplicationExecutor.CreateExecutableAsync(AppResource er, ILogger resourceLogger, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 1194
   at Aspire.Hosting.Dcp.ApplicationExecutor.<CreateExecutablesAsync>g__CreateExecutableAsyncCore|53_0(AppResource cr, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 1134
```

Code that adds the project to Apire host:

``` CSharp
builder.AddProject<Projects.PackageEventProcessor>("package-event-processor")
    .WithDaprSidecar(new DaprSidecarOptions
    {
        AppId = "cloud-runs-controller",
        ResourcesPaths = ImmutableHashSet.Create(@"..\resources"), // technically not needed

        // following is ok for local development with minimal logging
        EnableApiLogging = false,
        EnableAppHealthCheck = false,
        EnableProfiling = false,
        LogLevel = "warn",
        AppHealthProbeInterval = 60,
    });
```

**Comment by davidfowl** [comment]
This no longer works, and I'm not sure you can work around it without adding an endpoint to your application called http.

**Comment by dusan-tkac-bhp** [comment]
Thank you! 

I've added http endpoint to the app for now.

**Comment by oising** [comment]
Please fix :)

**Comment by davidfowl** [comment]
PRs welcome!

**Comment by oising** [comment]
> PRs welcome!

I know. I send some quite large ones your way :) I only have so much time!

**Comment by davidfowl** [comment]
If somebody can contribute a reasonable fix in the new day we may consider it. This isn't in the 9.0 milestone and isn't critical. You can see the list of work by filtering by the 9.0 milestone in the issue tracker.

**Comment by oising** [comment]
> Is the idea that services shouldn't necessarily need to expose http endpoints just to be managed by aspire & dapr?

Apps that only use output bindings or only publish to pubsub don't need to expose a http endpoint. This bug forces them to do so. This has all sorts of secondary and undesirable effects, like if you're sharing a binding that uses direction of "input, output" and want to use app A to publish and app B to listen to a binding, both apps will be considered listeners and your logs will fill with 404 errors. Additionally, if you've supplied a static consumer group, both apps will be considered competing consumers and you'll lose 50% of your messages.

**Comment by oising** [comment]
I'm going to tackle this today -- @davidfowl

**Comment by oising** [comment]
PR sent.
