### ISSUE TITLE
Errors running Aspire on Ubuntu 24.04

### ISSUE THREAD

**Issue by wgrs** [dotnet/aspire#3859]
Following the instructions from [https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?tabs=visual-studio](url)

This is the error message:
```
warn: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[8]
      The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.0-preview.5.24201.12+1b627b7d5d399d4f9118366e7611e11e56de4554
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: /home/greg/MyDev/Sandbox/AspireSample/AspireSample.AppHost
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: Container runtime 'docker' was found but appears to be unhealthy. The error from the container runtime check was Cannot connect to the Docker daemon at unix:///home/greg/.docker/desktop/docker.sock. Is the docker daemon running?.
         at Aspire.Hosting.Dcp.DcpDependencyCheck.EnsureDcpContainerRuntime(DcpInfo dcpInfo) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 199
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 99
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.AggregateException: One or more errors occurred. (Container runtime 'docker' was found but appears to be unhealthy. The error from the container runtime check was Cannot connect to the Docker daemon at unix:///home/greg/.docker/desktop/docker.sock. Is the docker daemon running?.)
 ---> Aspire.Hosting.DistributedApplicationException: Container runtime 'docker' was found but appears to be unhealthy. The error from the container runtime check was Cannot connect to the Docker daemon at unix:///home/greg/.docker/desktop/docker.sock. Is the docker daemon running?.
   at Aspire.Hosting.Dcp.DcpDependencyCheck.EnsureDcpContainerRuntime(DcpInfo dcpInfo) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 199
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 99
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
   at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 102
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 110
   at Program.<Main>$(String[] args) in /home/greg/MyDev/Sandbox/AspireSample/AspireSample.AppHost/Program.cs:line 11
```

**Comment by asimmon** [comment]
This is an ASP.NET Core error (not directly related to Aspire). After installing the .NET SDK, you must (at least once) trust the self-signed localhost certificate that will be used for HTTPS during development.

You can follow the official instructions here: https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-8.0&tabs=visual-studio%2Clinux-ubuntu#trust-https-certificate-on-linux

**Comment by asimmon** [comment]
Also, it seems like you have installed Docker but the daemon wasn't running. Your Docker instance must be up and running so that Aspire can start containers.

**Comment by asimmon** [comment]
Docker must be up and running

**Comment by timheuer** [comment]
We have seen this a bit in a few cases, as @asimmon notes, where the daemon is actually not running, but also in some cases where Docker has gone into different types of power-saver modes (mostly seeing this on Windows).  @wgrs can you confirm docker is running? eg. running `docker ps -a` or other `docker ps` commands?

**Comment by wgrs** [comment]
Hey Tim - seems docker desktop wont  run.

**Comment by wgrs** [comment]
When I run systemctl status docker, I get the message above - but when I run the Aspire AppHost i get 

Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: Container runtime 'docker' was found but appears to be unhealthy. The error from the container runtime check was Cannot connect to the Docker daemon at unix:///home/greg/.docker/desktop/docker.sock. Is the docker daemon running?.

**Comment by timheuer** [comment]
@danegsta any ideas on the Docker error here?

**Comment by danegsta** [comment]
@wgrs from that output, it looks like you may have both Docker Desktop for Linux installed as well as Docker CE (the open source community edition version), hence the two different sockets. Somehow the terminal is seeing the environment config for Docker CE, but however you’re running Aspire is seeing the environment config for Docker Desktop (which may not be running, hence the error).

Are you using a terminal or an IDE to run Aspire?

**Comment by wgrs** [comment]
I'm running dotnet run from terminal

**Comment by danegsta** [comment]
Aspire uses the Docker CLI to run commands, rather than communicating with a Docker socket, so any commands we run will honor the environment configuration Aspire was launched with. So if you were to run a Docker command such as `docker info` from the same terminal window, I would expect it to run with the same socket settings (and report a similar error if the socket isn’t responding). Can you share the output of running `docker info` (double check for any information in the output you’d like to redact; it’s fairly innocuous, but will include file paths to things like your docker socket)? That will indicate what settings Docker is using from the command line by default.

**Comment by wgrs** [comment]
@danegsta 

docker info is just hanging. So, I will completely nuke docker and do a fresh install of docker as per their docs.

**Comment by danegsta** [comment]
Also, try running `echo $DOCKER_HOST` to see what value it reports and running `docker context ls` to see if you have multiple contexts configured. If you have multiple contexts and one is referencing the working socket, you can make that the default with `docker context use <context-name>`. If you don’t have a context with the correct socket, you can try running aspire with DOCKER_HOST=/run/docker.sock dotnet run …` to force Docker to use the good socket and see if that works to run without error. If it does, you can create a new context to point to the good socket and make Docker use that: https://docs.docker.com/engine/context/working-with-contexts/

**Comment by wgrs** [comment]
@danegsta 

docker info
Client: Docker Engine - Community
 Version:    26.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.27
    Path:     /usr/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /usr/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.6.3
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
ERROR: Cannot connect to the Docker daemon at unix:///home/greg/.docker/desktop/docker.sock. Is the docker daemon running?
errors pretty printing info

**Comment by wgrs** [comment]
@danegsta 

echo $DOCKER_HOST returns a blank line

**Comment by danegsta** [comment]
@wgrs `docker context use default` should hopefully get you working.

**Comment by danegsta** [comment]
That looks like the Docker CE context which seems to be working based on your systemctl output.

**Comment by wgrs** [comment]
I started docker desktop : systemctl --user start docker-desktop

ran the Aspire Starter .... same error - 

dotnet run
Building...
/home/greg/MyDev/Sandbox/AspireSample/AspireSample.ServiceDefaults/AspireSample.ServiceDefaults.csproj : warning NU1902: Package 'OpenTelemetry.Instrumentation.AspNetCore' 1.7.1 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-vh2m-22xx-q94f [/home/greg/MyDev/Sandbox/AspireSample/AspireSample.AppHost/AspireSample.AppHost.csproj]
/home/greg/MyDev/Sandbox/AspireSample/AspireSample.ServiceDefaults/AspireSample.ServiceDefaults.csproj : warning NU1902: Package 'OpenTelemetry.Instrumentation.Http' 1.7.1 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-vh2m-22xx-q94f [/home/greg/MyDev/Sandbox/AspireSample/AspireSample.AppHost/AspireSample.AppHost.csproj]
/home/greg/MyDev/Sandbox/AspireSample/AspireSample.ServiceDefaults/AspireSample.ServiceDefaults.csproj : warning NU1902: Package 'OpenTelemetry.Instrumentation.AspNetCore' 1.7.1 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-vh2m-22xx-q94f
/home/greg/MyDev/Sandbox/AspireSample/AspireSample.ServiceDefaults/AspireSample.ServiceDefaults.csproj : warning NU1902: Package 'OpenTelemetry.Instrumentation.Http' 1.7.1 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-vh2m-22xx-q94f
warn: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[8]
      The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.0-preview.5.24201.12+1b627b7d5d399d4f9118366e7611e11e56de4554
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: /home/greg/MyDev/Sandbox/AspireSample/AspireSample.AppHost
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: Application orchestrator dependency check had an unexpected error System.TimeoutException: The operation has timed out.
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 78.
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 105
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.AggregateException: One or more errors occurred. (Application orchestrator dependency check had an unexpected error System.TimeoutException: The operation has timed out.
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 78.)
 ---> Aspire.Hosting.DistributedApplicationException: Application orchestrator dependency check had an unexpected error System.TimeoutException: The operation has timed out.
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 78.
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 105
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
   at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 102
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 110
   at Program.<Main>$(String[] args) in /home/greg/MyDev/Sandbox/AspireSample/AspireSample.AppHost/Program.cs:line 11

**Comment by wgrs** [comment]
@timheuer @danegsta 

Just tried to spin up the dev containers tutorial - when running the "open in container" command in vscode, the "Starting Docker" dialog opens and just hangs. No timeouts, no warnings or errors.

**Comment by timheuer** [comment]
Did you install the Aspire workload -- the latest error isn't showing the 'docker unhealthy' anymore but a diff dependency check.

What is the output of `dotnet --info` and `dotnet workload list`

**Comment by wgrs** [comment]
dotnet workload list

Installed Workload Id      Manifest Version                      Installation Source
------------------------------------------------------------------------------------
aspire                     8.0.0-preview.5.24201.12/8.0.100      SDK 8.0.100        

Use `dotnet workload search` to find additional workloads to install.

Updates are available for the following workload(s): aspire. Run `dotnet workload update` to get the latest.

dotnet --info
.NET SDK:
 Version:           8.0.104
 Commit:            034f91fcc0
 Workload version:  8.0.100-manifests.2f72bdd4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  24.04
 OS Platform: Linux
 RID:         ubuntu.24.04-x64
 Base Path:   /usr/lib/dotnet/sdk/8.0.104/

.NET workloads installed:
 Workload version: 8.0.100-manifests.2f72bdd4
 [aspire]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.0-preview.5.24201.12/8.0.100
   Manifest Path:       /home/greg/.dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.0.0-preview.5.24201.12/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.104 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by wgrs** [comment]
@timheuer @danegsta 

This is the core issue:

fail: Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0]
      could not create the container	{"Container": {"name":"cache"}, "Reconciliation": 2, "error": "CreateContainer command returned error code 1 Stdout: '' Stderr: 'Cannot connect to the Docker daemon at unix:///home/greg/.docker/desktop/docker.sock. Is the docker daemon running?\n'"}
fail: Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0]
      container has failed to start	{"Container": {"name":"cache"}, "Reconciliation": 4, "error": "CreateContainer command returned error code 1 Stdout: '' Stderr: 'Cannot connect to the Docker daemon at unix:///home/greg/.docker/desktop/docker.sock. Is the docker daemon running?\n'"}

---

Is the dotnet run cmd is looking at the wrong path for the daemon ??? 

**_Cannot connect to the Docker daemon at unix:///home/greg/.docker/desktop/docker.sock_**

**Comment by timheuer** [comment]
@danegsta the last exception no longer looks like the 'docker is unhealthy' one but another dependency check. I thought maybe the workload wasn't installed but looks like p5 is there.

**Comment by jiimaho** [comment]
Any updates on this? Getting the same error on MacOS

**Comment by davidfowl** [comment]
Can you share the exact error you’re hitting ?
