### ISSUE TITLE
The antiforgery token could not be decrypted - Using Aspir8 to deploy AspireWithDapr

### ISSUE THREAD

**Issue by sclarke81** [dotnet/aspire#3864]
I've tried to deploy the AspireWithDapr sample from aspire-samples to Kubernetes (Rancher Desktop) using Aspir8. However, I get the following exception when accessing the weather page on the AspireWithDapr.Web project.

```
 ---> System.Security.Cryptography.CryptographicException: The key {72504f72-4162-4cf1-8ab7-7cb03fc6eb5d} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

I was torn on where to post this issue, so apologies if this isn't the right place. I'm new to Aspire and Dapr but was hoping that starting with the sample would work out of the box - that is to say I could be missing something obvious so I'm open to any help/feedback.

**Comment by davidfowl** [comment]
How many replicas of your application are you running?

**Comment by sclarke81** [comment]
> How many replicas of your application are you running?

Just one

**Comment by davidfowl** [comment]
This likely happens because your app restarts, and the data protections keys change and your browser still has a cookie with the old token.

**Comment by andreaskromann** [comment]
You can get this error even after clearing cookies. It throws an exception in the CircuitHost and closes the connection. I had to clear session storage in the browser to make it work again. There is some value stored in there as well.

**Comment by danmoseley** [comment]
@amcasey any thoughts given this is DP?

**Comment by amcasey** [comment]
As David mentioned above, if you're running your app in a container and the data protection keys are stored in a folder that isn't mounted from the host, then they won't persist across container restarts.  But maybe you had a more specific question, @danmoseley?

If you're wondering why the browser is holding onto state, that would probably be a question for an Anti-forgery expert.

**Comment by gabynevada** [comment]
> As David mentioned above, if you're running your app in a container and the data protection keys are stored in a folder that isn't mounted from the host, then they won't persist across container restarts. But maybe you had a more specific question, @danmoseley?
> 
> If you're wondering why the browser is holding onto state, that would probably be a question for an Anti-forgery expert.

@amcasey we're using Github Codespaces for our development environments and get this error whenever we create a new container and access the Dashboard. Any guidance on what we can change to avoid this?

**Comment by amcasey** [comment]
@gabynevada Are you creating ephemeral containers in a persistent Codespace or is the Codespace itself ephemeral?

**Comment by amcasey** [comment]
If you want sessions to continue across distinct Codespaces (it's not immediately obvious to me why this would be necessary), you'll need to establish persistent storage outside the Codespaces.  Azure seems like an obvious candidate.

**Comment by yordis** [comment]
Copied from my dotfiles: 
https://github.com/yordis/.dotfiles/blob/bde0e2c91cad3f25fdd7d3b4b076d40fa8389b6f/roles/workspace/files/docker/docker-compose.yml#L30-L45

```yaml
services:
  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    restart: unless-stopped
    labels:
      - dev.orbstack.http-port=18888
    ports:
      - 4317:18889 # http2
      - 4318:18890 # http
    profiles:
      - o11y
      - aspire
    environment:
      - ASPIRE_ALLOW_UNSECURED_TRANSPORT=true
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
      - DOTNET_DASHBOARD_OTLP_HTTP_ENDPOINT_URL=http://localhost:18890
```

I keep getting this issue while visiting the Metrics page:

```
info: Aspire.Dashboard.DashboardWebApplication[0]
      Aspire version: 9.0.0+01ed51919f8df692ececce51048a140615dc759d
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/home/app/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {c360959a-1f0f-424a-888c-030f6b5bc6cf} may be persisted to storage in unencrypted form.
info: Aspire.Dashboard.DashboardWebApplication[0]
      Now listening on: http://[::]:18888
info: Aspire.Dashboard.DashboardWebApplication[0]
      OTLP/gRPC listening on: http://[::]:18889
info: Aspire.Dashboard.DashboardWebApplication[0]
      OTLP/HTTP listening on: http://localhost:18890
warn: Aspire.Dashboard.DashboardWebApplication[0]
      OTLP server is unsecured. Untrusted apps can send telemetry to the dashboard. For more information, visit https://go.microsoft.com/fwlink/?linkid=2267030
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: The key {c8b6a9a8-9d40-4c5b-aefc-a191bfde1a2f} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
      System.Security.Cryptography.CryptographicException: The key {c8b6a9a8-9d40-4c5b-aefc-a191bfde1a2f} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at Aspire.Dashboard.Model.BrowserStorage.BrowserStorageBase.GetAsync[T](String key) in /_/src/Aspire.Dashboard/Model/BrowserStorage/BrowserStorageBase.cs:line 19
         at Aspire.Dashboard.Components.Pages.PageExtensions.InitializeViewModelAsync[TViewModel,TSerializableViewModel](IPageWithSessionAndUrlState`2 page) in /_/src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:line 97
         at Aspire.Dashboard.Components.Pages.Metrics.OnParametersSetAsync() in /_/src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs:line 106
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'ZcrGspu0Hvx71V4FVeHjcMnUGGgHMPxfSBO3fKLo7WY'.
      System.Security.Cryptography.CryptographicException: The key {c8b6a9a8-9d40-4c5b-aefc-a191bfde1a2f} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at Aspire.Dashboard.Model.BrowserStorage.BrowserStorageBase.GetAsync[T](String key) in /_/src/Aspire.Dashboard/Model/BrowserStorage/BrowserStorageBase.cs:line 19
         at Aspire.Dashboard.Components.Pages.PageExtensions.InitializeViewModelAsync[TViewModel,TSerializableViewModel](IPageWithSessionAndUrlState`2 page) in /_/src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:line 97
         at Aspire.Dashboard.Components.Pages.Metrics.OnParametersSetAsync() in /_/src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs:line 106
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

```

**Comment by yordis** [comment]
I just founded out how to get rid of that error: clean up the browser localStorage where a Key is saved that caused mismatching
