### ISSUE TITLE
[WebToolsE2E][Aspire] Creating web app with MS Identity auth and aspire checked, F5 failed with 'This service descriptor is keyed. Your service provider may not support keyed services.'

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/aspire#3880]
**REGRESSION INFO**: Also reproduces on Aspire 8.0 P4 and Aspire 8.0 P5

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU 
2. Install VS 17.10.0 Preview 5 FB, Preview channel

    - Web workload
    - Includes Aspire 8.0.0-preview.6.24214.1
    - Includes .NET SDK 8.0.300-preview.24203.14 and runtime 8.0.2
    - Apply dotnet-tools feed

**REPRO STEPS**
1. New > Project > ASP.NET Core Web App > .NET 8.0 > Microsoft identity platform > Check 'Enlist in .NET Aspire orchestration' > Create
2. In the popped window, select 'Tenants' to 'Microsoft' > Create a new application > Next > Next > Finish
3. F5

**ACTUAL**
F5 failed with exception: This service descriptor is keyed. Your service provider may not support keyed services.
![image](https://github.com/Azure/azure-dev/assets/78580199/7dd77752-eb27-499f-b6b1-be35f232047e)

System.InvalidOperationException
  HResult=0x80131509
  Message=This service descriptor is keyed. Your service provider may not support keyed services.
  Source=Microsoft.Extensions.DependencyInjection.Abstractions
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType()
   at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c.<AddMicrosoftIdentityWebAppInternal>b__5_0(ServiceDescriptor s)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.AddMicrosoftIdentityWebAppInternal(AuthenticationBuilder builder, Action`1 configureMicrosoftIdentityOptions, Action`1 configureCookieAuthenticationOptions, String openIdConnectScheme, String cookieScheme, Boolean subscribeToOpenIdConnectMiddlewareDiagnosticsEvents, String displayName)
   at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.AddMicrosoftIdentityWebAppWithConfiguration(AuthenticationBuilder builder, Action`1 configureMicrosoftIdentityOptions, Action`1 configureCookieAuthenticationOptions, String openIdConnectScheme, String cookieScheme, Boolean subscribeToOpenIdConnectMiddlewareDiagnosticsEvents, String displayName, IConfigurationSection configurationSection)
   at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.AddMicrosoftIdentityWebApp(AuthenticationBuilder builder, IConfigurationSection configurationSection, String openIdConnectScheme, String cookieScheme, Boolean subscribeToOpenIdConnectMiddlewareDiagnosticsEvents, String displayName)
   at Program.<Main>$(String[] args) in C:\Users\v-elenafeng\source\repos\WebApplication9\WebApplication9\Program.cs:line 13

**EXPECTED**
Can run successfully with MSI auth + Aspire enabled.

**Comment by davidfowl** [comment]
Try updating the identity packages. This is a bug that has been fixed.

**Comment by v-elenafeng** [comment]
> Try updating the identity packages. This is a bug that has been fixed.

Thanks, after updating the identity packages I was able to run successfully.

**Comment by davidfowl** [comment]
cc @vijayrkn @BillHiebert @phenning

**Comment by vijayrkn** [comment]
@deepchoudhery - Can you please get the identity package versions updated in the identity scaffolding for this? This should just be a package update change.

**Comment by mkArtakMSFT** [comment]
Ping @deepchoudhery in case you didn't see this.

**Comment by v-elenafeng** [comment]
I'm able to repro this issue with the released VS 17.10.0.

@deepchoudhery ping you again on the packages update for msi to resolve this issue.

![image](https://github.com/dotnet/aspire/assets/78580199/a266438e-9d43-4650-b741-7a86412924ad)

**Comment by deepchoudhery** [comment]
Hi, 
Will look at this issue in my next cycle here, apologies for the delay

**Comment by v-bennettyue** [comment]
This issue not repro on Dev17.11.0, and now the identity packages shows as below:
![image](https://github.com/user-attachments/assets/0e0b9b75-4b1e-4ce1-b41f-c554e90f1781)
