### ISSUE TITLE
I cant use .AddDatabase("mysqldb"); create database

### ISSUE THREAD

**Issue by PSC-F** [dotnet/aspire#3883]
``` c#
var mysqldb = builder.AddMySql("mysql")
    // .WithPhpMyAdmin()
    .AddDatabase("mysqldb");

var apiService = builder.AddProject<Projects.ZhangPengFei_IoT_ApiService>("api-service")
    .WithReference(mysqldb)
    .WithReference(cache);
```
``` js
Server=localhost;Port=51050;User ID=root;Password=H6!V*kJF*5}Qz}+3nZu6}b;Database=mysqldb
2024-04-23T19:34:46.8846127 fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      SqlSugar.SqlSugarException: 中文提示 :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，错误信息：Couldn't connect to serverDbType="MySql";ConfigId="".
      English Message : Connection open error . Couldn't connect to serverDbType="MySql";ConfigId="" 
         at SqlSugar.Check.Exception(Boolean isException, String message, String[] args)
         at SqlSugar.AdoProvider.CheckConnection()
         at SqlSugar.DbMaintenanceProvider.IsAnySyst
```
Use platform 👍   .net8
Connector 🥇  aspire.mysqlconnector.8.0.0-preview.2.23619.3.nupkg

**Comment by PSC-F** [comment]
I fonud the mysql is not create database named "mysqldb"

**Comment by davidfowl** [comment]
That's right, it doesn't create the database see a similar issue https://github.com/dotnet/aspire/issues/1170

**Comment by PSC-F** [comment]
> That's right, it doesn't create the database see a similar issue #1170

Thanks a million，I got it 👍
