### ISSUE TITLE
Running AppHost in `Release` config fails

### ISSUE THREAD

**Issue by ptasev** [dotnet/aspire#3939]
I created the starter app from the templates. I then built and ran AppHost in `Release` configuration. When the dashboard came up I was able to see the following stack traces. It's looking for them in the bin/debug folder rather than bin/release. I have no good reason to run it in `Release` config. It works fine in `Debug` config. Preview 6 (template from Preview 5).

apiservice
```
Unhandled exception: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'Aspire.ApiService\bin\Debug\net8.0\Aspire.ApiService.exe' with working directory 'Aspire.ApiService'. The system cannot find the file specified.                 
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)                 
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)                
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()       
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)             
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

web
```
Unhandled exception: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'Aspire.Web\bin\Debug\net8.0\Aspire.Web.exe' with working directory 'Aspire.Web'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

**Comment by timheuer** [comment]
Thanks @ptasev -- this is from CLI right? (I can repro on CLI, but not in VS)

**Comment by ptasev** [comment]
I actually ran the AppHost project from Rider. I believe it simply ran the executable in the AppHost bin/release folder.

**Comment by radical** [comment]
I can reproduce this with `dotnet run -c Release`.

**Comment by radical** [comment]
This is easy to reproduce.
1. dotnet new aspire-starter -o asp0
2. cd asp0/asp0.AppHost
3. dotnet run -c Release

cc @joperezr @eerhardt @danegsta

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/aspire/pull/3961 . Tests for this are passing in https://github.com/dotnet/aspire/pull/4168/checks?check_run_id=25072734191 .

Thanks @danegsta .
