### ISSUE TITLE
Using the Jaeger container causes an error

### ISSUE THREAD

**Issue by takashiuesaka** [dotnet/aspire#4070]
I implemented the following in the Program.cs of the AppHost project. Then the dashboard looks like the image.

```
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache");

var apiService = builder.AddProject<Projects.AspireApp1_ApiService>("apiservice");

builder.AddProject<Projects.AspireApp1_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(cache)
    .WithReference(apiService);

builder.AddContainer("promethus", "prom/prometheus")
    .WithBindMount("../prometheus", "/etc/prometheus")
    .WithHttpEndpoint(9090, targetPort: 9090);

builder.AddContainer("jaeger", "jaegertracing/all-in-one")
    .WithHttpEndpoint(16686, targetPort: 16686)
    .WithHttpEndpoint(4317, targetPort: 4317);

builder.AddContainer("grafana", "grafana/grafana")
    .WithBindMount("../grafana/config", "/etc/grafana")
    .WithBindMount("../grafana/dashboards", "/var/lib/grafana/dashboards")
    .WithHttpEndpoint(3000, targetPort: 3000);

builder.Build().Run();
```

<img width="1683" alt="image" src="https://github.com/dotnet/aspire/assets/61622933/8d0216ef-7550-47a4-8090-7c51e210a598">

The container status remains 'Starting' and does not update. I noticed that using the Jaeger container causes an error.　

```
crit: Aspire.Hosting.Dcp.ApplicationExecutor[0]
      Watch task over kubernetes Endpoint resources terminated unexpectedly. Check to ensure dcpd process is running.
      System.InvalidOperationException: Sequence contains more than one matching element
         at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
         at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
         at Aspire.Hosting.ApplicationModel.EndpointReference.GetEndpointAnnotation() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 111
         at Aspire.Hosting.ApplicationModel.EndpointReference.get_EndpointAnnotation() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 18
         at Aspire.Hosting.Dcp.ApplicationExecutor.GetUrls(CustomResource resource) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 644
         at Aspire.Hosting.Dcp.ApplicationExecutor.ToSnapshot(Container container, CustomResourceSnapshot previous) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 527
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass37_0.<TryRefreshResource>b__0(CustomResourceSnapshot s) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 511
         at Aspire.Hosting.ApplicationModel.ResourceNotificationService.PublishUpdateAsync(IResource resource, String resourceId, Func`2 stateFactory) in /_/src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs:line 75
         at Aspire.Hosting.Dcp.ApplicationExecutor.TryRefreshResource(String resourceKind, String resourceName) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 507
         at Aspire.Hosting.Dcp.ApplicationExecutor.ProcessEndpointChange(WatchEventType watchEventType, Endpoint endpoint) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 474
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass32_1`1.<<WatchResourceChanges>b__10>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 291
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass32_1`1.<<WatchResourceChanges>b__10>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 285
      --- End of stack trace from previous location ---
         at Polly.ResiliencePipeline.<>c.<<ExecuteAsync>b__3_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Polly.Outcome`1.GetResultOrRethrow()
         at Polly.ResiliencePipeline.ExecuteAsync(Func`2 callback, CancellationToken cancellationToken)
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass32_0.<<WatchResourceChanges>g__WatchKubernetesResource|3>d`1.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 281
```

**Comment by davidfowl** [comment]
Hmm if you name the endpoints does it work?

**Comment by takashiuesaka** [comment]
After making the following changes to the implementation, it worked without any problems! Thank you!

```
builder.AddContainer("jaeger", "jaegertracing/all-in-one")
    .WithHttpEndpoint(16686, targetPort: 16686, name: "jaegerPortal")
    .WithHttpEndpoint(4317, targetPort: 4317, name: "jaegerEndpoint");
```

<img width="1684" alt="image" src="https://github.com/dotnet/aspire/assets/61622933/8db4fc24-7052-4feb-8c1c-b58286ff997a">

**Comment by mitchdenny** [comment]
reopening because I think we might want to address this with some changes to throw earlier with a more helpful error message.

**Comment by timheuer** [comment]
related: https://github.com/dotnet/aspire/issues/3569
