### ISSUE TITLE
Dashboard fails to start due to misconfiguration

### ISSUE THREAD

**Issue by wmeints** [dotnet/aspire#4080]
I tried running my aspire app this morning on Preview 6 and it fails to start due to a misconfiguration of the dashboard outside of my control. I'm getting the following logs:

```text
fail: Aspire.Hosting.Dashboard[0]
      Unhandled exception. System.InvalidOperationException: Missing required configuration for Frontend:AuthMode. Valid values are Unsecured, OpenIdConnect.
dbug: Aspire.Hosting.Dashboard[0]
      Failed to parse dashboard log line as JSON:    at Aspire.IConfigurationExtensions.GetEnum[T](IConfiguration configuration, String key) in /_/src/Shared/IConfigurationExtensions.cs:line 168
fail: Aspire.Hosting.Dashboard[0]
         at Aspire.IConfigurationExtensions.GetEnum[T](IConfiguration configuration, String key) in /_/src/Shared/IConfigurationExtensions.cs:line 168
dbug: Aspire.Hosting.Dashboard[0]
      Failed to parse dashboard log line as JSON:    at Aspire.Dashboard.DashboardWebApplication.LoadDashboardConfig(IConfiguration configuration) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 459
fail: Aspire.Hosting.Dashboard[0]
         at Aspire.Dashboard.DashboardWebApplication.LoadDashboardConfig(IConfiguration configuration) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 459
dbug: Aspire.Hosting.Dashboard[0]
      Failed to parse dashboard log line as JSON:    at Aspire.Dashboard.DashboardWebApplication..ctor(Action`1 configureBuilder) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 70
fail: Aspire.Hosting.Dashboard[0]
         at Aspire.Dashboard.DashboardWebApplication..ctor(Action`1 configureBuilder) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 70
dbug: Aspire.Hosting.Dashboard[0]
      Failed to parse dashboard log line as JSON:    at Program.<Main>$(String[] args) in /_/src/Aspire.Dashboard/Program.cs:line 7
fail: Aspire.Hosting.Dashboard[0]
         at Program.<Main>$(String[] args) in /_/src/Aspire.Dashboard/Program.cs:line 7
```

**Comment by wmeints** [comment]
I checked my environment. This problem was caused by a mixup in the assemblies on my system. I had a 8.1.0-preview-* build installed of the aspire workload from attempting to debug something with a nightly. I had to reinstall .NET 8 to get things back to normal.
