### ISSUE TITLE
Improve the error when dcp dependency check fails

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#4089]
This is what shows up:

```
System.InvalidOperationException: Command C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0-preview.6.24214.1\tools\dcp.exe info returned non-zero exit code -1
         at Aspire.Hosting.Dcp.Process.ProcessUtil.ProcessDisposable.DisposeAsync() in /_/src/Aspire.Hosting/Dcp/Process/ProcessUtil.cs:line 155
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.AggregateException: One or more errors occurred. (Command C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0-preview.6.24214.1\tools\dcp.exe info returned non-zero exit code -1)
 ---> System.InvalidOperationException: Command C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0-preview.6.24214.1\tools\dcp.exe info returned non-zero exit code -1
   at Aspire.Hosting.Dcp.Process.ProcessUtil.ProcessDisposable.DisposeAsync() in /_/src/Aspire.Hosting/Dcp/Process/ProcessUtil.cs:line 155
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
   at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 102
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 110
   at Program.<Main>$(String[] args) in C:\dev\git\WebQWorker\WebQWorker.AppHost\Program.cs:line 17

C:\dev\git\WebQWorker\WebQWorker.AppHost\bin\Debug\net8.0\WebQWorker.AppHost.exe (process 45384) exited with code -532462766.
```

**Comment by wwalendz-relativity** [comment]
Hello. Is there any workaround to get more significant logs? I can't get my AppHost running after upgrade to `8.0.1` from `preview`.

**Comment by davidfowl** [comment]
Did you update the workload as well?

**Comment by wwalendz-relativity** [comment]
Yes I re-installed ".NET Aspire SDK" component from VS Installer yesterday. Without luck. 
![image](https://github.com/dotnet/aspire/assets/80332029/0c6b2ff8-3027-4794-88fd-6b0fa6d4dab6)

**Comment by wwalendz-relativity** [comment]
Can it be related to multiple "Installation Source"? .NET SDK and VS Component 🤔

**Comment by kuleshov-aleksei** [comment]
Hello! I just encountered the same exact bug

I have created a fresh new Aspire project based on [https://github.com/dotnet/aspire-samples/samples/AspireWithJavaScript](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithJavaScript) example. And started migrating existing application to it. Two days were just mind blowing (Aspire is really awesome!) and after some time Aspire just stopped working (after reboot I suppose)

I have stumbled at this issue and after reading
> Suddenly, it started working today

I decided to reboot pc. And now everything works just fine

Here is some data that I collected, hope it can help

```
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.1+a6e341ebbf956bbcec0dda304109815fcbae70c9
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: D:\Coding\DiscordBot\FailsafeBot\source\FailsafeBot\Failsafe.AppHost
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.InvalidOperationException: Command C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0\tools\dcp.exe info returned non-zero exit code -1
         at Aspire.Hosting.Dcp.Process.ProcessUtil.ProcessDisposable.DisposeAsync() in /_/src/Aspire.Hosting/Dcp/Process/ProcessUtil.cs:line 155
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

`ServiceDefaults` unchanged, `AppHost` source (nothing special):
```csharp
using Aspire.Hosting;

IDistributedApplicationBuilder builder = DistributedApplication.CreateBuilder(args);
IResourceBuilder<ParameterResource> bungieApiKey = builder.AddParameter("bungie-api-key", secret: true);

IResourceBuilder<ProjectResource> weatherApi = builder.AddProject<Projects.Failsafe_MinimalApi>("weatherapi")
    .WithExternalHttpEndpoints();

builder.AddNpmApp("vue", "../Failsafe.Web")
    .WithReference(weatherApi)
    .WithHttpEndpoint(port: 63497, env: "PORT")
    .WithEnvironment("VITE_BUNGIE_URL", "https://bungie.net/")
    .WithEnvironment("VITE_BUNGIE_API_KEY", bungieApiKey)
    .WithExternalHttpEndpoints()
    .PublishAsDockerFile();

await builder.Build().RunAsync();
```

`dotnet --info`:
```
.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.5273bb1c
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.34707.107, VS 17.10.35004.147
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  6.0.110 [C:\Program Files\dotnet\sdk]
  8.0.200 [C:\Program Files\dotnet\sdk]
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by davidfowl** [comment]
Likely your docker desktop was not running. 

@karolz-ms or @danegsta can you take a look at this? We just need to surface the error from the dcp dependency check logic and log it as an error.

**Comment by danegsta** [comment]
There's a fix for this in Aspire main that's pending release in 8.1; there was a bug in the info check that could cause it to exit with an error code instead of returning the full error message from the check, but @davidfowl is correct that the error is indicating that Aspire couldn't find a healthy Docker (or Podman) instance.

Particularly with Docker Desktop, it's not uncommon for it to get stuck in resource saver mode after a machine wakes from sleep. When that happens, it won't respond to any CLI commands until you open the Docker Desktop UI to wake it up or restart your machine.

**Comment by joperezr** [comment]
This is now done with the new ingestion of DCP. Closing as such. Will be fixed in 8.1.

**Comment by kuleshov-aleksei** [comment]
Sorry for commenting in closed issue, I want to clarify: DCP wants a healty Docker Desktop instance even if it running without containers?

I have weird setup with both podman desktop and docker desktop, but there is no containers nor in `docker ps` nor in `podman ps`. I suppose everything is running without containerization (I do not need it at this point, so it did not bother me)

Here is process tree:

![image](https://github.com/dotnet/aspire/assets/10367317/a8220c65-0628-472e-a981-2470f38a4b7e)

![image](https://github.com/dotnet/aspire/assets/10367317/a96d7331-beb6-4b6e-98d4-c065d1f1cd42)

![image](https://github.com/dotnet/aspire/assets/10367317/35c2df32-195a-4b10-a529-a1736ffdb425)

**Comment by danegsta** [comment]
No worries; with the fix that will be shipping in the next release, Aspire won't block a project from running if Docker or Podman aren't installed/running, but no containers are used. The main issue is that the dependency check could return an error code, which was triggering an exception path. We had a code path that could accidentally run the Docker health check twice when it timed out due to the resource saver bug making it unresponsive, but that second check would cause it to exceed an overall command timeout that threw an error code.

As for using containers in Aspire, I've got both Docker Desktop and Podman Desktop installed on all my machines as well, since I always want to make sure container features are working as expected in both. Aspire makes two checks, the first to determine if a runtime is installed (can it find docker.exe or podman.exe on the system path), and a second to determine whether either of them are healthy (with a timeout to respond). If you do end up running any containers via the AppHost, we'll default to Docker if we find both runtimes installed and healthy, but you can override the behavior with an environment variable Setting `DOTNET_ASPIRE_CONTAINER_RUNTIME=podman` will force Aspire to use the Podman runtime.

**Comment by davidfowl** [comment]
This isn't done. We want to print the output from that command instead of just the status code 😄

**Comment by danegsta** [comment]
In current main the exception thrown includes the status check error message:

```
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.1.0-dev
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: C:\Users\danegsta\source\repos\aspire\main\playground\TestShop\AppHost
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      Aspire.Hosting.DistributedApplicationException: Container runtime 'docker' was found but appears to be unhealthy. The error from the container runtime check was error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.45/containers/json?limit=1": open //./pipe/docker_engine: The system cannot find the file specified..
         at Aspire.Hosting.Dcp.DcpDependencyCheck.EnsureDcpContainerRuntime(DcpInfo dcpInfo) in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\Dcp\DcpDependencyCheck.cs:line 199
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\Dcp\DcpDependencyCheck.cs:line 99
         at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\Dcp\DcpDependencyCheck.cs:line 117
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\Dcp\DcpHostService.cs:line 67
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Unhandled exception. System.AggregateException: One or more errors occurred. (Container runtime 'docker' was found but appears to be unhealthy. The error from the container runtime check was error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.45/containers/json?limit=1": open //./pipe/docker_engine: The system cannot find the file specified..)
 ---> Aspire.Hosting.DistributedApplicationException: Container runtime 'docker' was found but appears to be unhealthy. The error from the container runtime check was error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.45/containers/json?limit=1": open //./pipe/docker_engine: The system cannot find the file specified..
   at Aspire.Hosting.Dcp.DcpDependencyCheck.EnsureDcpContainerRuntime(DcpInfo dcpInfo) in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\Dcp\DcpDependencyCheck.cs:line 199
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\Dcp\DcpDependencyCheck.cs:line 99
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\Dcp\DcpDependencyCheck.cs:line 117
   at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\Dcp\DcpHostService.cs:line 67
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\DistributedApplication.cs:line 310
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in C:\Users\danegsta\source\repos\aspire\main\src\Aspire.Hosting\DistributedApplication.cs:line 338
   at Program.<Main>$(String[] args) in C:\Users\danegsta\source\repos\aspire\main\playground\TestShop\AppHost\Program.cs:line 50
```

**Comment by davidfowl** [comment]
I stand corrected!
