### ISSUE TITLE
Property DashboardPath: The path to the Aspire Dashboard binaries is missing

### ISSUE THREAD

**Issue by mmisztal1980** [dotnet/aspire#4193]
I'm attempting to add Aspire to my OSS project, to see if it can help with some productivity issues I'm facing.
- I've added the Aspire .AppHost & .ServiceDefaults project(s) to the solution.

My immediate observations are:
- Projects namespace is being generated but only contains generated code for the .AppHost project . I have no idea how to ensure other executables to be strongly typed from that namespace.
- I've had to resort to the non-generic `AddProject` method:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.AddProject(
  name: "hive-microservices-demo-api",
  projectPath: @"../Hive.MicroServices.Demo.Api/Hive.MicroServices.Demo.Api.csproj");

builder.Build().Run();
```

- The .AppHost doesn't start.

```
/Users/mmisztal/Checkout/@cloud-tek/hive/hive.microservices/demo/Hive.MicroServices.Demo.Aspire.AppHost/bin/Debug/net8.0/Hive.MicroServices.Demo.Aspire.AppHost
Unhandled exception. System.AggregateException: One or more errors occurred. (Property DashboardPath: The path to the Aspire Dashboard binaries is missing.)
 ---> Microsoft.Extensions.Options.OptionsValidationException: Property DashboardPath: The path to the Aspire Dashboard binaries is missing.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Aspire.Hosting.Dashboard.ConfigureDefaultDashboardOptions.Configure(DashboardOptions options) in /_/src/Aspire.Hosting/Dashboard/DashboardOptions.cs:line 24
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Aspire.Hosting.Dashboard.DashboardLifecycleHook.AddDashboardResource(DistributedApplicationModel model) in /_/src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs:line 77
   at Aspire.Hosting.Dashboard.DashboardLifecycleHook.BeforeStartAsync(DistributedApplicationModel model, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs:line 46
   at Aspire.Hosting.DistributedApplication.ExecuteBeforeStartHooksAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 353
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 309
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 338
   at Program.<Main>$(String[] args) in /Users/mmisztal/Checkout/@cloud-tek/hive/hive.microservices/demo/Hive.MicroServices.Demo.Aspire.AppHost/Program.cs:line 7

Process finished with exit code 134.
```

I realize it's preview, but it doesn't seem like I'm trying to achieve rocket-science here. 
Can anyone explain what am I missing?

**Comment by davidfowl** [comment]
I'd suggest using the project templates. I'm not sure how you made the apphost project, but it looks like its missing all of the required settings from launchSettings to make it run.

> Projects namespace is being generated but only contains generated code for the .AppHost project . I have no idea how to ensure other executables to be strongly typed from that namespace.

Add a project reference to the AppHost project and it will generate the strongly typed references.

The documentation has a tutorial for how to add aspire to your existing application:

https://learn.microsoft.com/en-us/dotnet/aspire/get-started/add-aspire-existing-app
