### ISSUE TITLE
[Error] Using Standalone Dashboard with Otlp ApiKey

### ISSUE THREAD

**Issue by niltor** [dotnet/aspire#4252]
I use Standalone Dashboard like:
```docker
docker run --rm -it -p 18888:18888 -p 4317:18889 -d --name aspire-dashboard -e DOTNET_DASHBOARD_CONFIG_FILE_PATH='/etc/aspire/config.json' -v \config\dev\aspire:/etc/aspire mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
``` 

And my config.json is:

```json
{
  "Dashboard": {
    "TelemetryLimits": {
      "MaxLogCount": 1000,
      "MaxTraceCount": 1000,
      "MaxMetricsCount": 1000
    },
    "Frontend": {
      "AuthMode": "BrowserToken",
      "BrowserToken": "7A3B9C5D1E6F8G2H4I0J"
    },
    "Otlp": {
      "AuthMode": "ApiKey",
      "PrimaryApiKey": "c4f1e9a1d6b78f4c5a2d9f1b3e9c7d8f",
      "SecondaryApiKey": "c4f1e9a1d6b78f4c5a2d9f1b3e9c7d8f"
    },
    "ResourceServiceClient": {}
  }
}
```

I can use Dashboard FrontEnd  BrowserToken to login,
then I get error from docker logs:

```logs
2024-05-22 15:59:25 info: Aspire.Dashboard.DashboardWebApplication[0]
2024-05-22 15:59:25       Aspire version: 8.0.0+7d0dde4108a2640ded4f9787fe28ce0f12d83633
2024-05-22 15:59:25 warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
2024-05-22 15:59:25       Storing keys in a directory '/home/app/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
2024-05-22 15:59:25 warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
2024-05-22 15:59:25       No XML encryptor configured. Key {af13dc63-1a4b-4a09-9300-92260c7d6324} may be persisted to storage in unencrypted form.
2024-05-22 15:59:25 info: Aspire.Dashboard.DashboardWebApplication[0]
2024-05-22 15:59:25       Now listening on: http://0.0.0.0:18888
2024-05-22 15:59:25 info: Aspire.Dashboard.DashboardWebApplication[0]
2024-05-22 15:59:25       Login to the dashboard at http://0.0.0.0:18888/login?t=7A3B9C5D1E6F8G2H4I0J
2024-05-22 15:59:25 info: Aspire.Dashboard.DashboardWebApplication[0]
2024-05-22 15:59:25       OTLP server running at: http://0.0.0.0:18889
2024-05-22 15:59:31 fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
2024-05-22 15:59:31       An exception was thrown while deserializing the token.
2024-05-22 15:59:31       Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
2024-05-22 15:59:31        ---> System.Security.Cryptography.CryptographicException: The key {28469378-5161-43b7-b328-58121374e4a9} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
2024-05-22 15:59:31          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
2024-05-22 15:59:31          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
2024-05-22 15:59:31          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
2024-05-22 15:59:31          --- End of inner exception stack trace ---
2024-05-22 15:59:31          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
2024-05-22 15:59:31          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
2024-05-22 15:59:34 warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
2024-05-22 15:59:34       Unhandled exception rendering component: The key {0309fca1-4c5d-4b52-8d36-b2646cdb261f} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
2024-05-22 15:59:34       System.Security.Cryptography.CryptographicException: The key {0309fca1-4c5d-4b52-8d36-b2646cdb261f} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
2024-05-22 15:59:34          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
2024-05-22 15:59:34          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
2024-05-22 15:59:34          at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
2024-05-22 15:59:34          at Aspire.Dashboard.Components.Pages.PageExtensions.InitializeViewModelAsync[TViewModel,TSerializableViewModel](IPageWithSessionAndUrlState`2 page) in /_/src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:line 72
2024-05-22 15:59:34          at Aspire.Dashboard.Components.Pages.StructuredLogs.OnParametersSetAsync() in /_/src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs:line 133
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-05-22 15:59:34 fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
2024-05-22 15:59:34       Unhandled exception in circuit 'Fj0egR20uXGNQIl42Ro_YrE1AvFeDivDdmEMUAp2TSA'.
2024-05-22 15:59:34       System.Security.Cryptography.CryptographicException: The key {0309fca1-4c5d-4b52-8d36-b2646cdb261f} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
2024-05-22 15:59:34          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
2024-05-22 15:59:34          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
2024-05-22 15:59:34          at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
2024-05-22 15:59:34          at Aspire.Dashboard.Components.Pages.PageExtensions.InitializeViewModelAsync[TViewModel,TSerializableViewModel](IPageWithSessionAndUrlState`2 page) in /_/src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:line 72
2024-05-22 15:59:34          at Aspire.Dashboard.Components.Pages.StructuredLogs.OnParametersSetAsync() in /_/src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs:line 133
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
2024-05-22 15:59:34          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

```

![image](https://github.com/dotnet/aspire/assets/8222201/ac488e36-a510-415a-9a21-3e8cfb841737)

**Comment by mitchdenny** [comment]
You you clear your aspnet login cookies? I think what is happening here is that data protection is signing the cookie, but when you restart the container it looses those keys and can't decrypt the cookie.

If you look at the earlier logs there is a hint:

```
024-05-22 15:59:25 info: Aspire.Dashboard.DashboardWebApplication[0]
2024-05-22 15:59:25       Aspire version: 8.0.0+7d0dde4108a2640ded4f9787fe28ce0f12d83633
2024-05-22 15:59:25 warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
2024-05-22 15:59:25       Storing keys in a directory '/home/app/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
```

You could use a host mounted volume to persist the keys that are stored in `/home/app/.aspnet/DataProtection-Keys`

**Comment by niltor** [comment]
@mitchdenny 
Indeed, I started the container without setting the apiKey at the beginning, and then restarted the container after setting it.
I don't clear login cookies, After restart the container, I use the BrowserToken to login in.

I tried it again today and no more errors.It should be the cookie issue you mentioned.
