### ISSUE TITLE
Error occurs in Aspire Dashboard structured log viewer when switching log sources

### ISSUE THREAD

**Issue by jimitndiaye** [dotnet/aspire#4447]
```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Aspire.Dashboard.Components.Pages.StructuredLogs.UpdateViewModelFromQuery(StructuredLogsPageViewModel viewModel) in /_/src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs:line 335
   at Aspire.Dashboard.Components.Pages.PageExtensions.InitializeViewModelAsync[TViewModel,TSerializableViewModel](IPageWithSessionAndUrlState`2 page)
   at Aspire.Dashboard.Components.Pages.StructuredLogs.OnParametersSetAsync() in /_/src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs:line 133
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   ```
The above error occurred when I switched from one log source to another. Here is a screenshot:
![AspireDashboardError](https://github.com/dotnet/aspire/assets/316325/da7cdfef-ff36-4b50-a7af-7d388b0639f8)

**Comment by drewnoakes** [comment]
@jimitndiaye thanks for filing this.

A couple of quick questions for you:

- Is this a 100% repro?
- Does it happen when switching between any log sources, or only particular ones?
- Are you running the dashboard during development, or is it hosted somewhere? If hosted, have you customised the application name in config?

Thanks.

**Comment by leslierichardson95** [comment]
This issue may be related to another replica-based scenario: https://github.com/dotnet/aspire/issues/4393

**Comment by jimitndiaye** [comment]
> @jimitndiaye thanks for filing this.
> 
> A couple of quick questions for you:
> 
> - Is this a 100% repro?
> - Does it happen when switching between any log sources, or only particular ones?
> - Are you running the dashboard during development, or is it hosted somewhere? If hosted, have you customised the application name in config?
> 
> Thanks.

No it is not 100%. Only happens occasionally. It is usually when there is a replica set.

Yes I'm running the dashboard during development. Regarding the application name though, I did have a different application name in Serilog's config from before Aspire. It may be that they now conflict.

**Comment by jimitndiaye** [comment]
I think @leslierichardson95 may be right. My scenario is similar.
