### ISSUE TITLE
Error updating database using dotnet ef database update when using postgresql

### ISSUE THREAD

**Issue by kjartanium** [dotnet/aspire#4497]
Using GA version. 

1. Create a .NET Aspire Starter project in VS

2. Add packages in Api service project:
- Aspire.Npgsql.EntityFrameworkCore.PostgreSQL
- Microsoft.EntityFrameworkCore.Design
- Microsoft.EntityFrameworkCore.Tools

3. Create a DbContext in the api service

```
public class ApplicationDbContext(DbContextOptions options) : DbContext(options)
{
    public DbSet<User> Users { get; set; }
}

public class User
{
    public int UserId { get; set; }
    public required string Name { get; set; }
}
```

4. Create a postgres container and database in the apphost (Add Aspire.Hosting.PostgreSQL package)

```
var builder = DistributedApplication.CreateBuilder(args);

var postgresdb = builder.AddPostgres("postgres").AddDatabase("postgresdb");

var apiService = builder.AddProject<Projects.startertest_ApiService>("apiservice").WithReference(postgresdb);

builder.AddProject<Projects.startertest_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(apiService);

builder.Build().Run();

```
5. Add a the following in the api service program.cs:

```
builder.AddNpgsqlDbContext<ApplicationDbContext>("postgresdb");
```

6. Create a migration in the Api service using "dotnet ef migrations add initial"

7. Update the migration in the database fails with the following:

 Build started...
Build succeeded.
System.ArgumentException: Host can't be null
   at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate()
   at Npgsql.NpgsqlConnection.SetupDataSource()
   at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnection..ctor(String connectionString)
   at Npgsql.NpgsqlConnection.CloneWith(String connectionString)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlRelationalConnection.CloneWith(String connectionString)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Host can't be null

I've tried with all possible locations of the migration assembly and so forth, same error.

**Comment by kjartanium** [comment]
Hmm, I'm assuming this happens because the connection string isn't really created at that point since the services isn't fired up. I guess i need to do it runtime, or are there any other workarounds?

**Comment by davidfowl** [comment]
This is because the connection string isn't available when you run from the command line. It's possible to run some dotnet ef commands without a valid connection string (a dummy one is still required), but `dotnet ef database update` isn't possible to run without the database running *and* the connection string being available in the application.

Possible workarounds;

Run the apphost, get the connection string from the dashboard (look at the environment variables of the application), and use it to run `dotnet ef database update` (passing in the connection string)

**Comment by KurtP20** [comment]
Nice workaround, thanks for the tip! For me it worked only after adding `--no-build` option, because running the app locks some files that need to be updated during build.

**Comment by KurtP20** [comment]
In my understanding, adding `--startup-project <AppHost>` should spin up the AppHost so that the container is running and the connection string is available, but there is an error as I have described on [SO](https://github.com/dotnet/aspire/issues/4497). Could you please comment on the SO question?

**Comment by megashrieks** [comment]
@KurtP20 have you considered adding `.WaitFor(postgresdb)` I was running into a similar issue and that fixed it

**Comment by KurtP20** [comment]
@megashrieks I don't think it would help. You could also change the lifetime of the containers to persistent, but you would still need to get the connection string. The work around works, but a nicer solution would still be desirable in my opinion.

**Comment by omidkrad** [comment]
There is a related blog post here, but I think what it is proposing is not correct as the Aspire app, and the containers are never run, unlike what it suggests:

https://khalidabuhakmeh.com/add-ef-core-migrations-to-dotnet-aspire-solutions

**Comment by JoseAugustoScherer** [comment]
Is your ConnectionStrings inside Logging?

**Comment by AndriySvyryd** [comment]
Use the new EF integration: https://github.com/microsoft/aspire/issues/10306
