### ISSUE TITLE
Incomplete Logs on Github Actions (Integration Tests)

### ISSUE THREAD

**Issue by batesjernigan-taxa** [dotnet/aspire#4552]
# Incomplete Logs on Github Actions

Hey All! My team has been developing a new Aspire app using version 8.0.1. In trying to get CI setup we ran into an issue where the logs that are outputted from the test are only related to the test. This was causing the test to fail and we had little visibility due to no Service specific logs being produced to Github Actions Console.

This is an example of the error from the test.
```
[xUnit.net 00:01:10.47]     IntegrationTests.WebTests.GetAccountsRootReturnsOkStatusCode [FAIL]
  Failed IntegrationTests.WebTests.GetAccountsRootReturnsOkStatusCode [1 m 10 s]
  Error Message:
   System.TimeoutException : The operation has timed out.
  Stack Trace:
     at IntegrationTests.WebTests.GetAccountsRootReturnsOkStatusCode() in /home/runner/work/project/Services/Tests/IntegrationTests/WebTests.cs:line 30
   at IntegrationTests.WebTests.GetAccountsRootReturnsOkStatusCode() in /home/runner/work/project/Services/Tests/IntegrationTests/WebTests.cs:line 34
--- End of stack trace from previous location ---

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - IntegrationTests.dll (net8.0)
```

The error was due to an ENV issue that normally stops the service relying on some ENV var from loading. I can see this clearly in teh aspire dashboard, but not in some unified log file.

### Project Setup
```
❯ dotnet workload list

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
aspire                     8.0.1/8.0.100         SDK 8.0.300

Use `dotnet workload search` to find additional workloads to install.

❯ dotnet --version
8.0.301
```

Test
```c#
using System.Net;

namespace IntegrationTests;

public class WebTests
{
    [Fact]
    public async Task GetAccountsRootReturnsOkStatusCode()
    {
        // Arrange
        var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.AppHost>();
        await using var app = await appHost.BuildAsync();
        await app.StartAsync();

        // Act
        var httpClient = app.CreateHttpClient("Accounts");

        // never makes it passed this line
        var response = await httpClient.GetAsync("/").WaitAsync(TimeSpan.FromSeconds(60));

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }
}
```

# Question
Is it possible to get a tail of all logs to output in 1 file if some ENV variable is set (like CI=true) so that we can have meaningful logs for our integration tests?
Specifically I'm looking for a way to get the open telemetry data to dump to the log output on Github Actions.

Example of an error I'd like to see in the Github Actions Console / Unified File.
```shell
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.Development.secretsfoo.json' was not found and is not optional. The expected physical path was '/Users/foobar/Services/Configuration/appsettings.Development.secretsfoo.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Shared.Extensions.ConfigurationStartupExtensions.CreateConfiguration(IConfigurationBuilder builder, IHostEnvironment environment, String[] additionalSettingFiles) in /Users/foobar/Services/Shared/Extensions/ConfigurationStartupExtensions.cs:line 15
   at ServiceDefaults.Extensions.AddServiceDefaults(IHostApplicationBuilder builder, String[] additionalSettingFiles) in /Users/foobar/Services/ServiceDefaults/Extensions.cs:line 42
   at Shared.Services.CreatorExtensions.CreateServiceBuilder(String[] args, String[] additionalSettingFiles) in /Users/foobar/Services/Services/Shared.Services/CreatorExtensions.cs:line 82
   at Program.<Main>$(String[] args) in /Users/foobar/Services/Services/Contacts/Program.cs:line 6
```

**Comment by radical** [comment]
cc @DamianEdwards @ReubenBond

**Comment by radical** [comment]
Also see https://github.com/dotnet/aspire/pull/4444

**Comment by DamianEdwards** [comment]
Yes this will be fixed by #4444 and shipped in 8.1

In the meantime you could copy the code for `ResourceLogForwarderService` in that PR into your own tests to get the logs for resources to be output to the host logs. If you're using xUnit.net, you'd also need to implement a custom logger that outputs to xUnit.net's `ITestOutputHelper` or use a package like https://www.nuget.org/packages/MartinCostello.Logging.XUnit

**Comment by batesjernigan-taxa** [comment]
This worked great! Thank you for the help on this. To close the loop, the steps I took to fix this were copying the contents of [ResouceLogForwarderService](https://github.com/dotnet/aspire/blob/921e53926a9aaf433b46815d4634b16f8a41269a/src/Aspire.Hosting.Testing/ResourceLoggerForwarderService.cs) in my `Shared.Tests` project that my tests include, then updating my test from this
```c#
using System.Net;

namespace IntegrationTests;

public class WebTests
{
    [Fact]
    public async Task GetAccountsRootReturnsOkStatusCode()
    {
        // Arrange
        var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.AppHost>();
        await using var app = await appHost.BuildAsync();
        // ...
    }
}
```
To this
```c#
using System.Net;

using Microsoft.Extensions.DependencyInjection;

using Shared.Tests;

namespace IntegrationTests;

public class WebTests
{
    [Fact]
    public async Task GetAccountsRootReturnsOkStatusCode()
    {
        // Arrange
        var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.AppHost>();
        appHost.Services.AddHostedService<ResourceLoggerForwarderService>();
        await using var app = await appHost.BuildAsync();
        // ...
    }
}
```

**Comment by DamianEdwards** [comment]
Great! Feel free close to the issue if there's nothing left to track here.
