### ISSUE TITLE
[tests] Failing dashboard test - `OtlpGrpcServiceTests.CallService_OtlpGrpcEndPoint_ExternalFile_FileChanged_UseConfiguredKey`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4637]
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719040&view=ms.vss-test-web.build-test-results-tab&runId=18019932&resultId=100267&paneView=debug) on an unrelated PR.

`Aspire.Dashboard.Tests.Integration.OtlpGrpcServiceTests.CallService_OtlpGrpcEndPoint_ExternalFile_FileChanged_UseConfiguredKey`

```
Error message
Assert.Throws() Failure
Expected: typeof(Grpc.Core.RpcException)
Actual:   (No exception was thrown)

Stack trace
   at Aspire.Dashboard.Tests.Integration.OtlpGrpcServiceTests.CallService_OtlpGrpcEndPoint_ExternalFile_FileChanged_UseConfiguredKey() in /_/tests/Aspire.Dashboard.Tests/Integration/OtlpGrpcServiceTests.cs:line 215
   at Aspire.Dashboard.Tests.Integration.OtlpGrpcServiceTests.CallService_OtlpGrpcEndPoint_ExternalFile_FileChanged_UseConfiguredKey() in /_/tests/Aspire.Dashboard.Tests/Integration/OtlpGrpcServiceTests.cs:line 218
--- End of stack trace from previous location ---
```

cc @JamesNK

**Comment by radical** [comment]
cc @joperezr

**Comment by JamesNK** [comment]
The test writes a large number of logs. Are they accessible for a failure?

**Comment by radical** [comment]
We have the generated test log, but nothing else. Where would these log files be? Maybe we should be collecting them for debugging in future.

**Comment by JamesNK** [comment]
This test hasn't failed in the last 30 days. Closing.
