### ISSUE TITLE
[tests] Hosting tests failing with `Application orchestrator dependency check had an unexpected error System.TimeoutException`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4640]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=712935
Build error leg or test failing: Aspire.Hosting.Containers.Tests.WithDockerfileTests.WithBuildSecretPopulatesSecretFilesCorrectly
Pull request: https://github.com/dotnet/aspire/pull/4386

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Application orchestrator dependency check had an unexpected error System.TimeoutException: The operation has timed out.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Console log:
```
| [2024-06-19T15:13:40] Aspire.Hosting.DistributedApplication Information: Aspire version: 8.1.0-ci
| [2024-06-19T15:13:40] Aspire.Hosting.DistributedApplication Information: Distributed application starting.
| [2024-06-19T15:13:40] Aspire.Hosting.DistributedApplication Information: Application host directory is: /mnt/vss/_work/1/s/tests/Aspire.Hosting.Tests
| [2024-06-19T15:14:05] Microsoft.Extensions.Hosting.Internal.Host Error: Hosting failed to start
| Aspire.Hosting.DistributedApplicationException: Application orchestrator dependency check had an unexpected error System.TimeoutException: The operation has timed out.
|    at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 78.
|    at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 105
|    at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
|    at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
|    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
|    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

cc @karolz-ms @joperezr 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=712935
**Error message validated:** `[Application orchestrator dependency check had an unexpected error System.TimeoutException: The operation has timed out.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/25/2024 4:01:24 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
The error output has changed, so closing this in favor of the newer https://github.com/dotnet/aspire/issues/5195 .
