### ISSUE TITLE
Failing test `Aspire.Hosting.Tests.DistributedApplicationTests.TestServicesWithMultipleReplicas`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4651]
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=719871
Build error leg or test failing: Aspire.Hosting.Tests.DistributedApplicationTests.TestServicesWithMultipleReplicas
Pull request: https://github.com/dotnet/aspire.git/pull/4645

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: Connection reset by peer.
-------- System.Net.Sockets.SocketException : Connection reset by peer

   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Aspire.Hosting.Tests.DistributedApplicationTests.TestServicesWithMultipleReplicas() in /_/tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs:line 191
   at Aspire.Hosting.Tests.DistributedApplicationTests.TestServicesWithMultipleReplicas() in /_/tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs:line 221
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
----- Inner Stack Trace -----
```

cc @mitchdenny 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

## Last 10 failures:
| Run date | Test Name |
| --------- | ---- |

-- Updated on 5/6/2025 3:39:57 AM UTC

## Summary

| Last 40 | Total failed / total runs |
| --- | --- |
| 0 | 0 / 200 |

**Comment by davidebbo** [comment]
It would be good to try to re-enable some of these tests, to prevent situations like https://github.com/dotnet/aspire/issues/5898.

This issue title just says `TestServicesWithMultipleReplicas`, but there are 19 tests in `DistributedApplicationTests` that are CI disabled and pointing to this issue.

**Comment by alexTr3** [comment]
I'm currently facing this issues in CI, is there any quick fix? Test are running locally but not in linux CI / google cloud build and facing the same error on the httpclient... 

also running the same test in WSL from vs2022 get me another exception (project not found)..

**Comment by radical** [comment]
This test was un-quarantined, but the issue wasn't closed. Closing now.

> I'm currently facing this issues in CI, is there any quick fix? Test are running locally but not in linux CI / google cloud build and facing the same error on the httpclient...
> 
> also running the same test in WSL from vs2022 get me another exception (project not found)..

I'm closing the issue, but if you still get this failure on `main` then could you please open a new issue so we can track that accordingly? Thanks!

**Comment by davidfowl** [comment]
This failed again on my PR TestServicesWithMultipleReplicas

**Comment by radical** [comment]
Unquarantined by #9115 .
