### ISSUE TITLE
[WebToolsE2E][Aspire] Installing Aspire 8.0.1 throws an exception: Cannot access a disposed object System.Collections.Concurrent.BlockingCollection.

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/aspire#4663]
**REPRO STEPS**

- Clean machine: Win11 x64 23h2 ENU
- Install SDK 8.0.302
- Install Aspire 8.0.1 using commands 'dotnet workload update' and 'dotnet workload install aspire'

**ACTUAL**
The aspire workload installed successfully but encountered an error

Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Collections.Concurrent.BlockingCollection`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, 
Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.WriteMessage(String message)
   at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.ProcessLogRequests(Object logPipeName)

![image](https://github.com/dotnet/aspire/assets/78580199/88cb3d46-a15b-439c-8f52-9a8a41ffe1b9)

**Comment by v-elenafeng** [comment]
This issue rarely occurs, reporting it in case we miss something.

**Comment by balachir** [comment]
Adding @marcpopMSFT @joperezr for awareness.

**Comment by marcpopMSFT** [comment]
cc @dsplaisted @Forgind to take a look. This is 8.0.302 which is the hotfix June release we did for Razor I believe. Did this repro with 8.0.300 (as we didn't make any changes in the SDK between those builds)? Does it repro with 8.0.302?

**Comment by dsplaisted** [comment]
Looks like a race condition or similar in `TimestampedFileLogger` between disposing the object and writing out the messages.  Since it's a timing issue, it could start occurring without any specific code changes in that area.  Probably we need to add a lock in `WriteMessage` and `Dispose`.  @joeloff
