### ISSUE TITLE
The endpoint `http`/`https` is not allocated for the resource 

### ISSUE THREAD

**Issue by moljac** [dotnet/aspire#4868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is duplicate of issue reported in eShop, 

https://github.com/dotnet/eShop/issues/228

but it needs more love, so adding it here.

It is on Mac, but I think it is irrelevant.

Calling 

```csharp
Console.WriteLine($"IP          {apiService.GetEndpoint("http").Url}");
```

crashes with:

```
Building...
Unhandled exception. System.InvalidOperationException: The endpoint `http` is not allocated for the resource `apiservice`.
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_AllocatedEndpoint() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 107
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_Url() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 104
   at Program.<Main>$(String[] args) in /Users/Shared/Projects/d/Samples-Playgrounds/gh/Blazor.FluentUI/samples/code-sharing/AppAspireRepro/AppAspireRepro.AppHost/Program.cs:line 9
```

### Expected Behavior

Should handle Exception at least.

### Steps To Reproduce

Cleanup

```bash
rm -fr AppAspireRepro/
```

Create minimal sample

```bash
dotnet new aspire-starter -o AppAspireRepro
```

Run:

```bash
dotnet run --project AppAspireRepro/AppAspireRepro.AppHost/AppAspireRepro.AppHost.csproj
```

Now add:

```csharp
Console.WriteLine($"IP          {apiService.GetEndpoint("http").Url}");
Console.WriteLine($"IP          {apiService.GetEndpoint("https").Url}");
```

before:

```csharp
builder.Build().Run();
```

Run again 

```bash
dotnet run --project AppAspireRepro/AppAspireRepro.AppHost/AppAspireRepro.AppHost.csproj
```

and watch Der Untergang:

```
Building...
Unhandled exception. System.InvalidOperationException: The endpoint `http` is not allocated for the resource `apiservice`.
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_AllocatedEndpoint() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 107
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_Url() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 104
   at Program.<Main>$(String[] args) in /Users/Shared/Projects/d/Samples-Playgrounds/gh/Blazor.FluentUI/samples/code-sharing/AppAspireRepro/AppAspireRepro.AppHost/Program.cs:line 9
```

### Exceptions (if any)

```
Unhandled exception. System.InvalidOperationException: The endpoint `http` is not allocated for the resource `apiservice`.
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_AllocatedEndpoint() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 107
   at Aspire.Hosting.ApplicationModel.EndpointReference.get_Url() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 104
   at Program.<Main>$(String[] args) in /Users/Shared/Projects/d/Samples-Playgrounds/gh/Blazor.FluentUI/samples/code-sharing/AppAspireRepro/AppAspireRepro.AppHost/Program.cs:line 9
```

### .NET Version info

```
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.7ccdde63
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.303/

.NET workloads installed:
 [wasm-tools]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.7/WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [macos]
   Installation Source: SDK 8.0.300
   Manifest Version:    14.2.8078/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.macos/14.2.8078/WorkloadManifest.json
   Install Type:        FileBased

 [maui-tizen]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [maui-maccatalyst]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [maui-ios]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [wasi-experimental]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.7/WorkloadManifest.json
   Install Type:        FileBased

 [maui-android]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8078/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.ios/17.2.8078/WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.0.2/WorkloadManifest.json
   Install Type:        FileBased

 [maui-mobile]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8078/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maccatalyst/17.2.8078/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased

 [tvos]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8078/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.tvos/17.2.8078/WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: SDK 8.0.300
   Manifest Version:    34.0.113/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.android/34.0.113/WorkloadManifest.json
   Install Type:        FileBased

 [wasm-experimental]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.7/WorkloadManifest.json
   Install Type:        FileBased

 [wasm-experimental-net7]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.net7/8.0.7/WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools-net6]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.net6/8.0.7/WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools-net7]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.net7/8.0.7/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-preview.1.24080.9
  Architecture: arm64
  Commit:       1d1bf92fcf

.NET SDKs installed:
  6.0.123 [/usr/local/share/dotnet/sdk]
  6.0.126 [/usr/local/share/dotnet/sdk]
  6.0.128 [/usr/local/share/dotnet/sdk]
  6.0.129 [/usr/local/share/dotnet/sdk]
  6.0.130 [/usr/local/share/dotnet/sdk]
  6.0.131 [/usr/local/share/dotnet/sdk]
  6.0.315 [/usr/local/share/dotnet/sdk]
  6.0.318 [/usr/local/share/dotnet/sdk]
  6.0.321 [/usr/local/share/dotnet/sdk]
  6.0.412 [/usr/local/share/dotnet/sdk]
  6.0.415 [/usr/local/share/dotnet/sdk]
  6.0.416 [/usr/local/share/dotnet/sdk]
  6.0.417 [/usr/local/share/dotnet/sdk]
  6.0.418 [/usr/local/share/dotnet/sdk]
  6.0.419 [/usr/local/share/dotnet/sdk]
  6.0.420 [/usr/local/share/dotnet/sdk]
  6.0.421 [/usr/local/share/dotnet/sdk]
  6.0.423 [/usr/local/share/dotnet/sdk]
  6.0.424 [/usr/local/share/dotnet/sdk]
  7.0.120 [/usr/local/share/dotnet/sdk]
  7.0.317 [/usr/local/share/dotnet/sdk]
  7.0.410 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]
  8.0.101 [/usr/local/share/dotnet/sdk]
  8.0.103 [/usr/local/share/dotnet/sdk]
  8.0.104 [/usr/local/share/dotnet/sdk]
  8.0.106 [/usr/local/share/dotnet/sdk]
  8.0.107 [/usr/local/share/dotnet/sdk]
  8.0.200 [/usr/local/share/dotnet/sdk]
  8.0.201 [/usr/local/share/dotnet/sdk]
  8.0.202 [/usr/local/share/dotnet/sdk]
  8.0.203 [/usr/local/share/dotnet/sdk]
  8.0.204 [/usr/local/share/dotnet/sdk]
  8.0.205 [/usr/local/share/dotnet/sdk]
  8.0.206 [/usr/local/share/dotnet/sdk]
  8.0.300 [/usr/local/share/dotnet/sdk]
  8.0.301 [/usr/local/share/dotnet/sdk]
  8.0.302 [/usr/local/share/dotnet/sdk]
  8.0.303 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.23 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.24 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.28 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.29 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.30 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.32 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.24 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.28 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.29 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Anything else?

- CLI (`dotnet`)
- Aspire 8.0.2

**Comment by Alirexaa** [comment]
It seems you try get Endpoint url before host started, endpoint allocated when host completly started.

**Comment by moljac** [comment]
@Alirexaa 

Thanks for help.

> It seems you try get Endpoint url before host started, endpoint allocated when host completly started.

Not sure about that. OK. I am not Aspire expert, but I remember I tried a lot of variants.

Have you tried to repro? It is quite simple.

OK. Trying.

Changed

```csharp
var a = builder.Build();

Console.WriteLine($"IP          {apiService.GetEndpoint("http").Url}");
Console.WriteLine($"IP          {apiService.GetEndpoint("https").Url}");

a.Run();
```

The same result. I think placing code after `a.Run()` would not make much sense.

There are several comments in eShop repo (issue I linked)

**Comment by moljac** [comment]
Confirmed (tested):

Code:

```csharp
var a = builder.Build();

a.Run();

Console.WriteLine($"IP          {apiService.GetEndpoint("http").Url}");
Console.WriteLine($"IP          {apiService.GetEndpoint("https").Url}");
```

Does not throw, but cannot be used.

```
Building...
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.2+3d0cf817f24298ba37bca94f15bd2f7061856e77
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: /Users/Shared/Projects/d/Samples-Playgrounds/gh/Blazor.FluentUI/samples/code-sharing/AppAspireRepro/AppAspireRepro.AppHost
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: https://localhost:17188
info: Aspire.Hosting.DistributedApplication[0]
      Login to the dashboard at https://localhost:17188/login?t=fb1d1d3b858c84de2dccaa27ed62629f
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
```

Seems like new extension method `a.RunExtended()` which calls `a.Run()` would be solution (for MAUI integration).
