### ISSUE TITLE
Playwright tests failing on linux complaining about missing dependencies

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4921]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=742280
Build error leg or test failing: Aspire.Workload.Tests.EmptyTemplateRunTests.ResourcesShowUpOnDashboad
Pull request: https://github.com/dotnet/aspire/pull/4914

```
Aspire.Workload.Tests: [apphost] info: Aspire.Hosting.DistributedApplication[0]
Aspire.Workload.Tests: [apphost]       Distributed application started. Press Ctrl+C to shut down.
Aspire.Workload.Tests: -- Ready to run tests --
    Aspire.Workload.Tests.EmptyTemplateRunTests.ResourcesShowUpOnDashboad [FAIL]
      System.AggregateException : One or more errors occurred. (
      ╔══════════════════════════════════════════════════════════╗
      ║ Host system is missing dependencies to run browsers.     ║
      ║ Please install them with the following command:          ║
      ║                                                          ║
      ║     sudo pwsh bin/Debug/netX/playwright.ps1 install-deps ║
      ║                                                          ║
      ║ Alternatively, use apt:                                  ║
      ║     sudo apt-get install libgbm1\                        ║
      ║         libxkbcommon0                                    ║
      ║                                                          ║
      ║ <3 Playwright Team                                       ║
      ╚══════════════════════════════════════════════════════════╝)
      ---- Microsoft.Playwright.PlaywrightException : 
      ╔══════════════════════════════════════════════════════════╗
      ║ Host system is missing dependencies to run browsers.     ║
      ║ Please install them with the following command:          ║
      ║                                                          ║
      ║     sudo pwsh bin/Debug/netX/playwright.ps1 install-deps ║
      ║                                                          ║
      ║ Alternatively, use apt:                                  ║
      ║     sudo apt-get install libgbm1\                        ║
      ║         libxkbcommon0                                    ║
      ║                                                          ║
      ║ <3 Playwright Team                                       ║
      ╚══════════════════════════════════════════════════════════╝
      Stack Trace:
           at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
           at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
        /_/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs(28,0): at Aspire.Workload.Tests.WorkloadTestsBase.CreateBrowser()
           at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
           at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
           at System.Lazy`1.CreateValue()
        /_/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs(37,0): at Aspire.Workload.Tests.WorkloadTestsBase.CreateNewBrowserContextAsync()
        /_/tests/Aspire.Workload.Tests/EmptyTemplateRunTests.cs(22,0): at Aspire.Workload.Tests.EmptyTemplateRunTests.ResourcesShowUpOnDashboad()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/Playwright/Transport/Connection.cs(206,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls)
        /_/src/Playwright/Transport/Connection.cs(532,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
        /_/src/Playwright/Core/BrowserType.cs(56,0): at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options)
        /_/tests/Shared/Playwright/PlaywrightProvider.cs(36,0): at Aspire.Workload.Tests.PlaywrightProvider.CreateBrowserAsync(BrowserTypeLaunchOptions options)
        /_/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs(24,0): at Aspire.Workload.Tests.WorkloadTestsBase.<>c.<<CreateBrowser>b__5_0>d.MoveNext()
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Host system is missing dependencies to run browsers",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

This shouldn't be happening because the queue should have the dependencies installed on the vm image itself (https://github.com/dotnet/dnceng/issues/3122).

cc @joperezr 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=742280
**Error message validated:** `[Host system is missing dependencies to run browsers`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/16/2024 4:31:26 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[770579](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770579)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770579&view=ms.vss-test-web.build-test-results-tab&runId=19683758&resultId=100021)|dotnet/aspire#5066|
|[763362](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763362)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763362&view=ms.vss-test-web.build-test-results-tab&runId=19404924&resultId=100021)|dotnet/aspire#5066|
|[754704](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754704)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754704&view=ms.vss-test-web.build-test-results-tab&runId=19129920&resultId=100021)|dotnet/aspire#5064|
|[754402](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754402)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754402&view=ms.vss-test-web.build-test-results-tab&runId=19118936&resultId=100021)|dotnet/aspire#5066|
|[742611](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742611)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742611&view=ms.vss-test-web.build-test-results-tab&runId=18755542&resultId=100021)|dotnet/aspire#4926|
|[742506](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742506)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742506&view=ms.vss-test-web.build-test-results-tab&runId=18752256&resultId=100021)|dotnet/aspire#4923|
|[742505](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742505)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742505&view=ms.vss-test-web.build-test-results-tab&runId=18752226&resultId=100021)|dotnet/aspire#4924|
|[742495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742495)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742495&view=ms.vss-test-web.build-test-results-tab&runId=18751812&resultId=100021)|dotnet/aspire#4850|
|[742419](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742419)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742419&view=ms.vss-test-web.build-test-results-tab&runId=18748190&resultId=100021)|dotnet/aspire#4805|
|[742280](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742280)|dotnet/aspire|[Aspire.Workload.Tests.Xunit_PerTestFrameworkTemplatesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742280&view=ms.vss-test-web.build-test-results-tab&runId=18746574&resultId=100021)|dotnet/aspire#4914|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|10|

**Comment by radical** [comment]
Related to https://github.com/dotnet/aspire/issues/4623 .

**Comment by radical** [comment]
These tests have been disabled with https://github.com/dotnet/aspire/pull/4922 . Closing, this in favor of the original issue.

**Comment by radical** [comment]
This is not a flaky test. We don't have Playwright installed on Linux/helix, so these tests don't run there. But we run the same on github actions/ubuntu-latest.

**Comment by radical** [comment]
Closing this as the test coverage is provided by GH actions rolling builds, and PR test runs.
