### ISSUE TITLE
Aspire.Hosting.Dashboard - Failed to bind to address, address already in use.

### ISSUE THREAD

**Issue by taniasimpson** [dotnet/aspire#5112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This issue was also mentioned by @mitchdenny from https://github.com/dotnet/aspire/issues/2198. But I did not see any solutions mentioned specifically for this (unless I read right over it) 

However, the first time I run the app and then stop it. Every start up after that causes the following issues: 
1. <img width="925" alt="image" src="https://github.com/user-attachments/assets/b2076916-b69a-46f7-8c07-cac4f7ad1a7f">
2. The containers in docker are not removed, and I have to manually delete.
3. This causes the dashboard to not be aligned with docker
4. A login screen pops up asking for token (even if I retrieve this from the console, I can't log in)

Changes made to not see this issue again: 
- Change all ports that are referenced in my `launchSettings.json` file
- Clean/Rebuild solution (If I don't, old port values are still held and I still see issues above) 
- I can start & stop the application as many times as I want and I never come across the issues above. 

If I change the ports back, the issue still remains. I have the latest Aspire nuget packages, WSL 2, Docker Desktop and Visual Studio 2022 Professional. All up to date.

What can I do so that my team does not have to run it once and then immediately change ports to solve this current issue?

**Comment by markat1** [comment]
I'm having something similar issue -  running it in administrator mode doesn't resolve it either.

```
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.577Z Unhandled exception. System.IO.IOException: Failed to bind to address https://localhost:21256.
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.587Z  ---> System.AggregateException: One or more errors occurred. (Det blev fors?gt at f? adgang til en socket p? en m?de, der er forbudt af den p?g?ldende sockets adgangstilladelser.) (Det blev fors?gt at f? adgang til en socket p? en m?de, der er forbudt af den p?g?ldende sockets adgangstilladelser.)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.587Z  ---> System.Net.Sockets.SocketException (10013): Det blev fors?gt at f? adgang til en socket p? en m?de, der er forbudt af den p?g?ldende sockets adgangstilladelser.
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.587Z    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.587Z    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.587Z    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
fail: Aspire.Hosting.Dashboard.Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.IO.IOException: Failed to bind to address https://localhost:21256.
       ---> System.AggregateException: One or more errors occurred. (Det blev forsøgt at få adgang til en socket på en måde, der er forbudt af den pågældende sockets adgangstilladelser.) (Det blev forsøgt at få adgang til en socket på en måde, der er forbudt af den pågældende sockets adgangstilladelser.)
       ---> System.Net.Sockets.SocketException (10013): Det blev forsøgt at få adgang til en socket på en måde, der er forbudt af den pågældende sockets adgangstilladelser.
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
         at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Bind(EndPoint localEP)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
       ---> (Inner Exception #1) System.Net.Sockets.SocketException (10013): Det blev forsøgt at få adgang til en socket på en måde, der er forbudt af den pågældende sockets adgangstilladelser.
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
         at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Bind(EndPoint localEP)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)<---

         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.587Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.587Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.587Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.587Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z --- End of stack trace from previous location ---
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    --- End of inner exception stack trace ---
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z  ---> (Inner Exception #1) System.Net.Sockets.SocketException (10013): Det blev fors?gt at f? adgang til en socket p? en m?de, der er forbudt af den p?g?ldende sockets adgangstilladelser.
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z --- End of stack trace from previous location ---
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)<---
fail: Aspire.Hosting.Dashboard[0]
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    --- End of inner exception stack trace ---
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
fail: Aspire.Hosting.Dashboard[0]
      2024-09-01T07:04:51.588Z    at Aspire.Dashboard.DashboardWebApplication.Run() in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 695
```

**Comment by markat1** [comment]
@davidfowl any idea how to resolve this?

**Comment by davidfowl** [comment]
Look got an existing running aspire dashboard and kill the process

**Comment by KennethHoff** [comment]
This is incredibly annoying, having to wait up to a minute (sometimes several minutes) everytime I stop the app before I can re-start it. Depending on what I'm working on, this is wasting up to like half an hour per day. 

Using `lsof` and `kill` I've been able to somewhat improve the DX, but it's still annoying that I have to do this every time I stop Aspire.

**Comment by davidfowl** [comment]
Are you seeing this every time you stop aspire? Id so can you record a video of the repro and share it here? If we’re able to get a reliable repro then we might be able to fix the problem (or mitigate).

**Comment by KennethHoff** [comment]
More-or-less every time, ye. Sometimes it's near-instant though, but that's a minority.

It seems like it's happening because of NodeJS. Specifically we're running `turbo run ***` to run next.js applications. They are taking several seconds to exit. According to some colleagues on Windows it can take several minutes on their Windows PC (I'm using an M3 Mac Pro, which is substantially faster than their Dell Windows machines; unsure if it's the OS or the power of the machine itself that's causing the difference, but I'm betting on just the perf).

I'll try it out tomorrow to see if this still happens if I remove the nextjs applications, or if it's unrelated.

**Comment by davidfowl** [comment]
Might be related to this https://github.com/dotnet/aspire/issues/6221#issuecomment-2408002558

**Comment by KennethHoff** [comment]
The description of that issue sounds a lot like what I'm experiencing too, when it comes to stopping of resources as well.

**Comment by danegsta** [comment]
The issue was likely exacerbated by changes made during 9.0 preview; we weren't always waiting for stdio to flush when shutting down services (which could result in file in use errors when we tried to cleanup the log files for a restarted process). We made a change to ensure we always wait for stdio, but that introduced a regression in the event that the kill signal wasn't forwarded to child processes (which seems to be the case with node.js on Windows).

We likely weren't properly cleaning up node processes before the regression, but now it could cause a deadlock during resource cleanup preventing us from completing the full teardown before we finally timed out. For executables we spawn additional cleanup processes whose only role is to kill forked service processes if we don't have a clean exit/complete the normal teardown, which is why we were still cleaning up those resources after everything timed out, but potentially leaving behind containers that weren't cleaned up.

Good news is a fix should be in main later today.

**Comment by danegsta** [comment]
Okay, a fix for one potential cause of this issue is in (failure to cleanup some resources cleanly during shutdown) has been merged, but I can't guarantee it will solve all the address in use cases that have been reported, so I'm reluctant to close this particular issue.

**Comment by davidfowl** [comment]
@danegsta @dbreshears @karolz-ms I am going to mark this under orchestrator and close as fixed https://github.com/dotnet/aspire/issues/6704
