### ISSUE TITLE
[WebToolsE2E][Aspire] When creating Aspire Starter App, there is an error in CMD when clicking the Console Logs multiple times.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#5135]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.5
3. Install Aspire 8.1.0

**REPRO STEPS**

1. Create Aspire Starter App
2. Build solution and run the project
4. Click the "Console" option on the Aspire dashboard and select the apiservice/webfrontend resource.
5. Click the Console button multiple times

**ACTUAL**
There is an error in CMD when clicking the Console button multiple times
![BugConsole](https://github.com/user-attachments/assets/abb787bb-04b9-4063-b778-566ade0b93c5)

> Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'WatchResourceConsoleLogs'.
      System.IO.IOException: The client reset the request stream.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.ReadAsync(CancellationToken cancellationToken)
         at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)

**EXPECTED**
There should be no errors in CMD when clicking the Console button multiple times.

**Comment by v-reinawang** [comment]
This issue is stable on Aspire 8.1.1-Preview.1.24381.3, but unstable on Aspire 8.1.0. We will continue to verify it tomorrow.

**Comment by v-reinawang** [comment]
There is a similar bug here [#4213](https://github.com/dotnet/aspire/issues/4213).

**Comment by davidfowl** [comment]
This is the same bug. Closing as dupe
