### ISSUE TITLE
OracleDatabaseServerResource.WithDbSetupBindMount has no effect

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspire#5190]
The container doesn't take the files into account. `WithInitBindMount` works fine though so this could be a problem only with assumptions about how it is supposed to work.

**Comment by ascott18** [comment]
`OracleDatabaseServerResource.WithInitFiles` also does not seem to work. Only the now-obsolete `OracleDatabaseServerResource.WithInitBindMount` actually works here.

There's a test that asserts that `WithInitFiles` does work while acknowledging this issue that `WithDbSetupBindMount` does not work. https://github.com/dotnet/aspire/blob/bf6d591e507129df9605bab053933609c861bdf2/tests/Aspire.Hosting.Oracle.Tests/OracleFunctionalTests.cs#L345-L349

However, since all the Oracle tests have been apparently quarantined (#5362), the fact that actually **both** of these tests cases fail has been masked.


```
[+0/x0/?0] Aspire.Hosting.Oracle.Tests.dll (net8.0|x64) - Aspire.Hosting.Oracle.Tests.OracleFunctionalTests.VerifyWithInitFiles(init: True) (15s)
  
  info: Microsoft.Hosting.Lifetime[0]
        Application started. Press Ctrl+C to shut down.
  info: Microsoft.Hosting.Lifetime[0]
        Hosting environment: Production
  info: Microsoft.Hosting.Lifetime[0]
        Content root path: D:\aaaThirdParty\aspire\artifacts\bin\Aspire.Hosting.Oracle.Tests\Debug\net8.0
  fail: Microsoft.EntityFrameworkCore.Database.Command[0]
        2026-03-06 15:50:07.378347 ThreadID:10  (ERROR)   OracleRelationalCommand.ExecuteReaderAsync() :  Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00942: table or view "SYSTEM"."Cars" does not exist
        https://docs.oracle.com/error-help/db/ora-00942/
           at Oracle.ManagedDataAccess.Client.OracleCommand.<>c.<ExecuteDbDataReaderAsync>b__232_0(Task`1 result)
           at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location ---
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location ---
           at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
  fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
        Failed executing DbCommand (49ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
        SELECT "c"."Id", "c"."Brand"
        FROM "Cars" "c"
  fail: Microsoft.EntityFrameworkCore.Query[10100]
        An exception occurred while iterating over the results of a query for context type 'Aspire.Hosting.Oracle.Tests.TestDbContext'.
        Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00942: table or view "SYSTEM"."Cars" does not exist
        https://docs.oracle.com/error-help/db/ora-00942/
           at Oracle.ManagedDataAccess.Client.OracleCommand.<>c.<ExecuteDbDataReaderAsync>b__232_0(Task`1 result)
           at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location ---
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location ---
           at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
           at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
           at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
           at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
           at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
           at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
           at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
           at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
           at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
        Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00942: table or view "SYSTEM"."Cars" does not exist
        https://docs.oracle.com/error-help/db/ora-00942/
           at Oracle.ManagedDataAccess.Client.OracleCommand.<>c.<ExecuteDbDataReaderAsync>b__232_0(Task`1 result)
           at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location ---
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location ---
           at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
           at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
           at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
           at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
           at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
           at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
           at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
           at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
```

**Comment by DanielRose** [comment]
After extensive research, I believe I found the root causes:

- `WithDbSetupBindMount` binds to `/opt/oracle/scripts/setup`. However if you use a "free" or "XE" image, they bring a pre-built DB with them. In that case, the setup scripts will not run. See [Oracle AI Database 26ai Free Container Image Documentation](https://container-registry.oracle.com/ords/f?p=113:4:14571611739772:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:1863,1863,Oracle%20Database%20Free,Oracle%20Database%20Free,1,0&cs=3FOufaiIomRO8IMZXwV_5fGeOg_1VVFxUy5RPdtVRrmAZnA5sFmTRbJjYhXJ9xT118f-vESbyKRz6kKTxWOreMw):

> Note: The setup scripts will not run in Free and Free Lite image as both comes with a pre-built database. If host mount point (empty directory) is provided, then a new database setup will start and setup scripts will run.

- `WithInitBindMount` binds to `/opt/oracle/scripts/startup`. However, `WithInitFiles` binds to `/docker-entrypoint-initdb.d`. The latter is an alias (on Oracle containers) for `/opt/oracle/scripts`, which is the _parent_ directory for scripts. The relevant subdirectories are `setup` and `startup`. So either
    - Move your local startup scripts to a `startup` subdirectory, and use `WithInitFiles` on the parent directory
    - Call `WithContainerFiles` yourself, with the correct target directory, ex. `.WithContainerFiles("/docker-entrypoint-initdb.d/startup", "my-startup-scripts")`
