### ISSUE TITLE
[tests] `Mongo` playground tests failing to `connect to host.docker.internal`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#5274]
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=773448&view=logs&j=acc6f692-388e-5b31-5997-e154da29f5b3&t=59fafa2a-4be0-5f74-c845-0779cc54f4a3

```
info: Mongo.AppHost.Resources.mongo-mongoexpress[0] 45: 2024-08-12T23:04:36.124121632Z Waiting for host.docker.internal:39875...
fail: Mongo.AppHost.Resources.mongo-mongoexpress[0] 46: 2024-08-12T23:04:36.230718602Z /docker-entrypoint.sh: line 15: host.docker.internal: Name does not resolve
fail: Mongo.AppHost.Resources.mongo-mongoexpress[0] 47: 2024-08-12T23:04:36.234785505Z /docker-entrypoint.sh: line 15: /dev/tcp/host.docker.internal/39875: Invalid argument

info: Mongo.AppHost.Resources.mongo-mongoexpress[0] 48: 2024-08-12T23:04:37.233651564Z Mon Aug 12 23:04:37 UTC 2024 retrying to connect to host.docker.internal:39875 (2/10)
fail: Mongo.AppHost.Resources.mongo-mongoexpress[0] 49: 2024-08-12T23:04:37.235349865Z /docker-entrypoint.sh: line 15: host.docker.internal: Name does not resolve

info: Mongo.AppHost.Resources.mongo[0] 89: 2024-08-12T23:04:37.448420306Z {"t":{"$date":"2024-08-12T23:04:37.448+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}

info: Mongo.AppHost.Resources.mongo-mongoexpress[0] 51: 2024-08-12T23:04:38.237924127Z Mon Aug 12 23:04:38 UTC 2024 retrying to connect to host.docker.internal:39875 (3/10)
fail: Mongo.AppHost.Resources.mongo-mongoexpress[0] 52: 2024-08-12T23:04:38.239519428Z /docker-entrypoint.sh: line 15: host.docker.internal: Name does not resolve

...

fail: Mongo.AppHost.Resources.mongo-mongoexpress[0] 73: 2024-08-12T23:04:45.271880897Z /docker-entrypoint.sh: line 15: /dev/tcp/host.docker.internal/39875: Invalid argument
info: Mongo.AppHost.Resources.mongo-mongoexpress[0] 74: 2024-08-12T23:04:45.270131894Z Mon Aug 12 23:04:45 UTC 2024 retrying to connect to host.docker.internal:39875 (10/10)
```

.. and then fails with:
```
Could not connect to database using connectionString: mongodb://host.docker.internal:39875/?directConnection=true"
/app/node_modules/mongodb/lib/sdam/topology.js:285
                const timeoutError = new error_1.MongoServerSelectionError(`Server selection timed out after ${serverSelectionTimeoutMS} ms`, this.description);
                                     ^

MongoServerSelectionError: getaddrinfo ENOTFOUND host.docker.internal
    at Timeout._onTimeout (/app/node_modules/mongodb/lib/sdam/topology.js:285:38)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  reason: TopologyDescription {
    type: 'Single',
    servers: Map(1) {
      'host.docker.internal:39875' => ServerDescription {
        address: 'host.docker.internal:39875',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
         maxWireVersion: 0,
         roundTripTime: -1,
         lastUpdateTime: 628461,
         lastWriteDate: 0,
         error: MongoNetworkError: getaddrinfo ENOTFOUND host.docker.internal
             at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:387:20)
             at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:310:22)
             at Object.onceWrapper (node:events:632:26)
             at Socket.emit (node:events:517:28)
             at emitErrorNT (node:internal/streams/destroy:151:8)
             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
             at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
           cause: Error: getaddrinfo ENOTFOUND host.docker.internal
               at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
             errno: -3008,
             code: 'ENOTFOUND',
             syscall: 'getaddrinfo',
             hostname: 'host.docker.internal'
           },
           [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
         },
         topologyVersion: null,
         setName: null,
         setVersion: null,
         electionId: null,
         logicalSessionTimeoutMinutes: null,
         primary: null,
         me: null,
         '$clusterTime': null
       }
     },
     stale: false,
     compatible: true,
     heartbeatFrequencyMS: 10000,
     localThresholdMS: 15,
     setName: null,
     maxElectionId: null,
     maxSetVersion: null,
     commonWireVersion: 0,
     logicalSessionTimeoutMinutes: null
   },
   code: undefined,
   [Symbol(errorLabels)]: Set(0) {}
 }
 
 Node.js v18.20.3
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "MongoNetworkError: getaddrinfo ENOTFOUND host.docker.internal",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=773448
**Error message validated:** `[MongoNetworkError: getaddrinfo ENOTFOUND host.docker.internal`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/13/2024 12:39:46 AM UTC

**Comment by radical** [comment]
cc @eerhardt @sebastienros

**Comment by eerhardt** [comment]
I believe this is because we don't have Docker Desktop installed on the CI / Helix machines. Instead we have the "vanilla Docker" installed. See https://github.com/microsoft/usvc/issues/164 for more info.

**Comment by davidfowl** [comment]
Fixed by https://github.com/dotnet/aspire/issues/5584
