### ISSUE TITLE
Adding minimal ClassLibrary1 library project reference to Aspire orchestrated Project causes azd deploy error (Value cannot be null. (Parameter 'value'))

### ISSUE THREAD

**Issue by joe-mills** [dotnet/aspire#5421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding a minimal Class library to the Aspire App starter project and referencing that Class library Project in the ApiService project causes an error on az deploy

### Expected Behavior

Aspire solution should deploy to Azure successfully using azd up

### Steps To Reproduce

1. Create .Net Aspire Starter App project
2. Run azd init, azd up - successfully deploys
3. Add new Class Library Project called ClassLibrary1
4. Add Project reference in ApiService project to ClassLibrary1
5. run azd deploy apiservice - deployment error

### Exceptions (if any)

MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 9432:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 24/08/2024 12:20:38
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:

### .NET Version info

.Net 8
Aspire 8.1.0

### Anything else?

I have tried adding the ClassLibrary1 to Aspire orchestration and setting IsAspireProjectResource=false on AppHost project reference.  
The solution builds and runs locally but does not deploy.

**Comment by kraldev** [comment]
Same here

**Comment by davidfowl** [comment]
Update your .NET SDK to 8.0.401. There was a regression with container publish.

**Comment by joe-mills** [comment]
Thanks that worked.  I was using 9.0.100-preview.7.24407.12 sdk so installed 8.0.401 and specified with global.json

**Comment by kraldev** [comment]
This worked. Thanks @davidfowl
