### ISSUE TITLE
Unexpected error when using Dashboard

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspire#5482]
I believe I was opening the filter dropdown on the main resources page and got the below error

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'jX3Kb5wLNVgUw5jCG9lRLZs2dhIXwhCIl8FNn-2DYHc'.
      Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'focusableElement')
      TypeError: Cannot read properties of null (reading 'focusableElement')
          at Module.goToNextFocusableElement (https://dashboard/_content/Microsoft.FluentUI.AspNetCore.Components/Components/AnchoredRegion/FluentAnchoredRegion.razor.js:5:22)
          at https://dashboard/_framework/blazor.web.js:1:3244
          at new Promise (<anonymous>)
          at y.beginInvokeJSFromDotNet (https://dashboard/_framework/blazor.web.js:1:3201)
          at fn._invokeClientMethod (https://dashboard/_framework/blazor.web.js:1:62914)
          at fn._processIncomingData (https://dashboard/_framework/blazor.web.js:1:60389)
          at An.onreceive (https://dashboard/_framework/blazor.web.js:1:54030)
          at WebSocket.<anonymous> (https://dashboard/_framework/blazor.web.js:1:82175)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at Microsoft.FluentUI.AspNetCore.Components.FluentAnchoredRegion.OnAfterRenderAsync(Boolean firstRender) in /_/src/Core/Components/AnchoredRegion/FluentAnchoredRegion.razor.cs:line 169
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Likely from:
https://github.com/dotnet/aspire/blob/0587e4872087512b5df5b9c894276cdf69df87d5/src/Aspire.Dashboard/Components/Pages/Resources.razor#L58

Which runs the code from fluentui and looks like `container` is null in that code:
https://github.com/microsoft/fluentui-blazor/blob/80ad64bc713a0962374f9c70ce07d7d1ce813b3f/src/Core/Components/AnchoredRegion/FluentAnchoredRegion.razor.js#L5

I don't know how to consistently repro this as it doesn't happen every time. Also don't know if it's a dashboard issue, blazor issue, or fluent ui issue, as I'm not very familiar with this area.

**Comment by adamint** [comment]
@BrennanConroy are you still running into this issue? I am unable to reproduce it at all.

**Comment by BrennanConroy** [comment]
I don't actively develop with aspire. So no, I have not hit this issue in a while, but I also have not tried in a long time.
