### ISSUE TITLE
Error streaming logs for aspire-dashboard-*

### ISSUE THREAD

**Issue by vaundrex** [dotnet/aspire#5536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I add a package reference in the host project to Aspire.Hosting.PostgreSQL the Aspire dashboard throws an error on startup in the Terminal Window that opens but the app seems to still run just fine.

### Expected Behavior

Without the package reference no error is shown in he debugger windowt

### Steps To Reproduce

Add this package reference to the host project
<PackageReference Include="Aspire.Hosting.PostgreSQL" Version="8.2.0" />

### Exceptions (if any)

```
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
fail: Aspire.Hosting.Dcp.ApplicationExecutor[0]
      Error streaming logs for aspire-dashboard-bknbeead.
      k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'BadRequest', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Timestamps are not supported yet for Executable logs","reason":"BadRequest","code":400}

         at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
         at Aspire.Hosting.Dcp.DcpKubernetesClient.ReadSubResourceAsStreamAsync(String group, String version, String plural, String name, String subResource, String namespaceParameter, IReadOnlyCollection`1 queryParams, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpKubernetesClient.cs:line 71
         at Aspire.Hosting.Dcp.KubernetesService.<>c__DisplayClass20_0`1.<<GetLogStreamAsync>b__0>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 243
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 308
         at Aspire.Hosting.Dcp.ResourceLogSource`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/ResourceLogSource.cs:line 49
         at Aspire.Hosting.Dcp.ResourceLogSource`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass41_1`1.<<StartLogStream>b__1>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 493
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass41_1`1.<<StartLogStream>b__1>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 493
```

### .NET Version info

.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.34944930
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.35027.167
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

### Anything else?

Aspire.Hosting.AppHost (8.0.0)
Visual Studio 2022 Community

**Comment by sheinema** [comment]
I had this same error message and noticed thanks to @arslanmusta that I was using Aspire.Hosting.AppHost Version="8.1.0" but had installed Aspire.Hosting.RabbitMQ Version="8.2.0". This mismatch was causing the issue.

**Comment by dbreshears** [comment]
This seems like it can be closed.   Shouldn't be an issue with the latest Aspire workload.
