### ISSUE TITLE
AppHost project crashes on startup: System.UriFormatException: Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by SapiensAnatis** [dotnet/aspire#5587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey, just trying to integrate Aspire into my existing solution. The first time I tried it, it threw this on startup:
```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
```
I eventually narrowed this down to using an `applicationUrl` of `"http://*:80"` in my web API's `launchSettings.json`. I had this set to listen on all IP addresses as I need to connect to my web API from my smartphone.

### Expected Behavior

This is my first time using Aspire so I don't have the context to know why it reads `launchSettings`, but perhaps these URLs could be skipped. I think in any case the error message could be improved, as I only narrowed it to `launchSettings` by checking the Aspire source code.

### Steps To Reproduce

1. Create new Web API project
2. Set `applicationUrl` to `http://*:80` in the web API's `launchSettings.json`:

```json
{
    "$schema": "https://json.schemastore.org/launchsettings.json",
    "profiles": {
        "DragaliaAPI": {
            "commandName": "Project",
            "environmentVariables": {
                "ASPNETCORE_ENVIRONMENT": "Development",
            },
            "applicationUrl": "http://*:80"
        }
    }
}
```

3. Create new Aspire app host with this configuration:

```cs
var builder = DistributedApplication.CreateBuilder(args);

builder.AddProject<Projects.DragaliaAPI>("dragaliaapi");

builder.Build().Run();
```

4. Crash

### Exceptions (if any)

```
Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Aspire.Hosting.ProjectResourceBuilderExtensions.WithProjectDefaults(IResourceBuilder`1 builder, ProjectResourceOptions options) in /_/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs:line 407
   at Aspire.Hosting.ProjectResourceBuilderExtensions.AddProject[TProject](IDistributedApplicationBuilder builder, String name, Action`1 configure) in /_/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs:line 216
   at Aspire.Hosting.ProjectResourceBuilderExtensions.AddProject[TProject](IDistributedApplicationBuilder builder, String name) in /_/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs:line 63
   at Program.<Main>$(String[] args) in C:\Users\jay0\Projects\Dawnshard\AppHost\Program.cs:line 3
```

### .NET Version info

```
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.57f7c351
 MSBuild version:   17.11.4+37eb419ad
```

### Anything else?

`Aspire.Hosting.AppHost` v8.2.0.

**Comment by davidfowl** [comment]
http://*:80 looks to be the problem.
