### ISSUE TITLE
[playground-tests] Flaky `EventHubs` test in `TestEndpointsReturnOk`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#5959]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=818717
Build error leg or test failing: Aspire.Playground.Tests.AppHostTests.Aspire.Playground.Tests.AppHostTests.TestEndpointsReturnOk
Pull request: N/A

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": " Timed out waiting for the consumer message to be logged: 'Hello, from /test sent via producerClient'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by radical** [comment]
On the [last build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=824830) the `consumer` shutdown with this exception:
```
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      System.AggregateException: One or more errors occurred. (The messaging entity 'sb://emulatorns1.eventhubs.emulator.net/hub' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  (hub).  For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot)
       ---> Azure.Messaging.EventHubs.EventHubsException(ResourceNotFound): The messaging entity 'sb://emulatorns1.eventhubs.emulator.net/hub' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  (hub).  For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot
         at Azure.Messaging.EventHubs.AmqpError.ThrowIfErrorResponse(AmqpMessage response, String eventHubName)
         at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
         at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
         at Azure.Messaging.EventHubs.EventHubConnection.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
         at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.ValidateEventHubsConnectionAsync(CancellationToken cancellationToken)
         at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.ValidateEventHubsConnectionAsync(CancellationToken cancellationToken)
         at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.ValidateProcessingPreconditions(CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.StartProcessingInternalAsync(Boolean async, CancellationToken cancellationToken)
         at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.StartProcessingAsync(CancellationToken cancellationToken)
         at Azure.Messaging.EventHubs.EventProcessorClient.StartProcessingInternalAsync(Boolean async, CancellationToken cancellationToken)
         at Azure.Messaging.EventHubs.EventProcessorClient.StartProcessingAsync(CancellationToken cancellationToken)
         at EventHubsConsumer.Processor.ExecuteAsync(CancellationToken stoppingToken) in /datadisks/disk1/work/ABF7093F/w/B02B09B0/e/playground/AspireEventHub/EventHubsConsumer/Processor.cs:line 44
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```
.. specifically - `Azure.Messaging.EventHubs.EventHubsException(ResourceNotFound): The messaging entity 'sb://emulatorns1.eventhubs.emulator.net/hub' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  (hub).  For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot`.

.. but the test keeps waiting for the message from the `consumer`, and times out.

We should fix the tests to also fail earlier, so the xunit test reports show the real cause, or closer to it.

cc @davidfowl @eerhardt

**Comment by davidfowl** [comment]
There's a bug in the consumer, I think this is a resiliency problem.

**Comment by radical** [comment]
### Last 10 failures:
| Run date | Build Type | Test Name | OS |
| -------- | ---------- | --------- | -- |

### Summary

| Last 24 hrs | Last 7 days | Last 30 days | Most Affected OS | Failure Rate |
| ----------- | ----------- | ------------ | ---------------- | ------------ |
| 0 | 0 | 0 | N/A | 0.0% |

🔍 Matched by test name (`Aspire.Playground.Tests.AppHostTests.TestEndpointsReturnOk`) and error message substring

-- Updated on 5/13/2026 10:39:01 PM UTC

**Comment by radical** [comment]
[automated] The CI shepherd found this test quarantined against a different issue.

**Current source evidence** (revision `6f39f17e504bcb5239799ff7d5cbd64b808ffef6`):
- `Aspire.Playground.Tests.AppHostTests.TestEndpointsReturnOk` — `tests/Aspire.Playground.Tests/AppHostTests.cs:33` — `[QuarantinedTest]` links https://github.com/microsoft/aspire/issues/6866

**Decision needed:** Review whether this issue duplicates https://github.com/microsoft/aspire/issues/6866. Close the duplicate or repoint the existing attribute if this issue is the canonical tracker; do not add a second quarantine for the same method.

The shepherd made no source, label, or issue-metadata change and will not close this issue on source absence.
