### ISSUE TITLE
Adding a project reference to a class library breaks deployment to Azure with azd up or deploy

### ISSUE THREAD

**Issue by NickDrouin** [dotnet/aspire#6092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When adding a project reference to a class library to an Aspire enabled service like the Aspire starter app's ApiService, it no longer deploys to Azure Container Apps.  The failure points to a null value.

Full repro below.

### Expected Behavior

App deploys normally, as it did before.

### Steps To Reproduce

```bash
> dotnet new aspire-starter -n LibTest1
> dotnet new classlib -n LibTest1.Common
> azd auth login
>cd LibTest1.AppHost
LibTest1.AppHost> azd init
LibTest1.AppHost> azd up
[Success]

LibTest1.AppHost> cd ../LibTest1.ApiService
LibTest1.ApiService> dotnet add reference ../LibTest1.Common/LibTest1.Common.csproj
LibTest1.ApiService> cd ../LibTest1.AppHost
LibTest1.AppHost> azd up
[Fail]
```

Error:
```
ERROR: error executing step command 'deploy --all': failed deploying service 'apiservice': publishing container: dotnet publish on project 'C:\Users\REDACTED\source\repos\test\LibTest1.ApiService\LibTest1.ApiService.csproj' failed: exit code: 1, stdout: , stderr: MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\REDACTED\AppData\Local\Temp\MSBuildTemp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: C:\Users\REDACTED\AppData\Local\Temp\MSBuildTemp\MSBuild_pid-11748_b5b5da4666bb416aa7c2098764e09548.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 11748:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 2024-10-03 6:59:22 PM
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:
Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.
```

### Exceptions (if any)

```
LibTest1.AppHost> azd up --debug

PS C:\Users\REDACTED\source\repos\test\LibTest1.AppHost> azd deploy --debug
2024/10/03 19:01:16 main.go:56: azd version: 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)
2024/10/03 19:01:16 main.go:214: using cached latest version: 1.10.1 (expires on: 2024-10-04T13:32:56Z)
2024/10/03 19:01:16 project.go:144: Reading project from file 'C:\Users\REDACTED\source\repos\test\LibTest1.AppHost\azure.yaml'
2024/10/03 19:01:16 middleware.go:108: running middleware 'debug'
2024/10/03 19:01:16 middleware.go:108: running middleware 'ux'
2024/10/03 19:01:16 middleware.go:108: running middleware 'experimentation'
2024/10/03 19:01:16 experimentation.go:42: assignment context: 0g5ad841:76970;
2024/10/03 19:01:16 middleware.go:108: running middleware 'telemetry'
2024/10/03 19:01:16 telemetry.go:43: TraceID: ab5a40cb5d80b8b0bb0b830300af0a02
2024/10/03 19:01:16 middleware.go:108: running middleware 'hooks'
2024/10/03 19:01:16 project.go:144: Reading project from file 'C:\Users\REDACTED\source\repos\test\LibTest1.AppHost\azure.yaml'
2024/10/03 19:01:16 command_runner.go:307: Run exec: 'dotnet msbuild C:\Users\REDACTED\source\repos\test\LibTest1.AppHost\LibTest1.AppHost.csproj --getProperty:IsAspireHost' , exit code: 0
Additional env:
   DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE=<redacted>
-------------------------------------stdout-------------------------------------------
true
  |    ===| Analyzing Aspire Application (this might take a moment...)2024/10/03 19:01:19 command_runner.go:307: Run exec: 'dotnet run --project LibTest1.AppHost.csproj --publisher manifest --output-path C:\Users\REDACTED\AppData\Local\Temp\azd-provision602135209\apphost-manifest.json' , exit code: 0
-------------------------------------stdout-------------------------------------------
Building...
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.2.1+137e8dcae0a7b22c05f48c4e7a5d36fe3f00a8d7
info: Aspire.Hosting.Publishing.ManifestPublisher[0]
      Published manifest to: C:\Users\REDACTED\AppData\Local\Temp\azd-provision602135209\apphost-manifest.json
2024/10/03 19:01:19 hooks.go:143: service 'apiservice' does not require any command hooks.
2024/10/03 19:01:19 hooks.go:143: service 'webfrontend' does not require any command hooks.
2024/10/03 19:01:19 hooks.go:78: azd project is not available or does not contain any command hooks, skipping command hook registrations.
2024/10/03 19:01:19 command_runner.go:307: Run exec: 'dotnet --version' , exit code: 0
Additional env:
   DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE=<redacted>
-------------------------------------stdout-------------------------------------------
8.0.400
2024/10/03 19:01:19 dotnet.go:69: dotnet version: 8.0.400
2024/10/03 19:01:19 ensure.go:47: Skipping install check for '.NET CLI'. It was previously confirmed.

Deploying services (azd deploy)

  |==     | Deploying service apiservice2024/10/03 19:01:19 main.go:50: Retry: =====> Try=1
2024/10/03 19:01:19 main.go:50: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://management.azure.com/subscriptions/REDACTED/resourcegroups?%24filter=REDACTED&api-version=2021-04-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources.ResourceGroupsClient/v1.1.1 (go1.23.0 X:loopvar; Windows_NT),azdev/1.10.1 (Go go1.23.0 X:loopvar; windows/amd64)
   X-Ms-Correlation-Request-Id: ab5a40cb5d80b8b0bb0b830300af0a02

2024/10/03 19:01:19 main.go:50: Response: ==> REQUEST/RESPONSE (Try=1/153.2633ms, OpTime=153.2633ms) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/REDACTED/resourcegroups?%24filter=REDACTED&api-version=2021-04-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources.ResourceGroupsClient/v1.1.1 (go1.23.0 X:loopvar; Windows_NT),azdev/1.10.1 (Go go1.23.0 X:loopvar; windows/amd64)
   X-Ms-Correlation-Request-Id: ab5a40cb5d80b8b0bb0b830300af0a02
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-cache
   Content-Length: 267
   Content-Type: application/json; charset=utf-8
   Date: Thu, 03 Oct 2024 23:01:19 GMT
   Expires: -1
   Pragma: no-cache
   Strict-Transport-Security: REDACTED
   X-Cache: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: ab5a40cb5d80b8b0bb0b830300af0a02
   X-Ms-Ratelimit-Remaining-Subscription-Global-Reads: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Reads: REDACTED
   X-Ms-Request-Id: a0885378-e6a6-4a17-8e38-16a337483ed9
   X-Ms-Routing-Request-Id: REDACTED
   X-Msedge-Ref: REDACTED

2024/10/03 19:01:19 main.go:50: Retry: response 200
2024/10/03 19:01:19 main.go:50: Retry: exit due to non-retriable status code
  |       | Deploying service apiservice (Logging in to registry)2024/10/03 19:01:19 main.go:50: Retry: =====> Try=1
2024/10/03 19:01:19 main.go:50: Request: ==> OUTGOING REQUEST (Try=1)
   POST https://acrglajh3yxyupky.azurecr.io/oauth2/exchange
   Content-Type: application/x-www-form-urlencoded
   User-Agent: azsdk-go-azd-acr/1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9) (go1.23.0 X:loopvar; Windows_NT),azdev/1.10.1 (Go go1.23.0 X:loopvar; windows/amd64)
   X-Ms-Correlation-Request-Id: REDACTED

  |=      | Deploying service apiservice (Logging in to registry)2024/10/03 19:01:19 main.go:50: Response: ==> REQUEST/RESPONSE (Try=1/195.0879ms, OpTime=195.9225ms) -- RESPONSE RECEIVED
   POST https://acrglajh3yxyupky.azurecr.io/oauth2/exchange
   Content-Type: application/x-www-form-urlencoded
   User-Agent: azsdk-go-azd-acr/1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9) (go1.23.0 X:loopvar; Windows_NT),azdev/1.10.1 (Go go1.23.0 X:loopvar; windows/amd64)
   X-Ms-Correlation-Request-Id: REDACTED
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Connection: keep-alive
   Content-Type: application/json; charset=utf-8
   Date: Thu, 03 Oct 2024 23:01:19 GMT
   Server: AzureContainerRegistry
   Strict-Transport-Security: REDACTED
   X-Ms-Correlation-Request-Id: REDACTED
   X-Ms-Ratelimit-Remaining-Calls-Per-Second: REDACTED

2024/10/03 19:01:19 main.go:50: Retry: response 200
2024/10/03 19:01:19 main.go:50: Retry: exit due to non-retriable status code
  |====   | Deploying service apiservice (Pushing container image)2024/10/03 19:01:21 command_runner.go:307: Run exec: 'dotnet publish C:\Users\REDACTED\source\repos\test\LibTest1.ApiService\LibTest1.ApiService.csproj -r linux-x64 -c Release /t:PublishContainer -p:ContainerRepository=libtest1.apphost/apiservice-libtest1 -p:ContainerImageTag=azd-deploy-1727996479 -p:ContainerRegistry=<redacted> --getProperty:GeneratedContainerConfiguration' , exit code: 1
Additional env:
   SDK_CONTAINER_REGISTRY_UNAME=<redacted>
   SDK_CONTAINER_REGISTRY_PWORD=<redacted>
-------------------------------------stderr-------------------------------------------
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\REDACTED\AppData\Local\Temp\MSBuildTemp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: C:\Users\REDACTED\AppData\Local\Temp\MSBuildTemp\MSBuild_pid-33332_5968af18d2584a9a86c0847580e1e96e.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 33332:
MSBUILD : error MSB4166: ====================<redacted>
MSBUILD : error MSB4166: 2024-10-03 7:01:20 PM
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ==================<redacted>
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:
Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.
  (x) Failed: Deploying service apiservice

ERROR: failed deploying service 'apiservice': publishing container: dotnet publish on project 'C:\Users\REDACTED\source\repos\test\LibTest1.ApiService\LibTest1.ApiService.csproj' failed: exit code: 1, stdout: , stderr: MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\REDACTED\AppData\Local\Temp\MSBuildTemp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: C:\Users\REDACTED\AppData\Local\Temp\MSBuildTemp\MSBuild_pid-33332_5968af18d2584a9a86c0847580e1e96e.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 33332:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 2024-10-03 7:01:20 PM
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:
Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.


```

### .NET Version info

```
.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.2772ffde
 MSBuild version:   17.11.3+0c8610977

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 8.0.400, VS 17.11.35303.130
   Manifest Version:    8.2.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.1\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by NickDrouin** [comment]
Close as Duplicate of:  https://github.com/dotnet/aspire/issues/6092

**Comment by NickDrouin** [comment]
Didn't find the first issue, wrote this one, someone provided a link on discord: closing this.  Maybe a slightly different description helps the next person find the solution, which is to update the .Net SDK off of 8.0.400.
