### ISSUE TITLE
[ci] Internal build is broken

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#6165]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2554334&view=results).

```
Cannot find Aspire.ProjectTemplates*.nupkg in C:\h\w\B25B09EA\p\built-nugets. Packages found in C:\h\w\B25B09EA\p\built-nugets: Aspire.AppHost.Sdk.9.0.0-preview.4.24507.3.nupkg,...

[xUnit.net 00:00:00.50]       Stack Trace:
[xUnit.net 00:00:00.50]         /_/tests/Shared/WorkloadTesting/BuildEnvironment.cs(51,0): at Aspire.Workload.Tests.BuildEnvironment.get_ForDefaultFramework()
[xUnit.net 00:00:00.50]         /_/tests/Aspire.Workload.Tests/AppHostTemplateTests.cs(21,0): at Aspire.Workload.Tests.AppHostTemplateTests.EnsureProjectsReferencing8_1_0AppHostWithNewerWorkloadCanBuild()
[xUnit.net 00:00:00.50]         --- End of stack trace from previous location ---
[xUnit.net 00:00:00.50]         ----- Inner Stack Trace -----
[xUnit.net 00:00:00.50]            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[xUnit.net 00:00:00.50]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[xUnit.net 00:00:00.50]            at System.Threading.Tasks.Task.Wait()
[xUnit.net 00:00:00.50]         /_/tests/Shared/WorkloadTesting/BuildEnvironment.cs(244,0): at Aspire.Workload.Tests.BuildEnvironment..ctor(Boolean useSystemDotNet, TemplatesCustomHive templatesCustomHive, String sdkDirName)
[xUnit.net 00:00:00.50]         /_/tests/Shared/WorkloadTesting/BuildEnvironment.cs(43,0): at Aspire.Workload.Tests.BuildEnvironment.<>c.<.cctor>b__62_2()
[xUnit.net 00:00:00.50]            at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
[xUnit.net 00:00:00.50]            at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
[xUnit.net 00:00:00.50]            at System.Lazy`1.CreateValue()
[xUnit.net 00:00:00.50]         /_/tests/Shared/WorkloadTesting/BuildEnvironment.cs(49,0): at Aspire.Workload.Tests.BuildEnvironment.get_ForCurrentSdkAndPreviousRuntime()
[xUnit.net 00:00:00.50]         /_/tests/Shared/WorkloadTesting/BuildEnvironment.cs(57,0): at Aspire.Workload.Tests.BuildEnvironment..cctor()
[xUnit.net 00:00:00.50]         ----- Inner Stack Trace -----
[xUnit.net 00:00:00.50]         /_/tests/Shared/WorkloadTesting/TemplateCustomHive.cs(99,0): at Aspire.Workload.Tests.TemplatesCustomHive.GetPackagePath(String builtNuGetsPath, String templatePackageId)
[xUnit.net 00:00:00.50]         /_/tests/Shared/WorkloadTesting/TemplateCustomHive.cs(55,0): at Aspire.Workload.Tests.TemplatesCustomHive.<>c__DisplayClass18_0.<EnsureInstalledAsync>b__0(String id)
[xUnit.net 00:00:00.50]            at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
[xUnit.net 00:00:00.50]            at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
[xUnit.net 00:00:00.50]         /_/tests/Shared/WorkloadTesting/TemplateCustomHive.cs(80,0): at Aspire.Workload.Tests.TemplatesCustomHive.EnsureInstalledAsync(BuildEnvironment buildEnvironment)
```

This is failing because the regex in the workload tests fails to match the preview version in the package filename.

**Comment by joperezr** [comment]
Looks like this is fixed now. Closing for now.
