### ISSUE TITLE
[WebToolsE2E][Aspire] Refreshing the browser multiple times when running 9.0 aspire project, an error occurred in CMD.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6373]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2
2. Install VS 17.12 P4 candidate

**REPRO STEPS**
1. Create .Net Aspire 9 Starter App
2. Build solution and run the project
3. Click the refresh button in the browser multiple times

**ACTUAL**
An error occurred in CMD
![Image](https://github.com/user-attachments/assets/54c9e1c1-3aff-4cdb-a13c-c9cb4f028c0e)
```
Grpc.AspNetCore.Server.ServerCallHandler[6]
     Error when executing service method 'GetApplicationInformation'.
     System.IO.IOException: The client reset the request stream.
        at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.ReadAsync(CancellationToken cancellationToken)
        at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer)
        at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
        at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```
**EXPECTED**
Can refresh the browser multiple times without an error in CMD.

**Comment by joperezr** [comment]
cc: @JamesNK any ideas if this could be a quick fix?

**Comment by JamesNK** [comment]
It will be fixed with a gRPC update. Won't be available in time for 9.0.

**Comment by JamesNK** [comment]
I believe this was fixed with https://github.com/dotnet/aspire/pull/6752

**Comment by vmykagapuz** [comment]
I verified that this issue is fixed in 17.13 GA with aspire 9.0. Thanks
