### ISSUE TITLE
AddPythonApp crashes because it does not double quote paths with spaces in arguments list

### ISSUE THREAD

**Issue by DiAifU** [dotnet/aspire#6841]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

AddPythonApp does not double quote paths it passes as arguments, especially the Python executable in venv when passed to the OpenTelemetry instrumentation executable.
Example :
![Image](https://github.com/user-attachments/assets/5f315dae-efb8-427d-b241-d1783ff20abe)

This results in the python script not starting because the argument list is not parsed correctly when there are spaces in the full path.
![Image](https://github.com/user-attachments/assets/938c2d8c-c026-4bf5-a6fc-944c2eb006f9)

### Expected Behavior

The path should double quoted within the argument list to avoid this issue.

### .NET Version info

SDK .NET :
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.3068a692
 MSBuild version:   17.12.7+5b8665660

### Anything else?

Aspire 9.0.0 and Aspire.Hosting.Python 9.0.0

**Comment by eerhardt** [comment]
I tried to simply double quote the path in https://github.com/dotnet/aspire/commit/626f7435fd06d31086692317923a615d5a2dcf10.

However, things aren't working when I do that. The app fails to run:

```
 Traceback (most recent call last):
   File "<frozen runpy>", line 198, in _run_module_as_main
   File "<frozen runpy>", line 88, in _run_code
   File "D:\My Temp\AspireWithPython\InstrumentedPythonProject\.venv\Scripts\opentelemetry-instrument.exe\__main__.py", line 7, in <module>
     sys.exit(run())
              ~~~^^
   File "D:\git\aspire-samples\samples\AspireWithPython\InstrumentedPythonProject\.venv\Lib\site-packages\opentelemetry\instrumentation\auto_instrumentation\__init__.py", line 112, in run
     execl(executable, executable, *args.command_args)
     ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "<frozen os>", line 579, in execl
 TypeError: execv: path should be string, bytes or os.PathLike, not NoneType
```

**Comment by eerhardt** [comment]
Trying to do this outside of Aspire results in the same behavior as originally noted in the top post:

```shell
D:\My Temp\AspireWithPython\InstrumentedPythonProject>.venv\Scripts\opentelemetry-instrument.exe --traces_exporter otlp --logs_exporter console,otlp --metrics_exporter otlp "D:\My Temp\AspireWithPython\InstrumentedPythonProject\.venv\Scripts\python.exe" app.py

D:\My: can't open file 'D:\\My Temp\\AspireWithPython\\InstrumentedPythonProject\\Temp\\AspireWithPython\\InstrumentedPythonProject\\.venv\\Scripts\\python.exe': [Errno 2] No such file or directory
```

I believe this is an argument parsing issue in `opentelemetry-instrument.exe`.

I've opened [Executing opentelemetry-instrument.exe on an app with a path with space doesn't work (open-telemetry/opentelemetry-python-contrib#3238)](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/3238) for this.

**Comment by eerhardt** [comment]
I did more digging, and it looks like we shouldn't double quote paths at all. This is handled for us via DCP. We keep each argument separate in a `string[]` in the ExecutableSpec:

https://github.com/dotnet/aspire/blob/c1c96662138475a786e85285a4782b44bed64013/src/Aspire.Hosting/Dcp/Model/Executable.cs#L24-L28

DCP takes these separate args and will combine them correctly if an individual arg contains a space or tab.

So I'm closing this issue as .NET Aspire code is doing the correct thing. The underlying issue is in opentelemetry-instrument.exe - https://github.com/open-telemetry/opentelemetry-python-contrib/issues/3238.
