### ISSUE TITLE
AddKeyedNpgsqlDataSource fails on Aspire 9: MissingMethodException

### ISSUE THREAD

**Issue by dvlprx** [dotnet/aspire#6852]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

After upgrading from .Net 8 to .Net 9 / Aspire 9, the following line fails:

```
public static WebApplication Build(this WebApplicationBuilder builder)
{
   ...
   builder.AddKeyedNpgsqlDataSource("myPostgresInstance");
   ...
}
```

This is called when starting an asp net core app, that needs to talk to postgres through the keyed npgsql dataSource.

### Expected Behavior

The keyed npgsql dataSource is added to the di-container.

### Steps To Reproduce

1. Create an asp net core app
2. host the app with aspire
3. call builder.AddKeyedNpgsqlDataSource(..)

### Exceptions (if any)

System.MissingMethodException: 'Method not found: 'OpenTelemetry.Trace.TracerProviderBuilder Npgsql.TracerProviderBuilderExtensions.AddNpgsql(OpenTelemetry.Trace.TracerProviderBuilder, System.Action`1<Npgsql.NpgsqlTracingOptions>)'.'

StackTrace:

  ```
at Microsoft.Extensions.Hosting.AspirePostgreSqlNpgsqlExtensions.<>c.<AddNpgsqlDataSource>b__3_1(TracerProviderBuilder tracerProviderBuilder)
   at OpenTelemetry.OpenTelemetryBuilderSdkExtensions.WithTracing(IOpenTelemetryBuilder builder, Action`1 configure)
   at OpenTelemetry.OpenTelemetryBuilder.WithTracing(Action`1 configure)
   at Microsoft.Extensions.Hosting.AspirePostgreSqlNpgsqlExtensions.AddNpgsqlDataSource(IHostApplicationBuilder builder, Action`1 configureSettings, String connectionName, Object serviceKey, Action`1 configureDataSourceBuilder)
   at Microsoft.Extensions.Hosting.AspirePostgreSqlNpgsqlExtensions.AddKeyedNpgsqlDataSource(IHostApplicationBuilder builder, String name, Action`1 configureSettings, Action`1 configureDataSourceBuilder)
   at 
```
...

### .NET Version info

.Net 9

**Comment by ElanHasson** [comment]
Same issue I think, latest everything.
```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'OpenTelemetry.Trace.TracerProviderBuilder Npgsql.TracerProviderBuilderExtensions.AddNpgsql(OpenTelemetry.Trace.TracerProviderBuilder, System.Action`1<Npgsql.NpgsqlTracingOptions>)'.
  Source=Aspire.Npgsql
  StackTrace:
   at Microsoft.Extensions.Hosting.AspirePostgreSqlNpgsqlExtensions.<>c.<AddNpgsqlDataSource>b__3_1(TracerProviderBuilder tracerProviderBuilder) in /_/src/Components/Aspire.Npgsql/AspirePostgreSqlNpgsqlExtensions.cs:line 97
   at OpenTelemetry.OpenTelemetryBuilderSdkExtensions.WithTracing(IOpenTelemetryBuilder builder, Action`1 configure)
   at OpenTelemetry.OpenTelemetryBuilder.WithTracing(Action`1 configure)
   at Microsoft.Extensions.Hosting.AspirePostgreSqlNpgsqlExtensions.AddNpgsqlDataSource(IHostApplicationBuilder builder, Action`1 configureSettings, String connectionName, Object serviceKey, Action`1 configureDataSourceBuilder) in /_/src/Components/Aspire.Npgsql/AspirePostgreSqlNpgsqlExtensions.cs:line 93
   at Microsoft.Extensions.Hosting.AspirePostgreSqlNpgsqlExtensions.AddNpgsqlDataSource(IHostApplicationBuilder builder, String connectionName, Action`1 configureSettings, Action`1 configureDataSourceBuilder) in /_/src/Components/Aspire.Npgsql/AspirePostgreSqlNpgsqlExtensions.cs:line 35
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\elan\Source\repos\InfinityFlowApp\system\src\InfinityFlow.Hosting.WebAPI\Program.cs:line 47
   at Program.<Main>(String[] args)
```

![Image](https://github.com/user-attachments/assets/baf9f80e-b01c-4e2d-8aee-92c120bbbdde)

**Comment by JoaoLucasSR** [comment]
Same issue here

![Image](https://github.com/user-attachments/assets/345af0dd-f0f2-45d8-95d3-75a432de7caa)

`System.MissingMethodException: Method not found: 'OpenTelemetry.Trace.TracerProviderBuilder Npgsql.TracerProviderBuilderExtensions.AddNpgsql(OpenTelemetry.Trace.TracerProviderBuilder, System.Action`1<Npgsql.NpgsqlTracingOptions>)'.
   at Microsoft.Extensions.Hosting.AspireEFPostgreSqlExtensions.<>c__4`1.<ConfigureInstrumentation>b__4_1(TracerProviderBuilder tracerProviderBuilder)
   at OpenTelemetry.OpenTelemetryBuilderSdkExtensions.WithTracing(IOpenTelemetryBuilder builder, Action`1 configure)
   at OpenTelemetry.OpenTelemetryBuilder.WithTracing(Action`1 configure)
   at Microsoft.Extensions.Hosting.AspireEFPostgreSqlExtensions.ConfigureInstrumentation[TContext](IHostApplicationBuilder builder, NpgsqlEntityFrameworkCorePostgreSQLSettings settings) in /_/src/Components/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL/AspireEFPostgreSqlExtensions.cs:line 200
   at Microsoft.Extensions.Hosting.AspireEFPostgreSqlExtensions.AddNpgsqlDbContext[TContext](IHostApplicationBuilder builder, String connectionName, Action`1 configureSettings, Action`1 configureDbContextOptions) in /_/src/Components/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL/AspireEFPostgreSqlExtensions.cs:line 69
   at Program.<Main>$(String[] args) in /home/jlribeiro/Repos/Ellevese/Ellevese.ApiService/Program.cs:line 28
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass13_0.<ResolveServiceProviderFactory>b__3(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
`

**Comment by davidfowl** [comment]
cc @eerhardt

**Comment by eerhardt** [comment]
This issue was caused by a breaking change in Npgsql.OpenTelemetry:

https://github.com/npgsql/npgsql/commit/7949c45e2957da3641d73531e7efe931e2868fe4

@roji - was the breaking change intentional? I didn't see any mention of it in the PR - [Add an ability to filter and enrich tracing activities (npgsql/npgsql#5853)](https://github.com/npgsql/npgsql/pull/5853) nor in https://www.npgsql.org/doc/release-notes/9.0.html#breaking-changes.

**Comment by roji** [comment]
@eerhardt hey Erik, yeah - we did this binary breaking change. The 2nd parameter to AddNpgsql() - the `Action<NpgsqlTracingOptions>` - was removed, because we now manage tracing options on the data source level, allowing different data sources to be configured with different tracing options (that's really where this kind of customization belongs). And since NpgsqlTracingOptions was previously empty (it was just a placeholder in case we add stuff in the future), we decided to remove it.

Do you need to have the same Aspire component working against different versions of Npgsql?

**Comment by ElanHasson** [comment]
@roji  / @eerhardt what is suggested the work around here until Aspire adapts?

**Comment by eerhardt** [comment]
That seems like an OK workaround for now. I'm not aware of a better way for now.
