### ISSUE TITLE
dotnet publish to folder for Aspire.Hosting.Testing projects

### ISSUE THREAD

**Issue by Culan** [dotnet/aspire#6857]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In our build pipeline we have separated the build from the test execution to enable all our test projects run in parallel on multiple test agents.

To accomplish this we have this workflow:

- dotnet build the solution
- dotnet publish each of the test projects with the --no-build option
- store the output of the publish
- check and react to any build warnings (here the building of the full solution helps because we also have some sample projects so this will cover all for us)

If this is fine we move to the test stage where we:

- For every test project allocate one of the test agents.
- Download the artifact from previous step
- Execute the tests

Obviously we want only one build to happen and we want our tests run on that particular build so to save time and space, the test agent doesn't even have to clone the repo, it just gets everything from the dotnet publish and then executes dotnet test on that dll.

When we try to run the tests we are hitting a DirectoryNotFoundException with an directory hinting of the agent who build it.

I've researched current issues there is none pointing exactly to my use-case but i found some hints:
https://github.com/dotnet/aspire/issues/1704 - Here DamianEdwards is saying that during compile time the path to DCP from the AssemblyMetadata attributes stamped onto the AppHost

So i had a quick check on my apphost:

AssemblyMetadataAttribute: dcpclipath value: /home/vsts/.nuget/packages/aspire.hosting.orchestration.linux-x64/9.0.0/tools/dcp
AssemblyMetadataAttribute: dcpextensionpaths value: /home/vsts/.nuget/packages/aspire.hosting.orchestration.linux-x64/9.0.0/tools/ext/
AssemblyMetadataAttribute: dcpbinpath value: /home/vsts/.nuget/packages/aspire.hosting.orchestration.linux-x64/9.0.0/tools/ext/bin/
AssemblyMetadataAttribute: apphostprojectpath value: /home/vsts/work/1/s/Source/Gateway.AppHost
AssemblyMetadataAttribute: apphostprojectname value: Gateway.AppHost.csproj
AssemblyMetadataAttribute: aspiredashboardpath value: /home/vsts/.nuget/packages/aspire.dashboard.sdk.linux-x64/9.0.0/tools/Aspire.Dashboard

Here we can see references to the build host's nuget cache and the sourcecode.

I guess that what i'm after is a dotnet publish to folder functionality that would remove any link towards the sourcecode and the build host.

### Describe the solution you'd like

dotnet publish to folder that creates a package that can run independently.

**Comment by Culan** [comment]
The same behavior can be observed locally with aspire-samples:

- Clone the repo aspire-samples
- `dotnet build tests\SamplesTests.sln -c Release -f net9.0`
- `dotnet publish tests\SamplesIntegrationTests\SamplesIntegrationTests.csproj --no-build -c Release -f net9.0`
- Rename the aspire-samples folder (this simulates the agent switch in my case)
- `dotnet test tests\SamplesIntegrationTests\SamplesIntegrationTests.csproj --no-build`

**Comment by davidfowl** [comment]
It's unclear if we would support this, the testing relies on access to the source.

**Comment by afscrome** [comment]
If not supported, could we make this fail with a clearer message saying that the tests must be run from the path they were built in, rather than failing with a directory not found error?

With the dotnet testing platforming supporting dotnet publish for tests natively, it doesn't seem unreasonable that developers would think aspire supports tests published this way.

**Comment by davidfowl** [comment]
It's uncommon but not unheard of which means we aren't going to rush to support it (amongst the other issues that are blocking more people). The issue is left open to see how many people run into this problem (or potentially for someone to contribute to unblock).

**Comment by kt-danmendonca** [comment]
To understand the extent of this issue, we're encountering a problem where, due to network security, our agents connected to Azure resources are unable to build the projects. Consequently, we build the project on one agent and then transfer the contents to another. However, when the other agent attempts to run the project, it still references the original build path from the different agent. This issue is occurring in our DevOps Azure Pipelines.

**Comment by MattKotsenas** [comment]
We're bumping into this as well, where we build on an x64 machine but want to run the tests on arm64. We're in the process of adopting Microsoft.Testing.Platform so that we can do this for other tests, but for Aspire we re-build on the test machine to sidestep these types of issues.

**Comment by chuanboz** [comment]
We meet similar issue with cloud test to run on another VM different than the build machine. The error message we meet is project file was not found when determine the launch setting for AddProject.

Aspire.Hosting.DistributedApplicationException : Project file 'C:\__w\1\s\src\Directory.Api\Directory.Api.csproj' was not found.

> at Aspire.Hosting.LaunchProfileExtensions.GetLaunchSettings(IProjectMetadata projectMetadata, String resourceName) in /_/src/Shared/LaunchProfiles/LaunchProfileExtensions.cs:line 77
at Aspire.Hosting.LaunchProfileExtensions.GetLaunchSettings(ProjectResource projectResource) in /_/src/Shared/LaunchProfiles/LaunchProfileExtensions.cs:line 28
at Aspire.Hosting.LaunchProfileExtensions.TrySelectLaunchProfileByOrder(ProjectResource projectResource, String& launchProfileName) in /_/src/Shared/LaunchProfiles/LaunchProfileExtensions.cs:line 117
at Aspire.Hosting.LaunchProfileExtensions.SelectLaunchProfileName(ProjectResource projectResource) in /_/src/Shared/LaunchProfiles/LaunchProfileExtensions.cs:line 179
at Aspire.Hosting.LaunchProfileExtensions.GetEffectiveLaunchProfile(ProjectResource projectResource, Boolean throwIfNotFound) in /_/src/Shared/LaunchProfiles/LaunchProfileExtensions.cs:line 33
at Aspire.Hosting.ProjectResourceBuilderExtensions.WithProjectDefaults(IResourceBuilder`1 builder, ProjectResourceOptions options) in /_/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs:line 341
at Aspire.Hosting.ProjectResourceBuilderExtensions.AddProject[TProject](IDistributedApplicationBuilder builder, String name, Action`1 configure) in /_/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs:line 230
at Aspire.Hosting.ProjectResourceBuilderExtensions.AddProject[TProject](IDistributedApplicationBuilder builder, String name) in /_/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs:line 63
at Program.<Main>$(String[] args) in C:\__w\1\s\src\MiniCPC.AppHost\Program.cs:line 8
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
at Aspire.Hosting.Testing.DistributedApplicationEntryPointInvoker.EntryPointInvoker.InvokeAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting.Testing/DistributedApplicationEntryPointInvoker.cs:line 132
at Aspire.Hosting.Testing.DistributedApplicationEntryPointInvoker.<>c__DisplayClass0_0.<<ResolveEntryPoint>b__0>d.MoveNext() in /_/src/Aspire.Hosting.Testing/DistributedApplicationEntryPointInvoker.cs:line 39
--- End of stack trace from previous location ---
at Aspire.Hosting.Testing.DistributedApplicationFactory.InvokeEntryPoint(Func`3 factory) in /_/src/Aspire.Hosting.Testing/DistributedApplicationFactory.cs:line 427
at Aspire.Hosting.Testing.DistributedApplicationFactory.ResolveBuilderAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting.Testing/DistributedApplicationFactory.cs:line 51
at Aspire.Hosting.Testing.DistributedApplicationTestingBuilder.SuspendingDistributedApplicationFactory.CreateBuilderAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting.Testing/DistributedApplicationTestingBuilder.cs:line 162
at Aspire.Hosting.Testing.DistributedApplicationTestingBuilder.CreateAsync(Type entryPoint, String[] args, Action`2 configureBuilder, CancellationToken cancellationToken) in /_/src/Aspire.Hosting.Testing/DistributedApplicationTestingBuilder.cs:line 109
at Microsoft.WindowsCloud.Aspire.TestShared.AppHostFixture`1.InitializeAsync() in C:\__w\1\s\src\AspireF5.TestShared\AppHostFixture.cs:line 21
