### ISSUE TITLE
[WebToolsE2E] [Aspire] An unhandled exception thrown failed after clicking multiple times the start and stop icon.

### ISSUE THREAD

**Issue by Coleen17** [dotnet/aspire#6860]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.12.3 [Includes aspire 9.0.0]

**REPRO STEPS**

1. Create a project > Aspire New Stater App > Framework: 9.0/8.0 > Create
2. Build and run the project.
3. Dashboard comes up > click quickly and continuously the star/stop icons. 

**ACTUAL**
The notification from the start/stop icon has an error when you clicked multiple times. 
![Image](https://github.com/user-attachments/assets/94e4a180-4c96-451f-86f8-a14f91cdf9b1)
![Image](https://github.com/user-attachments/assets/2493f531-f994-44c2-9946-944aba3688da)

EXPECTED:
No errors displayed when stopping or starting the project.

**Comment by dbreshears** [comment]
Might be already fixed, please check.   Moving to backlog as an edge case.

**Comment by dbreshears** [comment]
Thanks for looking into.   Will hold off on investigation unless this reproduces without quickly clicking back and forth on start/stop

**Comment by adamint** [comment]
I am unable to reproduce this anymore. Closing as fixed

**Comment by v-reinawang** [comment]
@adamint This issue still repro on VS 18.5 GA + latest Aspire 13.2.2. 

This issue occurs when you quickly and continuously click the start/stop icon many times. An error is appearing in the console log, and the resource page is showing as unhealthy.

Console logs:
<img width="1902" height="937" alt="Image" src="https://github.com/user-attachments/assets/85df5c5e-5686-48ce-ac1d-1f2f65eb9eca" />

```
 Error executing command 'stop'.
System.InvalidOperationException: Failed to stop resource 'apiservice-qkpkstcd'.
   at Aspire.Hosting.Dcp.DcpExecutor.StopResourceAsync(IResourceReference resourceReference, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpExecutor.cs:line 2562
   at Aspire.Hosting.Orchestrator.ApplicationOrchestrator.StopResourceAsync(String resourceName, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs:line 593
   at Aspire.Hosting.ApplicationModel.CommandsConfigurationExtensions.<>c.<<AddLifeCycleCommands>b__1_3>d.MoveNext() in /_/src/Aspire.Hosting/ApplicationModel/CommandsConfigurationExtensions.cs:line 62
--- End of stack trace from previous location ---
   at Aspire.Hosting.ApplicationModel.ResourceCommandService.ExecuteCommandCoreAsync(String resourceId, IResource resource, String commandName, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/ApplicationModel/ResourceCommandService.cs:line 161
```

Resources: 
<img width="1916" height="366" alt="Image" src="https://github.com/user-attachments/assets/5d634f63-43ec-485c-8f35-49a14e967fe1" />
