### ISSUE TITLE
"azd init" failing with "address already in use" error

### ISSUE THREAD

**Issue by dluc** [dotnet/aspire#6896]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Trying to initialize a project, `azd init` keep failing with the same error.

### Steps To Reproduce

`azd init`

### Exceptions (if any)

```
ERROR: failed to generate manifest from app host project: generating app host manifest: 

dotnet run --publisher manifest on project 'myproject.csproj' failed: exit code: 134, stdout: Using launch settings from Properties/launchSettings.json...

info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 9.0.0+01ed51919f8df692ececce51048a140615dc759d
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: myproject
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.IO.IOException: Failed to bind to address https://127.0.0.1:21103: address already in use.

       ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
       ---> System.Net.Sockets.SocketException (48): Address already in use
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
         at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Bind(EndPoint localEP)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
         [...]
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.IO.IOException: Failed to bind to address https://127.0.0.1:21103: address already in use.
       ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
       ---> System.Net.Sockets.SocketException (48): Address already in use
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
         [...]
         at Aspire.Hosting.Dashboard.DashboardServiceHost.Microsoft.Extensions.Hosting.IHostedService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dashboard/DashboardServiceHost.cs:line 201
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
, stderr: Unhandled exception. System.AggregateException: One or more errors occurred. (Failed to bind to address https://127.0.0.1:21103: address already in use.)
 ---> System.IO.IOException: Failed to bind to address https://127.0.0.1:21103: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (48): Address already in use
   [...]
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Aspire.Hosting.Dashboard.DashboardServiceHost.Microsoft.Extensions.Hosting.IHostedService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dashboard/DashboardServiceHost.cs:line 201
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|14_3(<>c__DisplayClass14_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 311
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 339
   at AppHost.Program.Main() in Program.cs:line 55
```

### .NET Version info

dotnet --version
9.0.100

### Anything else?

Aspire launchSettings:

```json
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "profiles": {
    "https": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:21100;http://localhost:21101",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "DOTNET_ENVIRONMENT": "Development",
        "DOTNET_DASHBOARD_OTLP_ENDPOINT_URL": "https://localhost:21102",
        "DOTNET_RESOURCE_SERVICE_ENDPOINT_URL": "https://localhost:21103"
      }
    },
    "http": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "http://localhost:21101",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "DOTNET_ENVIRONMENT": "Development",
        "DOTNET_DASHBOARD_OTLP_ENDPOINT_URL": "http://localhost:21102",
        "DOTNET_RESOURCE_SERVICE_ENDPOINT_URL": "http://localhost:21103"
      }
    }
  }
}
```

Target project launchsettings:

```json
{
  "profiles": {
    "http": {
      "commandName": "Project",
      "launchBrowser": false,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "http://+:9001",
        "COMPlus_ReadyToRun": "0",
        "DOTNET_ReadyToRun": "0"
      }
    }
  }
}
```

**Comment by davidfowl** [comment]
That's interesting, it shouldn't be booting up a server in publish mode, can you share the whole project?

**Comment by dluc** [comment]
> That's interesting, it shouldn't be booting up a server in publish mode, can you share the whole project?

here's a repro https://github.com/dluc/kernel-memory/blob/misc127/tools/aspire/test/Program.cs

    git clone https://github.com/dluc/kernel-memory.git km
    cd km
    git checkout misc127
    cd tools/aspire/test
    azd init --from-code

**Comment by davidfowl** [comment]
Remove —From-code from your azd init. See if that works

**Comment by dluc** [comment]
I added it here just for convenience, I hit the error with 'azd unit'

**Comment by afscrome** [comment]
Try passing command line args through to the DistributedApplicationBuilder.  Without that it won't know anything about the `--publisher manifest` argument azd appears to be running your app with.

```cs
  internal static void Main(string[] args)
    {
        var builder = DistributedApplication.CreateBuilder(args);
```

**Comment by dluc** [comment]
It turns out the problem was caused by a semi-crashed instance of Aspire still running in the background, and holding the TCP ports. Looks like "azd init" needs those ports to be free after all, perhaps something worth checking. 

After killing the faulty processes, "azd init" works fine.
