### ISSUE TITLE
[WebToolsE2E][Aspire] After starting a stopped container, there is error in Console logs: "Error executing command 'resource-start'. Aspire.Hosting.DistributedApplicationException: Failed to delete 'cache-nskrejxr' successfully before restart."

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6901]
**REFRESSION INFO**

1. Reproduced in Aspire 9.0.1

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2
2. Install VS 17.13 P3 (with Aspire 9.0.0)
3. Install Podman Desktop

**REPRO STEPS**
1. Create .NET Aspire Starter App > .NET 9.0 (Standard Term Support) > Check "Use Redis for caching" > Create
2. Build and F5
3. Stop and Start the container and navigate to Console logs.

**NOTE**
1. This issue is unstable and shows different error messages when rerunning the project.
2. This is also reproduce in .NET 8.0 framework.

**ACTUAL**
Starting the container again after stopping it shows an error message in Console logs and CMD.

CONSOLE LOGS: 
![Image](https://github.com/user-attachments/assets/2fd60c95-f257-4da1-ad13-38a0cc0e4106)
Error message:
```
Error executing command 'resource-start'.
Aspire.Hosting.DistributedApplicationException: Failed to delete 'cache-nskrejxr' successfully before restart.
   at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass81_2`1.<<StartResourceAsync>b__2>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 2133
--- End of stack trace from previous location ---
   at Polly.ResiliencePipeline.<>c.<<ExecuteAsync>b__3_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync(Func`2 callback, CancellationToken cancellationToken)
   at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass81_0.<<StartResourceAsync>g__StartExecutableOrContainerAsync|0>d`1.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 2128
--- End of stack trace from previous location ---
   at Aspire.Hosting.Dcp.ApplicationExecutor.StartResourceAsync(String resourceName, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 2074
   at Aspire.Hosting.ApplicationModel.CommandsConfigurationExtensions.<>c.<<AddLifeCycleCommands>b__3_1>d.MoveNext() in /_/src/Aspire.Hosting/ApplicationModel/CommandsConfigurationExtensions.cs:line 29
--- End of stack trace from previous location ---
   at Aspire.Hosting.Dashboard.DashboardCommandExecutor.ExecuteCommandAsync(String resourceId, ResourceCommandAnnotation annotation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dashboard/DashboardCommandExecutor.cs:line 31
   at Aspire.Hosting.Dashboard.DashboardServiceData.ExecuteCommandAsync(String resourceId, String type, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dashboard/DashboardServiceData.cs:line 99
```
CMD:
1. ![Image](https://github.com/user-attachments/assets/6aa694e2-3948-4027-8e3d-fc5e86760411)

2. ![Image](https://github.com/user-attachments/assets/d7917856-b1c8-45cc-a38b-4d4160499dcc)

**EXPECTED**
There should be no errors when stopping and starting the container.

**Comment by vmykagapuz** [comment]
Im not sure if this issue is the same as [#5972](https://github.com/dotnet/aspire/issues/5972), which was fixed in Aspire 9.1 but this issue is reproduced in Aspire 9.0.0 and 9.0.1.

**Comment by vmykagapuz** [comment]
For aspire 9.1 with the same repro steps, I also encountered this issue as mentioned in https://github.com/dotnet/aspire/issues/5972#issuecomment-2440733249
 ![Image](https://github.com/user-attachments/assets/fbb8e833-fc89-4891-9dea-560c72b0da57)

**Comment by dbreshears** [comment]
I'm not able to reproduce either of these issues in 9.1.0-preview.1.25066.1

cc: @danegsta

**Comment by vmykagapuz** [comment]
I verified that this issue does not reproduce in the latest Aspire 9.1.0-preview.1.25109.4.
