### ISSUE TITLE
[WebToolsE2E][Aspire] After refreshing the browser when running aspire 9.1 and 8.2 project at the same time, displays an authentication login and errors in CMD.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6942]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2
2. Install VS 17.12 P4 VAL (with Aspire 9.0.0)
3. Install latest Aspire 9.1.0-preview.1.24611.1

**REPRO STEPS**
1. Create .NET Aspire Starter App > .NET 9.0 (Standard Term Support) > Create
2. Build and F5 (keep the project running) 
3. Create .NET Aspire Starter App > .NET 8.0 (Long Term Support) > Aspire 8.2 > Create
4. Build and F5
5. Open the browser for 9.0 project > refresh the page

**ACTUAL**

![Image](https://github.com/user-attachments/assets/f930db65-a21f-4bfc-9191-c8aa4ed0ad7c)

![Image](https://github.com/user-attachments/assets/ea992eec-5e79-44f1-bcf9-2f239560a94a)

```
Aspire.Hosting.Dashboard.Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
       ---> System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

**EXPECTED**
Running aspire 9.0 and aspire 8.2 project at the same time, can refresh browser without errors in the cmd.

**Comment by vmykagapuz** [comment]
@balachir yes this is not a regression.

**Comment by davidfowl** [comment]
@JamesNK I thought we suppressed these logs?

**Comment by JamesNK** [comment]
I thought so too.

Having two versions of the app open will cause problems. They share an auth cookie, but they don't share a data protection key.

**Comment by leslierichardson95** [comment]
Is this a scenario we'd want to support?  I'm not sure I understand the circumstance where this scenario is needed.

**Comment by v-sherryfan** [comment]
Mixing Aspire 9.0 and Aspire 9.1 in the same solution, running both projects at the same time also requires authentication, but no error is displayed

**Comment by v-reinawang** [comment]
This scenario is no longer applicable, we can only create the latest version of Aspire 13.x.
