### ISSUE TITLE
Add support for comment handling in `launchSettings.json`

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/aspire#772]
### Description:

Seems like when `launchSettings.json` includes comments then parsing the launch profile fails.

```
   at Aspire.Hosting.LaunchProfileExtensions.TrySelectLaunchProfileFromEnvironment(ProjectResource projectResource, String& launchProfileName) in /_/src/Aspire.Hosting/Utils/LaunchProfileExtensions.cs:line 100
   at Aspire.Hosting.LaunchProfileExtensions.SelectLaunchProfileName(ProjectResource projectResource) in /_/src/Aspire.Hosting/Utils/LaunchProfileExtensions.cs:line 135
```

(Link to [`JsonCommentHandling`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsoncommenthandling?view=netcore-3.1))

### Repro steps:

- Use templates to create a new ".NET Aspire Starter Application"
- In one of the launchSettings.json, files add a line of comment.

e.g. in the `AspireXX.Web` project add the following line:
```diff
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
+    // comment
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5261",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
- F5
- `builder.Build().Run();` ends up with a unhandled exception.

<details>
 <summary> Full callstack (click to view) </summary>

```
Unhandled exception. System.AggregateException: One or more errors occurred. ('/' is invalid after a value. Expected either ',', '}', or ']'. Path: $.profiles | LineNumber: 3 | BytePositionInLine: 4.)
 ---> System.Text.Json.JsonException: '/' is invalid after a value. Expected either ',', '}', or ']'. Path: $.profiles | LineNumber: 3 | BytePositionInLine: 4.
 ---> System.Text.Json.JsonReaderException: '/' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 3 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   at Aspire.Hosting.LaunchProfileExtensions.GetLaunchSettings(IServiceMetadata serviceMetadata) in /_/src/Aspire.Hosting/Utils/LaunchProfileExtensions.cs:line 65
   at Aspire.Hosting.LaunchProfileExtensions.GetLaunchSettings(ProjectResource projectResource) in /_/src/Aspire.Hosting/Utils/LaunchProfileExtensions.cs:line 22
   at Aspire.Hosting.LaunchProfileExtensions.TrySelectLaunchProfileFromEnvironment(ProjectResource projectResource, String& launchProfileName) in /_/src/Aspire.Hosting/Utils/LaunchProfileExtensions.cs:line 100
   at Aspire.Hosting.LaunchProfileExtensions.SelectLaunchProfileName(ProjectResource projectResource) in /_/src/Aspire.Hosting/Utils/LaunchProfileExtensions.cs:line 135
   at Aspire.Hosting.Dcp.DcpDistributedApplicationLifecycleHook.PrepareServices(DistributedApplicationModel model) in /_/src/Aspire.Hosting/Dcp/DcpDistributedApplicationLifecycleHook.cs:line 33
   at Aspire.Hosting.Dcp.DcpDistributedApplicationLifecycleHook.BeforeStartAsync(DistributedApplicationModel appModel, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDistributedApplicationLifecycleHook.cs:line 22
   at Aspire.Hosting.DistributedApplication.ExecuteBeforeStartHooksAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 161
   at Aspire.Hosting.DistributedApplication.RunAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/DistributedApplication.cs:line 138
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 147
   at Program.<Main>$(String[] args) in C:\Users\maariyan\source\repos\AspireApp8\AspireApp8.AppHost\Program.cs:line 8
```
</details>

/cc @joperezr @davidfowl @luisquintanilla

**Comment by stbau04** [comment]
Is there still help wanted on this one?
