### ISSUE TITLE
ACA Deployment with Dapr

### ISSUE THREAD

**Issue by rudiv** [dotnet/aspire#838]
As Dapr is intended to be supported with Aspire (see the sample) but also has first-party support in ACA, it seems a little strange that deployment doesn't work when Dapr is added (to auto wire up the ACA Containers correctly with the service name to ACA Dapr).

Instead, when adding using `WithDaprSidecar` an Executable resource is added, and when attempting `azd up` or `azd deploy` it fails as unsupported.

```
rudi@rudismacstudio AspireTest % azd up

ERROR: generating bicep from manifest: unsupported resource type: executable.v0
```

Wrapping the `*Dapr*` methods in a DEBUG proprocessor or Development environment check also doesn't work for this either (in an attempt to ignore this and configure manually).

**Comment by DamianEdwards** [comment]
You can exclude AppHost resources from deployment by calling `.ExcludeFromManifest()` on them. That said, I agree we should make this work.

**Comment by rudiv** [comment]
Not sure `.ExcludeFromManifest()` works in this scenario, wouldn't that exclude the resource in its entirety?

```csharp
builder.AddDapr(new DaprOptions
{
    DaprPath = "dapr"
});

var apiservice = builder.AddProject<Projects.AspireTest_ApiService>("apiservice")
    .WithDaprSidecar("api_service")
    .ExcludeFromManifest();

builder.AddProject<Projects.AspireTest_Web>("webfrontend")
    .WithReference(apiservice)
    .WithDaprSidecar("web_frontend")
    .ExcludeFromManifest();

builder.AddProject<Projects.AspireTest_TestApp>("test"); // Added to try to fix azd error
```

Even if that would work (fingers crossed!), azd chokes with any command on the above:
```
rudi@rudismacstudio AspireTest % azd deploy
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1035a7314]

goroutine 1 [running]:
github.com/azure/azure-dev/cli/azd/pkg/project.(*DotNetImporter).readManifest(0x140000b9130, {0x103d0d5a8, 0x140003fd9b0}, 0x1400042cb60)
	/Users/runner/work/1/s/cli/azd/pkg/project/dotnet_importer.go:281 +0x704
github.com/azure/azure-dev/cli/azd/pkg/project.(*DotNetImporter).Services(0x140000b9130?, {0x103d0d5a8, 0x140003fd9b0}, 0x14000155810, 0x4f?)
	/Users/runner/work/1/s/cli/azd/pkg/project/dotnet_importer.go:147 +0x50
github.com/azure/azure-dev/cli/azd/pkg/project.(*ImportManager).ServiceStable(0x14000496540, {0x103d0d5a8, 0x140003fd9b0}, 0x14000155810)
	/Users/runner/work/1/s/cli/azd/pkg/project/importer.go:64 +0x24c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*HooksMiddleware).registerServiceHooks(0x140000b9180, {0x103d0d5a8?, 0x140003fd9b0?}, 0x10?, 0x10?)
	/Users/runner/work/1/s/cli/azd/cmd/middleware/hooks.go:147 +0xc8
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*HooksMiddleware).Run(0x140000b9180, {0x103d0d5a8?, 0x140003fd800?}, 0x140006172c0)
	/Users/runner/work/1/s/cli/azd/cmd/middleware/hooks.go:69 +0x114
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x103d0d5a8, 0x140003fd800})
	/Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*TelemetryMiddleware).Run(0x14000121b80, {0x103d0d5a8, 0x1400053b980}, 0x140006172c0)
	/Users/runner/work/1/s/cli/azd/cmd/middleware/telemetry.go:85 +0x6f4
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x103d0d5a8, 0x1400053b980})
	/Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*ExperimentationMiddleware).Run(0x103855230?, {0x103d0d5a8, 0x1400053b980}, 0x140006172c0)
	/Users/runner/work/1/s/cli/azd/cmd/middleware/experimentation.go:64 +0x338
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x103d0d5a8, 0x1400053b980})
	/Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*DebugMiddleware).Run(0x1400000f350, {0x103d0d5a8, 0x1400053b980}, 0x140006172c0)
	/Users/runner/work/1/s/cli/azd/cmd/middleware/debug.go:48 +0x30c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x103d0d5a8, 0x1400053b980})
	/Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction(0x14000508570, {0x103d0d5a8, 0x1400053b980}, 0x103a807c0?, {0x103d01af8?, 0x140001e2000})
	/Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:131 +0x1e4
github.com/azure/azure-dev/cli/azd/cmd.(*CobraBuilder).configureActionResolver.func1(0x14000478500, {0x1043d7fe0?, 0x0, 0x0})
	/Users/runner/work/1/s/cli/azd/cmd/cobra_builder.go:142 +0x3a4
github.com/spf13/cobra.(*Command).execute(0x14000478500, {0x1043d7fe0, 0x0, 0x0})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x554
github.com/spf13/cobra.(*Command).ExecuteC(0x14000422a00)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x318
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(0x103d0d570?, {0x103d0d570?, 0x1043d7fe0?})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895 +0x48
main.main()
	/Users/runner/work/1/s/cli/azd/main.go:61 +0x1c4
```

I can raise it on the azd repo, but I'm assuming it's more Aspire related?

**Comment by davidfowl** [comment]
Deploying dapr to aca is currently unsupported. It will be supported in a later preview. 

cc @philliphoff

**Comment by davidfowl** [comment]
I just saw a demo of this working 😄. Stay tuned!

**Comment by davidfowl** [comment]
@philliphoff ok to close this right?
