### ISSUE TITLE
Change how container connection strings resolve the right endpoint

### ISSUE THREAD

**Issue by AndyVanDePutte** [dotnet/aspire#844]
We should change how allocation endpoints are determine the connection string by using an endpoint called "default" instead of using `SingleOfDefault` everywhere.

## Original Issue

Hi,

I have an Aspire application with an sql-container:

```

private static void Main(string[] args)
    {
        var builder = DistributedApplication.CreateBuilder(args);

        #region Sql Server Container

        var dbserver = builder.AddSqlServerContainer("sql");
        var emadb = dbserver.AddDatabase("EmaDb");
        var shopdb = dbserver.AddDatabase("ShopDb");
        
        dbserver.WithServiceBinding(1433, 1433);

        #endregion

        //builder.AddProject<Projects.AVDP_MyTicket_EventWorkerService>("eventworkerservice")
        //    .WithReference(emadb)
        //    .WithReference(shopdb);

        var app = builder.Build();
        app.Run();
    }

```

The container with the sql server is created and because of "dbserver.WithServiceBinding(1433, 1433)" I can connect with my SSMS to this database...

But once I uncomment the 3 lines (with the .WithReference to the databases), it gives me errors on the app.Run().
When I comment out 'dbserver.WithServiceBinding(1433, 1433)', the app is working, but I'm not able to connect with SSMS anymore to the database.

So my question is: what is the correct way to open the 1433 port on the sql container to be availabe on the host machine (in ssms for example).

thx a lot
Andy

**Comment by davidfowl** [comment]
You said "it gives me errors" , what errors?

**Comment by AndyVanDePutte** [comment]
> You said "it gives me errors" , what errors?

Well.. I simplified the application.. When I start with the .NET Aspire Starter application and update the following code inthe AppHost program.cs: file

```
var dbserver = builder.AddSqlServerContainer("sql");
var shopdb = dbserver.AddDatabase("ShopDb");

dbserver.WithServiceBinding(1433, 1433);

var apiservice = builder
    .AddProject<Projects.AspireApp1_ApiService>("apiservice")
    .WithReference(shopdb);

var app = builder.Build();
app.Run();
```

receive the following error:

```
info: Aspire.Dashboard.DashboardWebApplication[0]
      Now listening on: http://localhost:15069
info: Aspire.Dashboard.DashboardWebApplication[0]
      OTLP server running at: http://localhost:16254
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.InvalidOperationException: Sequence contains more than one element
         at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
         at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
         at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
         at Aspire.Hosting.ApplicationModel.SqlServerContainerResource.GetConnectionString() in /_/src/Aspire.Hosting/SqlServer/SqlServerContainerResource.cs:line 29
         at Aspire.Hosting.ApplicationModel.SqlServerDatabaseResource.GetConnectionString() in /_/src/Aspire.Hosting/SqlServer/SqlServerDatabaseResource.cs:line 25
         at Aspire.Hosting.ResourceBuilderExtensions.<>c__DisplayClass7_0`1.<WithReference>b__0(EnvironmentCallbackContext context) in /_/src/Aspire.Hosting/Extensions/ResourceBuilderExtensions.cs:line 136
         at Aspire.Hosting.Dcp.ApplicationExecutor.CreateExecutablesAsync(IEnumerable`1 executableResources, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 397
         at Aspire.Hosting.Dcp.ApplicationExecutor.CreateContainersAndExecutablesAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 150
         at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 75
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 78
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Could not stop project 'apiservice': k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'NotFound', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"executables.usvc-dev.developer.microsoft.com \"apiservice\" not found","reason":"NotFound","details":{"name":"apiservice","group":"usvc-dev.developer.microsoft.com","kind":"executables"},"code":404}

   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.DeleteClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, String name, V1DeleteOptions body, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, String dryRun, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Aspire.Hosting.Dcp.KubernetesService.<>c__DisplayClass12_0`1.<<DeleteAsync>b__0>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 109
--- End of stack trace from previous location ---
   at Aspire.Hosting.Dcp.KubernetesService.ExecuteWithRetry[TResult](DcpApiOperationType operationType, String resourceType, Func`2 operation, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 198
   at Aspire.Hosting.Dcp.ApplicationExecutor.DeleteResourcesAsync[RT](String resourceName, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 633

```

**Comment by AndyVanDePutte** [comment]
When playing around with it... when I specify a host-port when adding the sql container, It all works...

`var dbserver = builder.AddSqlServerContainer("sql", "VerySecretPassword", 1433);`

I was not aware that 1433 was not the default host port, but a random port was assigned.

Thx a lot!

**Comment by murh-lego** [comment]
> You said "it gives me errors" , what errors?

When you configure service binding such as 

````
var rabbit = builder.AddRabbitMQContainer("rabbit")
.WithServiceBinding(5672, 5672)
.WithServiceBinding(15672, 15672);

var sql = builder.AddSqlServerContainer("sql")
.WithServiceBinding(1433, 1433);
````

Calls to `GetConnectionString` to each of the container resources will throw because of allocated endpoints

![image](https://github.com/dotnet/aspire/assets/149667205/af01aca4-3e27-4cf4-8fa3-63462587eeb8)

I'm probably understanding this wrong :D So please do help :D 

Me as I guess the author of this issue wanted to expose these standard ports so I can have it uniformly the same, and not have to see what my dynamically allocated ports are from the dashboard or peeking into environment variables

**Comment by davidfowl** [comment]
cc @mitchdenny should we do something here? Most of our containers would fail like this in connection string resolution?

**Comment by mitchdenny** [comment]
There are a few choices here. The first is that we could simply change the `GetConnectionString(...)` methods to be more forgiving of having multiple allocated endpoints and instead find the endpoint based on the binding name. Another option is that we make connection string generation somewhat pluggable (which we may need to do anyway).

**Comment by davidfowl** [comment]
> There are a few choices here. The first is that we could simply change the GetConnectionString(...) methods to be more forgiving of having multiple allocated endpoints and instead find the endpoint based on the binding name

This is what I think we should be doing.

**Comment by davidfowl** [comment]
@JamesNK this is a good one for P4

**Comment by davidfowl** [comment]
@BrennanConroy moving to you

**Comment by davidfowl** [comment]
Moved to P5

**Comment by davidfowl** [comment]
All container resources now use a named endpoint as their default and that's what the connection string is based on.
