### ISSUE TITLE
eShopLite Exception When Clicking Cart Icon

### ISSUE THREAD

**Issue by ardalis** [dotnet/aspire#849]
Steps to Reproduce:
Run eShopLite
Go to Front End project (localhost:5266)
Click on the Cart icon at the top

Result:
```
Grpc.Core.RpcException: Status(StatusCode="NotFound", Detail="Basket with buyer id user does not exist")
   at MyFrontend.Services.BasketServiceClient.CheckoutBasketAsync(String buyerId) in C:\dev\github-ardalis\aspire\samples\eShopLite\MyFrontend\Services\BasketServiceClient.cs:line 60
   at MyFrontend.Components.Cart.HandleCheckout() in C:\dev\github-ardalis\aspire\samples\eShopLite\MyFrontend\Components\Cart.razor:line 41
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<WaitForQuiescence>g__ProcessAsynchronousWork|54_0()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.WaitForQuiescence()
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.SendStreamingUpdatesAsync(HttpContext httpContext, Task untilTaskCompleted, TextWriter writer)
```

**Comment by mitchdenny** [comment]
Hi Steve!

The sample in the aspire repo is more of a test jig we use whilst building out the Aspire libraries. For more fully featured sample you probably want to check out the https://github.com/dotnet/eshop sample.

Sometimes we have "bugs" like this in the sample so that we can quickly launch it and click something and see something (like an error) pop up in the dashboard.

**Comment by timheuer** [comment]
Closing in favor of tracking any change in the samples repo itself: https://github.com/dotnet/aspire-samples/issues/36
